### ISSUE TITLE
Text align not behaving as expected 

### ISSUE THREAD

**Issue by coreysimons** [excalidraw/excalidraw#1770] opened 2020-06-15 19:41 UTC
Text position behaves the same regardless of the alignment chosen. 

This recording is from Excalidraw 
![text-align](https://user-images.githubusercontent.com/28794556/84698547-d070ba00-af04-11ea-800e-d10a97c72487.gif)

 The following recording is how I expect the text position to behave. This recording is from Sketch.
![text-align-sketch](https://user-images.githubusercontent.com/28794556/84698811-4d039880-af05-11ea-93c1-2f37cf906e80.gif)

Is the current Excalidraw behavior working as intended? I can't see any difference between the three options. The current behavior is slowing down my use of the app significantly.

**Comment by vjeux** [comment] 2020-06-15 19:43
Right now the alignment only works for multiline. The behavior you described is the expected one for excalidraw but no one actually implemented yet. If you would like to, that would be highly impactful!

**Comment by coreysimons** [comment] 2020-06-15 19:49
Thanks for the speedy reply. I am new to excalidraw after a colleague recently recommended it. It has quickly become my go-to tool for quick diagramming. I am impressed with so much of the UX and interface decisions. Big thank you and respect to everyone involved. 

This text behavior is the only thing so far that I have come across that is causing me issues. 

I work on the design side so sadly I can't help with engineering/development. I'll reach out to my team and see if anyone wants to contribute.

**Comment by dwelle** [comment] 2020-06-15 19:52
Duplicate of https://github.com/excalidraw/excalidraw/issues/1326 & https://github.com/excalidraw/excalidraw/issues/1327 unless I misunderstand.

Will fix this when I'm available.

**Closed by dwelle** 2020-06-15 19:52 UTC
