### ISSUE TITLE
CLI tooling to export the excalidraw file as PNG or SVG

### ISSUE THREAD

**Issue by marcofranssen** [excalidraw/excalidraw#2422] opened 2020-11-27 13:38 UTC
Is there any CLI tooling available that I can use to export my excalidraw files as PNG or SVG?

This would be very beneficial in static page generation.

**Comment by lipis** [comment] 2020-11-27 13:58
Duplicate of #1261

If you are using Gatsby.. this is something that you could use; https://github.com/excalidraw/gatsby-embedder-excalidraw

**Closed by lipis** 2020-11-27 13:58 UTC
Labels: duplicate
