### ISSUE TITLE
Obsidian version Macos - locked image undo visual glitch

### ISSUE THREAD

**Issue by FederaikLudikon** [excalidraw/excalidraw#6362] opened 2023-03-16 22:17 UTC
I Made a little video to illustrate the glitch. Briefly : when I press CMD+Z and the cursor is hovering onto a locked image, a replica of the image shows temporarily on overlay.
Macos, latest version.
https://youtu.be/tszv7XZNXx0

**Comment by zsviczian** [comment] 2023-03-17 06:41
Thanks for raising. The replica image showing is the hover preview which is triggered by the CMD button. As such this is by design.

I've added a feature request to the Obsidian plugin's github for disabling hover preview for locked elements: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1060

I am going to close this issue. Let's continue the conversation on the other issue I just created.

**Closed by zsviczian** 2023-03-17 06:41 UTC
