### ISSUE TITLE
Blank page besides the Github logo

### ISSUE THREAD

**Issue by rrousselGit** [excalidraw/excalidraw#488] opened 2020-01-21 09:41 UTC
:wave:

Since today (yesterday it was working fine), I have a blank-page with a bunch of errors in the console:

Using Chrome:
> Version 79.0.3945.130 (Official Build) (64-bit)

<img width="1792" alt="Screenshot 2020-01-21 at 09 40 15" src="https://user-images.githubusercontent.com/20165741/72793210-16657280-3c32-11ea-8722-14f21a7767a5.png">

**Comment by dwelle** [comment] 2020-01-21 09:53
This looks like a problem with initialization caused by invalid data in `localStorage`. Try running `localStorage.clear()` in your console and refresh.

We need to fix this in #471

**Comment by rrousselGit** [comment] 2020-01-21 09:59
That indeed did the trick 👌

**Comment by dwelle** [comment] 2020-01-21 10:04
Cool. I'll close this in favor of #471.

**Closed by dwelle** 2020-01-21 10:04 UTC
Labels: bug
