### ISSUE TITLE
Free hand drawing on the iPad is inconsistent

### ISSUE THREAD

**Issue by aloknnikhil** [excalidraw/excalidraw#3502] opened 2021-04-25 22:07 UTC
Opening this based on the discussion in #3468 

Free-hand drawing on the iPad (Safari / Firefox / Chrome) is inconsistent with the strokes being eaten up sometimes. Demonstrated below.

https://user-images.githubusercontent.com/8571509/116011078-e694df80-a5d7-11eb-891b-bc3650ca8eee.mov

**Comment by j-f1** [comment] 2021-04-25 22:51
I'm wondering if this would be fixed by calling preventDefault when detecting a pointer down event.

**Comment by dwelle** [comment] 2021-04-26 08:53
> I'm wondering if this would be fixed by calling preventDefault when detecting a pointer down event.

Yeah, it may be the issue since we've recently moved away from doing it to solve excalidraw integration issues: https://github.com/excalidraw/excalidraw/pull/3207 — as such, going back to it is probably not something we wanna do.

@aloknnikhil just to confirm this, can you check if it reproduces in here https://excalidraw-git-aakansha-export-excalidraw.vercel.app/? This should be before we stopped preventing the default.

**Comment by aloknnikhil** [comment] 2021-04-26 16:15
Hmm. Looks like the text selection bug is back in this one ➝  https://excalidraw-git-aakansha-export-excalidraw.vercel.app/?
which is preventing me from testing the fix for this issue.

**Comment by dwelle** [comment] 2021-04-26 20:09
I think you should be able to open dev console on iPadOS, and from there paste this in to fix it:

```
var s = document.createElement('style'); s.innerHTML = '.visually-hidden { user-select: none }'; document.querySelector('head').appendChild(s);
```

**Comment by pjm17971** [comment] 2021-05-24 17:02
Yeah, this issue makes excalidraw not work for freehand drawing on the iPad. It's even worse if you don't use cursive writing. Every other stroke is lost, so it's really not functional. Really hoping this gets picked up and fixed, it's our number one issue now that we have cloud file storage/sharing in excalidraw+.

**Comment by dwelle** [comment] 2021-05-24 20:03
@pjm17971 can you try disabling Scribble feature if it improves the situation (https://twitter.com/steveruizok/status/1389889293913571328)?

**Comment by kevinjalbert** [comment] 2021-05-24 22:07
@dwelle I disabled Scribble and it made it work as expected.

I followed the tweet to the Apple forum post and found this post -- https://mikepk.com/2020/10/iOS-safari-scribble-bug/. Seems like some fix was suggested there. Not sure if that is a change that could be made?

**Comment by dwelle** [comment] 2021-05-24 22:14
Interesting, thanks for the link! Can't test myself. /cc @steveruizok unclear if we can do that without breaking other things.

**Comment by pjm17971** [comment] 2021-05-25 02:13
For me turning off Scribble makes strokes work 80% of the time vs maybe 50% before. Below is output from both settings. Better but still can't use. This is on an iPad Pro.

<img width="943" alt="Screen Shot 2021-05-24 at 7 12 22 PM" src="https://user-images.githubusercontent.com/1288813/119429625-09441200-bcc4-11eb-8221-a071e33307eb.png">

**Comment by dwelle** [comment] 2021-05-25 19:12
For comparison, how does it work in this sandbox? https://perfect-freehand-example-steveruizok.vercel.app/

**Comment by steveruizok** [comment] 2021-05-25 19:18
There’s an issue here that may be related https://github.com/steveruizok/perfect-freehand/issues/11 though the best comparison would be against an Excalidraw build from before we integrated perfect freehand. I also had missed strokes on the iPad with the old pen tool... though we’re able to repro this with mouse input too, right?

**Comment by dwelle** [comment] 2021-05-25 19:34
> though we’re able to repro this with mouse input too, right?

If this is related to https://github.com/excalidraw/excalidraw/issues/3564 then yes. But since the OP issue is pre-freedraw and it never happened to me pre-freedraw I'd say no?

**Comment by pjm17971** [comment] 2021-05-25 20:38
Writing with the vercel app above works perfectly.

**Comment by h0uter** [comment] 2021-10-05 18:27
I have the same issue using excalidraw on a 2018 ipad with apple pencil 2. Strokes are missed when I write normal speed. Only when slowing down my writing to one stroke every second no strokes are missed.

The [Vercel app](https://perfect-freehand-example-steveruizok.vercel.app/)  works perfectly for me. 
It's a real shame because I want to use the excellent excalidraw integration for Obsidian in the same way as is mentioned in the issue above.

**Comment by dwelle** [comment] 2021-10-05 19:44
@h0uter oops, I thought we've solve this across the board, but apparently it's still a problem when Scribble is enabled. I'll take a look at it later — for now, if you disable Scribble (Apple Pencil settings), it should solve it.

**Comment by kishorekumarxyz** [comment] 2022-01-04 08:06
Even I am facing the same issue as shown in video of the OP.

**Comment by dwelle** [comment] 2022-01-04 11:17
@kishorekumarxyz what device? If Apple with Apple Pen, do you have Scribble enabled or not?

**Comment by rememberthis9000** [comment] 2022-01-12 02:21
@dwelle I turned off scribble and overall it works well enough, but palm rejection is iffy and iOS’s magnifying glass intermittently appears while writing.

**Comment by dwelle** [comment] 2022-02-02 14:47
@rememberthis9000 palm rejection now implemented via pen mode: https://twitter.com/excalidraw/status/1488884968243740674

**Comment by dwelle** [comment] 2022-02-05 11:29
Here's an attempted fix for the Scribble missing strokes issue: https://excalidraw-git-fixscribble-excalidraw.vercel.app/ Lemme know if you can still reproduce!

**Comment by jgonggrijp** [comment] 2022-02-05 20:48
Hand writing seems to work fine in that version with scribble enabled!

**Closed** 2022-02-06 19:07 UTC
Labels: bug, mobile

**Comment by h0uter** [comment] 2022-02-06 19:10
Handwriting works fine for me too!
Up next it would be really cool if we can actually use scribble to write text fields in Excalidraw :)

**Comment by jgonggrijp** [comment] 2022-02-07 11:23
@h0uter I'm already able to use scribble to write text fields. It's a bit tricky to get spaces detected correctly, though. Is that what you were referring to?

**Comment by cre8tiveGray** [comment] 2022-10-10 19:40
It’s that tricky part that’s annoying. I find that for some reason the text tool deselects itself randomly while I’m writing in scribble. I would love to use text, but it’s just not there… would love to be able to lock the text tool on.

**Comment by GargeeSharma60** [comment] 2024-07-26 20:38
https://github.com/user-attachments/assets/c76b4403-c75f-4980-9db6-2cd21f1b5945

![IMG_0013](https://github.com/user-attachments/assets/b065c3fd-798b-42ba-820c-edbd3e050009)
while free hand drawing with apple pencil on ipad pro the UI keeps crashing and keep going to the support web...see the attached video. It is very annoying and is really hard to use. I was planning on using this for my upcoming interview but looks like I may have to find something else.

https://github.com/user-attachments/assets/7d41d7c4-5008-4fa9-81de-6aef9a70994b

![IMG_0013](https://github.com/user-attachments/assets/a63d7103-5d9e-40d6-bf73-6cf3770e563c)
