### ISSUE TITLE
Option to provide a name to drawing

### ISSUE THREAD

**Issue by sharmasha2nk** [excalidraw/excalidraw#1623] opened 2020-05-21 08:19 UTC
When we click save currently it save as Untitled-{date}-{number}.excalidraw but in export, there is an option to provide a name to the exported file. There could be a global name field, which could be used for both save and export (prefill export name field) files.

Name field for export.
<img width="804" alt="Screenshot 2020-05-21 at 4 16 03 PM" src="https://user-images.githubusercontent.com/4423790/82538521-750a1100-9b7e-11ea-8357-d0126e7db2eb.png">

No name field for saving.
<img width="819" alt="Screenshot 2020-05-21 at 4 17 03 PM" src="https://user-images.githubusercontent.com/4423790/82538665-a84ca000-9b7e-11ea-95d5-72d4ad62b72a.png">

**Comment by dwelle** [comment] 2020-05-21 08:33
Hello.

We actually somewhat do that, but only for legacy fs API, not the one. It seems there's no open issue for this (or it's a recent regression), so I'll open one.

As for placement, in the beginning, it was in the place you suggested, but we've removed it's not a common case to name your projects so it would only add noise to the UI (and often you either save or export, not both at the same time --- which means you can name the file when you save, or name it when you export).

**Comment by sharmasha2nk** [comment] 2020-05-21 10:29
Hi,
The good part with the current save is, its fast. No popup. No windows. I prefer it remains the same. That's why suggested it to be there or somewhere with prefilled as "Untitled-{date}-{number}". Name field to be near the save option makes sense to me. And whose value could be reused in export as well, as pre-filled. For export to open a popup is fine, as there are other options as well to choose for. Save can remain as is.

**Comment by xixixao** [comment] 2020-08-04 03:23
Duplicate of #1271, let's keep the convo there.

**Closed by xixixao** 2020-08-04 03:23 UTC
