### ISSUE TITLE
Saving the session saves the file without the extension

### ISSUE THREAD

**Issue by eggei** [excalidraw/excalidraw#1750] opened 2020-06-11 16:52 UTC
Steps to reproduce:
1. Draw something
2. Save it to your local disk
3. Observe the saved file is without extension (.json)
4. Try to load the file in Excalidraw (It wont, because it doesn't see the file extension)

Browser: Chrome 83.0.4103.97

**Comment by lipis** [comment] 2020-06-11 16:59
Can confirm.. (the extension should be `.excalidraw`)

**Comment by dwelle** [comment] 2020-06-11 18:58
Duplicate of https://github.com/excalidraw/excalidraw/issues/1750 --- I assume we're talking about the new FS API since you're on CH 83. That said, I thought this bug was resolved in recent PR. I'm getting lost in the FS issues lately :).

**Closed by dwelle** 2020-06-11 18:58 UTC
Labels: bug

**Comment by eggei** [comment] 2020-06-11 21:01
Thanks for the response!
