### ISSUE TITLE
Feature Request: Enhanced File Management and Workspace Features

### ISSUE THREAD

**Issue by Nayabacademic** [excalidraw/excalidraw#8746] opened 2024-11-02 22:43 UTC
### Description
I commonly make notes and concept diagrams in **Excalidraw** , using it as a **PWA** . Though accessing and viewing files from the default file system of my machine becomes tedious and time consuming. I am aware of **Excalidraw+**  but it is not built to work with the local storage.
I think that a better navigation and file access management can be implemented to work with the current PWA , without relying on any other database.

---

### Broad Outline for Proposed Features

1. **Folder Selection**:
   - Allow users to select a specific folder on their local file system as a workspace using the File System Access API.

2. **File Listing**:
   - Display all files and subfolders within the selected folder in a sidebar for quick access and organization.

3. **Load Saved Folder**:
   - On startup, check Local Storage for a previously selected folder and prompt the user to either use that folder or select a new one.

4. **Change Folder Option**:
   - Provide functionality for users to change the selected folder, updating the Current Workspace with the new selection.

5. **Multiple tab interface**:
   - Implementation of multiple tabs for viewing different files from the local storage, if such is possible.

6. **User-Friendly Interface**:
   - Create an intuitive user interface that integrates these file management features seamlessly with the existing drawing functionalities of Excalidraw.

### Benefits
- **Improved Organization**: Users can keep their projects organized within specific folders, making it easier to manage multiple drawings.
- **Enhanced User Experience**: Quick access to recently used files and folders improves overall usability.
- **Increased Efficiency**: Dynamically accessing files without needing to upload or manage them on a server streamlines the workflow for users.

---

I acknowledge that I know less than little of the application architecture and overall storage system . Therefore, please let me know if the features I’ve mentioned are feasible to implement.  Thank you for your consideration!

**Comment by Mrazator** [comment] 2024-11-03 13:42
I don't think we will ever be implementing custom directory UI. You shall be presented with an OS-level directory when you are saving or opening a scene.

For tabs, closing as a duplicate of https://github.com/excalidraw/excalidraw/issues/1543.

**Closed by Mrazator** 2024-11-03 13:42 UTC

**Comment by Nayabacademic** [comment] 2024-11-03 14:02
Is it technically possible to do so ? If yes then I will try to implement it on my own in the future. Thankyou for your response.

**Comment by Nayabacademic** [comment] 2024-11-03 14:19
Is it technically possible to do so ?
If yes then I will try to implement it on my own in the future. Thankyou
for your response.
