### ISSUE TITLE
Export crashes Chromium

### ISSUE THREAD

**Issue by jeyemwey** [excalidraw/excalidraw#4035] opened 2021-10-08 14:27 UTC
Hi, I'm using `Ubuntu 20.04 with Gnome 3.36.8` and Chromium 94.0.4606.71, and whenever I try to export an Excallidraw file, it crashes my whole browser.

__To reproduce:__

1. Go to excallidraw.com
2. Draw something
3. Hit export (as a .excallidraw file) and use your native OS interface to select a place to save
4. Experience the crash.

I have seen that you seem to use https://github.com/GoogleChromeLabs/browser-fs-access for the Save file dialog. When trying to save a file [in their demo app](https://browser-fs-access.glitch.me/), my browser did not crash.

I'm not sure if I'm holding it wrong or its an error with chromium, but since Saving Things seems work on other websites, I figured it might be on your site.

**Comment by acorpuz101** [comment] 2021-11-02 17:16
I'm getting the same thing. Using Edge (IE) which is also based on Chromium. It crashes when I save as png or export

Windows 10
Edge
excalidraw.com

**Comment by dwelle** [comment] 2021-11-02 17:30
@acorpuz101 can't reproduce. Can you share the drawing? If private, can you share the these stats? (right-click on the canvas → show nerds for stats)

![image](https://user-images.githubusercontent.com/5153846/139915895-29acf2b9-8708-4ffe-9b8d-dc72151ca382.png)

**Comment by acorpuz101** [comment] 2021-11-02 17:38
@dwelle , here you go.
![excalidraw-stats-000](https://user-images.githubusercontent.com/8561349/139916938-b0043a79-3c16-4783-a835-703e39ffdadd.PNG)

While this is looked into, do you know where the data is stored locally? Maybe I can try transferring it to another computer/browser to try and save it. I tried opening Excalidraw in Chrome but it didn't have it cached.

**Comment by dwelle** [comment] 2021-11-02 18:20
That drawing looks very small so it's unclear why it'd crash.  Just to clarify, crashing means the tab or the browser dies? Meaning, there's no way to check the console for errors.

Unless there's something very specific in the drawing that would cause the crash, I don't see how/why. I can't reproduce, especially not without the underlying data.

> While this is looked into, do you know where the data is stored locally? Maybe I can try transferring it to another computer/browser to try and save it. I tried opening Excalidraw in Chrome but it didn't have it cached.

Does saving to disk crash the browser as well? Otherwise, you should be able to select all elements and copy them (`Cmd/Ctrl-C`), then go to the other browser and paste (`Cmd/Ctrl-V`).

**Comment by acorpuz101** [comment] 2021-11-02 19:17
I was able to copy and paste it to Chrome and both Export and Save it.

Here's the excalidraw file with some things renamed for privacy.
[IE-crash.zip](https://github.com/excalidraw/excalidraw/files/7463493/IE-crash.zip)

With Edge, it'll crash when I Export it and Save it as a PNG.

Microsoft Edge | 95.0.1020.40 (Official build) (64-bit)
-- | --
Revision | 1f61f1c45c1e4229af88888771afd46a90ce2e88
Operating system | Windows 10 Version 20H2 (Build 19042.1288)
JavaScript | V8 9.5.172.25

**Comment by dwelle** [comment] 2021-11-02 19:58
> Here's the excalidraw file with some things renamed for privacy.
> [IE-crash.zip](https://github.com/excalidraw/excalidraw/files/7463493/IE-crash.zip)

It works fine on my system. The only difference between us is I'm running `Windows 10 Version 21H1`. If it was only the PNG export that was causing problems I'd say it's related to memory in some way, but since it's also saving to disk, then that shouldn't be memory-related. Only other option that leaves is filesystem-related. But both Chrome and Edge use the latest filesystem API and it should handle it identically, and you're saying that Chrome works.

I'm out of ideas :/

**Comment by jeyemwey** [comment] 2021-11-02 20:37
Since this is happening on multiple platforms (Windows & Gnome Ubuntu), and in multiple iterations of chromium (Chromium & Edge), I’d suggest to open a bug report with the chromium team on this at crbug.com.

**Comment by dwelle** [comment] 2021-11-02 20:54
It's hard to open a crbug issue on something I can't repro so one of you would have to do it yourselves (they'll likely want more data from your systems). Ideally a small reproducible case (outside of Excalidraw, e.g. on Codesandbox) would be good as well, but you said that browser-fs-access is working for you. Not sure what the root cause is here.

**Comment by dwelle** [comment] 2021-11-09 18:36
Can either or both of you check these deployments? You'll have to copy the drawing elements that cause the crash, and paste them in (`Cmd/Ctrl-C & Cmd/Ctrl-V`).

1. https://excalidraw-q9t4cpreo-excalidraw.vercel.app
2. https://excalidraw-cigqdgbvg-excalidraw.vercel.app

Another question: do your drawings contain images?

**Comment by acorpuz101** [comment] 2021-11-09 19:00
@dwelle I tried it just now. The two new deployments were able to save my content fine, both as an export and as a png. I tried the current deployment on excalidraw again and it still crashed the browser.

No images on mine.

**Comment by dwelle** [comment] 2021-11-09 19:06
Actually, those are not new deployments, but older ones.

Can you check this one? https://excalidraw-9xy6v6vn6-excalidraw.vercel.app 

Appreciated!

**Comment by acorpuz101** [comment] 2021-11-09 19:11
@dwelle Export and PNG both worked on that version for me.

**Comment by dwelle** [comment] 2021-11-09 19:20
That's strange. That last deployment is newer than your initial report (7 days ago). Are you sure you're exporting the same drawing on all the deployments including when trying out the current deployment on excalidraw.com?

In any case, you can also try these, but from this point I'm just throwing these out mostly on random:

1. https://excalidraw-q6attvfv2-excalidraw.vercel.app/
2. https://excalidraw-1l4ezr353-excalidraw.vercel.app/
3. https://excalidraw-mlirtawcq-excalidraw.vercel.app/

**Comment by acorpuz101** [comment] 2021-11-09 19:29
@dwelle Yeah it's exactly the same. Before I started with today's deployments, I tried it on the live deployment (excalidraw.com), it crashed as usual. From there, I copied and pasted from the live deployment

Those 3 worked too. Same process: opened up live deployment, copied and pasted from there.

**Comment by dwelle** [comment] 2021-11-09 21:05
The (3) should point to the current production deployment. If it works on (3) but not on https://excalidraw.com, you must be running an older version (happens a lot due to serviceWorker caching). Can you go to https://excalidraw.com, open the stats for nerds and copy version info? (screenshot it or click it to copy to clipboard). You can also hard-refresh (don't recall how to do it on Mac now) which should load the latest version.

**Comment by acorpuz101** [comment] 2021-11-09 21:25
As expected, the version info for (3) and excalidraw.com are the same: 2021-11-09T11:16:32Z-bc6b066 .

I tried a hard refresh on Windows using CTRL+F5 and CTRL+Click-Reload-Icon and the excalidraw still crashes when saving a PNG.

**Comment by dwelle** [comment] 2021-11-10 21:58
@acorpuz101 no idea. But [it'll possibly be solved](https://github.com/excalidraw/excalidraw/issues/4227#issuecomment-965621147) in next version on Chrome (96).

You can check that in the beta channel today https://www.google.com/chrome/beta/

**Comment by dwelle** [comment] 2021-11-19 15:25
This should be fixed with Chrome 96. If not, please comment here and we'll reopen!

**Closed by dwelle** 2021-11-19 15:25 UTC

**Comment by haapjari** [comment] 2022-12-21 11:10
Having the same issue again in Chrome 108.0.53.59.124, running on Ubuntu 22.04 LTS on Wayland.

**Comment by dwelle** [comment] 2022-12-21 13:15
> Having the same issue again in Chrome 108.0.53.59.124, running on Ubuntu 22.04 LTS on Wayland.

@haapjari Can you open a new issue with steps and the error message + stack trace (if there's any)? Thanks!
