### ISSUE TITLE
[feature request] add the ability to search

### ISSUE THREAD

**Issue by ethanneff** [excalidraw/excalidraw#6492] opened 2023-04-19 15:36 UTC
`command + f` appears to not work. It would be nice to see text highlighted when searching. Bonus points if we can navigate to the text.

**Comment by siddhant1** [comment] 2023-05-07 09:26
Since excalidraw renders on canvas, this looks really difficult since everything is rendered in pixels, there is a workaround of setting elements off screen and searching, but would def impact performance!

**Comment by ad1992** [comment] 2023-05-08 09:43
The search would be going through all text elements `text` attribute and depending on whether we want to allow fuzzy search (for which we can use a library). However we will need to highlight the search results in some way for which we can use element's position and scroll to that element in canvas.

closing this as duplicate of https://github.com/excalidraw/excalidraw/issues/3826 and there were multiple draft PRs for the same, one of them - https://github.com/excalidraw/excalidraw/pull/4570 so we can pick it up from there

**Closed by ad1992** 2023-05-08 09:43 UTC
