### ISSUE TITLE
Moving with middle button paste unwanted elements on Linux

### ISSUE THREAD

**Issue by jrmi** [excalidraw/excalidraw#1383] opened 2020-04-11 19:37 UTC
On linux, if something has been copied beforehand and the screen is moved with the middle mouse button, the copied element is pasted. (The middle button on linux can paste something).

If the mouse has moved, the pasted item should not be taken into account.

![Peek 11-04-2020 21-36](https://user-images.githubusercontent.com/571533/79053297-90f3cc00-7c3c-11ea-82c7-b6f28d606c22.gif)

**Comment by dwelle** [comment] 2020-04-11 20:12
duplicate of https://github.com/excalidraw/excalidraw/issues/961 (and https://github.com/excalidraw/excalidraw/issues/1289). Not sure what we can do on our side.

**Comment by jrmi** [comment] 2020-04-11 20:21
My bad, i only search in open bugs.

I think we may prevent the paste event by preventing the bubbling of the release button event if we have just release the middle mouse button after panning the view ?

**Comment by dwelle** [comment] 2020-04-11 20:24
Preventing `pointerup` event doesn't affect `paste`. The best we could do is to disable `paste` until ~100ms after `pointerup` event fired, but that seems hacky and may have unintended consequences.

**Comment by jrmi** [comment] 2020-04-12 08:04
Do you think we can disable the paste event as soon as the `pointerdown` event as been sent and when the mouse move then re-enableit immediately during the pointerup event handle ?

I use a lot of web drawing application where it doesn't cause any trouble like draw.io, I can't think it's impossible to find a way to do it well in excalidraw ;-)

I'll try some fixes…

**Comment by jrmi** [comment] 2020-04-12 15:06
I've just create a new PR for this bug.

**Closed** 2020-04-13 13:10 UTC
Labels: Linux

**Comment by TKperson** [comment] 2023-07-28 19:29
why does this bug still exist in excalidraw.com? it has been 3 years
