### ISSUE TITLE
When some elements are selected, and option+drag is performed, do not perform reselection of elements under pointer

### ISSUE THREAD

**Issue by sompylasar** [excalidraw/excalidraw#703] opened 2020-02-04 20:04 UTC
Currently, when I do option+drag of selected elements, it matters where I start the drag: it must be within one of the selected elements, otherwise the selection changes to the element under pointer and that element gets selected and copied instead.

This is annoying when certain elements are hard to select (e.g. overlapping text elements), and cmd+c/cmd+v does not work, so only option+drag works for copy/pasting.

It would be nice if the behavior is adjusted to not replace the selection if option is pressed so that the originally selected elements are copied.

**Comment by dwelle** [comment] 2020-02-04 21:13
Possible duplicate of https://github.com/excalidraw/excalidraw/issues/671

**Comment by vjeux** [comment] 2020-03-15 19:08
This is not a duplicate of #671.

I agree it's annoying. I'm not really sure what the right fix is though.

**Comment by j-f1** [comment] 2020-03-15 19:11
Maybe we could switch the cursor to the `copy` cursor when option is pressed, and maintain the relative position of the cursor and the new element when dragging?

**Comment by dwelle** [comment] 2020-03-15 19:33
I'm planning to do some changes to how selection is handled, to align with editors out there. We're certainly doing many things in suboptimal ways. Will see if it covers this, too.

**Comment by dwelle** [comment] 2020-08-29 19:49
> I'm planning to do some changes to how selection works related to z-indexes so as to align with editors out there. We're certainly doing many things in suboptimal ways. Should cover this, too.

I'm not sure what I meant by this since it's been a while, but I pretty sure it was https://github.com/excalidraw/excalidraw/pull/2023. As of now if you have a selected element it doesn't matter if you click on an element with a higher z-index if you're dragging/resizing.

As such, your issue should be resolved @sompylasar. Lemme know if I misunderstood and I'll reopen.

**Closed by dwelle** 2020-08-29 19:49 UTC
