### ISSUE TITLE
Default font does not support handwriting style when I use korean characters

### ISSUE THREAD

**Issue by mwmw7** [excalidraw/excalidraw#7648] opened 2024-02-03 06:51 UTC
Hello, I am Branden,

I'm a big fan of Excalidraw. However, I've noticed that the current font does not support a beautiful handwriting style for Korean characters.

I have already checked out the [Chrome extension](https://chromewebstore.google.com/detail/excalidraw-custom-font/afbeaojffbjckicjpkecknoocdpmgoah?pli=1) and enabled a handwriting style for Korean, which works great. However, I think it would significantly enhance the user experience if Excalidraw could automatically detect Korean text and switch to a suitable handwriting style font.

Do you have any suggestions on how to implement this feature? If there aren't any existing solutions or ideas, I would like to propose my contribution through a PR to address this. What are your thoughts on this?

**Comment by Mrazator** [comment] 2024-10-16 20:04
We will be releasing support for the whole CJK soonish! (https://github.com/excalidraw/excalidraw/pull/8530)

Feel free to give us early feedback, preview is available here:
https://excalidraw-git-mrazator-first-class-support-chinese-excalidraw.vercel.app/

Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/8408

**Closed by Mrazator** 2024-10-16 20:04 UTC
Labels: font
