### ISSUE TITLE
Add font with Chinese characters (CJK)

### ISSUE THREAD

**Issue by ParadiseWitch** [excalidraw/excalidraw#1290] opened 2020-04-07 05:27 UTC

**Comment by dwelle** [comment] 2020-04-07 08:40
Hello. Can you elaborate?

**Comment by lipis** [comment] 2020-04-07 08:50
Our hand writing font to support Chinese

**Comment by dwelle** [comment] 2020-04-07 08:51
Right, but that's not very tractable:

![image](https://user-images.githubusercontent.com/5153846/78649453-c2c40600-78bd-11ea-940a-8c0d8d460254.png)

**Comment by dwelle** [comment] 2020-04-07 09:00
That said, I bet there are some existing Chinese fonts that look handwritten we could use. Though we'd have to detect Chinese is being written and swap fonts for given element.

**Comment by lipis** [comment] 2020-04-07 09:04
As someone already mentioned, we could have a fall back font.. Maybe it's also a time to reconsider saving the type and the actual font name into the schema. Should be backwards compatible, but it will be easier to manage those things.

**Comment by ParadiseWitch** [comment] 2020-04-08 10:28
> That said, I bet there are some existing Chinese fonts that look handwritten we could use. Though we'd have to detect Chinese is being written and swap fonts for given element.
> 
> The font would have to be lazyloaded (how big are these fonts?).

**Comment by vjeux** [comment] 2021-02-05 19:24
We're looking for another handwritten font. If you could add suggestions for the fonts listed in this issue that'd be useful. Thanks! #2945

**Comment by dreamkidd** [comment] 2021-04-30 03:49
![image](https://user-images.githubusercontent.com/11213228/116645505-9a1b1c80-a9a8-11eb-95b1-487312ca299c.png)

I think this feature could change to user config ，just like libaries ，user could upload font what they want and use it

**Comment by dai-shi** [comment] 2021-04-30 03:59
> I think this feature could change to user config

Recently, I lean to this idea for personal use (meaning, non collaboration).
This would fix the font licensing issue (the font I want to use doesn't allow embedding in the app) and CJK code point overlapping issue.

**Comment by dreamkidd** [comment] 2021-04-30 04:47
> > I think this feature could change to user config
> 
> Recently, I lean to this idea for personal use (meaning, non collaboration).
> This would fix the font licensing issue (the font I want to use doesn't allow embedding in the app) and CJK code point overlapping issue.

i am using excalidraw in other embed app ，if the `@excalidraw/excalidraw` could add some api to change font , it will be great full

**Comment by Borber** [comment] 2021-09-01 09:39
Really need this feature

**Comment by hulkbig** [comment] 2024-03-19 16:13
@ParadiseWitch hi, you can try my fork version: [https://excalidraw-zh.com/](https://excalidraw-zh.com/)

**Comment by Mrazator** [comment] 2024-10-16 19:50
We will be releasing support for the whole CJK soonish! (https://github.com/excalidraw/excalidraw/pull/8530)

Feel free to give us early feedback, preview is available here:
https://excalidraw-git-mrazator-first-class-support-chinese-excalidraw.vercel.app/

Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/8408

**Closed by Mrazator** 2024-10-16 19:50 UTC
Labels: enhancement, discussion, font
