### ISSUE TITLE
Can't rotate groups

### ISSUE THREAD

**Issue by eendeego** [excalidraw/excalidraw#1727] opened 2020-06-08 03:54 UTC
Repro

* Create multiple objects
* Rotate individually works
* Group objects
* Try to rotate

Expected behavior

* Handles for rotation show up and can be used for rotation

Actual behavior

* Handles for rotation do not show up

![Screen Recording 2020-06-07 at 8 46 25 PM](https://user-images.githubusercontent.com/101878/83991239-027c8d80-a901-11ea-970e-1d9224140ee0.gif)

**Comment by lipis** [comment] 2020-06-08 08:51
Duplicate of #1168

**Closed by lipis** 2020-06-08 08:51 UTC
