### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4282] opened 2021-11-19 17:30 UTC
I fetched the latest changes. I get this error when I try to build:
`Property 'metaKey' does not exist on type 'KeyboardEvent | React.KeyboardEvent<Element>'`

This is building a copy of master. No local changes, except `cross-env` added in package.json to these two lines:
```javascript
    "build:app:docker": "cross-env REACT_APP_DISABLE_SENTRY=true react-scripts build",
    "build:app": "cross-env REACT_APP_GIT_SHA=$VERCEL_GIT_COMMIT_SHA react-scripts build",
```

![image](https://user-images.githubusercontent.com/14358394/142665570-6de85e88-9220-4154-b78a-1ed5728bbdeb.png)

**Comment by zsviczian** [comment] 2021-11-19 18:07
I was able to resolve the problem by reverting this 
https://github.com/excalidraw/excalidraw/blob/1c11df011a2f1eaf7f1164f475c94fc3ebe9f36b/tsconfig.json#L4
to
https://github.com/excalidraw/excalidraw/blob/a7cbe68ae8dbe3323b46aac3dd5640314e64d393/tsconfig.json#L4

@lipis : any particular reason for removing `"dom","dom.iterable",`?

**Comment by dwelle** [comment] 2021-11-19 18:15
I did that as part of using the DOM types via `@types/web`. It's unclear why that's causing a problem for your build. Have you installed latest deps?

**Comment by zsviczian** [comment] 2021-11-19 18:18
I have

**Comment by zsviczian** [comment] 2021-11-19 18:22
Now I moved on to building the excalidraw package. I am getting similar errors:
![image](https://user-images.githubusercontent.com/14358394/142672446-e479bf75-4d13-4a11-95fe-39a24fdedb15.png)

**Comment by dwelle** [comment] 2021-11-19 18:33
I've opened https://github.com/excalidraw/excalidraw/pull/4283 to revert this by upgrading. But, it'll likely be a temp fix coz I can't guarantee we won't use `@types/web` again in the future for various reasons. FYI I couldn't reproduce in my fork.

**Comment by zsviczian** [comment] 2021-11-19 18:46
In the meantime I deleted yarn.lock and node_modules, I am testing to see if a clean install of dependencies solves the issue

**Comment by dwelle** [comment] 2021-11-19 18:47
It may have been due to the fact I forgot to install the `@types/web` in the packages git folder as well. But it was still building ok both in CI and in my fork, so 🤷‍♂️.

**Comment by zsviczian** [comment] 2021-11-19 18:50
hm... now I am getting 
![image](https://user-images.githubusercontent.com/14358394/142675723-4dc10b41-2614-4375-b446-e24c023aae48.png)

**Comment by dwelle** [comment] 2021-11-19 18:51
No clue. I've done a clean install as well just to be sure. I've merged the PR, so try now.

**Closed** 2021-11-19 18:51 UTC

**Comment by zsviczian** [comment] 2021-11-19 18:56
I think the root cause is that it seems it's been years that I've updated node. I am installing the latest and will see.

**Comment by zsviczian** [comment] 2021-11-19 19:48
I updated node to 16.13 and that resolved the issue.
Sorry for the false alarm.
