### ISSUE TITLE
Suggestion: Text with background Color

### ISSUE THREAD

**Issue by schittli** [excalidraw/excalidraw#1460] opened 2020-04-20 10:58 UTC
Good afternoon
**Thank you very much for this nice tool!**

#### I have a small suggestion:
It would enhance the readability if we could define a background Color for Text. 

Thanks a lot, kind regards,
Thomas

**Comment by dwelle** [comment] 2020-04-20 11:13
duplicate of https://github.com/excalidraw/excalidraw/issues/1317 (and likely part of https://github.com/excalidraw/excalidraw/issues/1126)

**Comment by gwww** [comment] 2020-04-23 01:28
I think that #1428 is also related.

**Closed** 2020-04-23 17:07 UTC
Labels: discussion, enhancement
