### ISSUE TITLE
Add font size option

### ISSUE THREAD

**Issue by cloudrflight** [excalidraw/excalidraw#5313] opened 2022-06-16 11:43 UTC
![image](https://user-images.githubusercontent.com/95400333/174061697-363ab998-e9ec-422d-b133-b03873c5850e.png)
笔太粗，字体太小了，用笔来写字，字会很大，用文本工具输入，字体就很小，两者不能契合在一起；

**Comment by dwelle** [comment] 2022-06-16 19:51
If I understand correctly, then what you can do is resize the text using the resize handles, which will scale the font size up.

![image](https://user-images.githubusercontent.com/5153846/174152861-397be124-4cfd-4640-9d93-0c3697c07735.png)

**Comment by yamfeel** [comment] 2023-06-16 07:25
Me too. I need to configure bold.

**Comment by Mrazator** [comment] 2024-10-22 10:21
Duplicate of https://github.com/excalidraw/excalidraw/issues/5138

**Closed by Mrazator** 2024-10-22 10:21 UTC
