### ISSUE TITLE
Looking for another handwritten font

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#2945] opened 2021-02-05 19:16 UTC
The current font FG_Virgil has been an important part of the success of Excalidraw but we've received recurring feedback that it can be hard to read. We are now officially looking for another handwritten font. We will most likely keep the two fonts available within Excalidraw but haven't yet figured out how they will co-exist.

* Handwritten look and feel
* Other alphabets than just latin (Cyrillic, Greek, ...)
* License that will allow users to use it anywhere (= can be redistributed), can be hosted, and can be used for commercial. Doesn't have to be free, but if paid, the license shouldn't be based on userbase size.

We will keep the search going for a week and on Monday February 15 will select a winner and start the integration within Excalidraw.

Thanks for all your suggestions, let the hunt begin!

You can use this text for a template (or use your own):

```
Pack my box with five dozen liquor jugs!
[ ] ( ) < > ? ! . , ; ' " @ # $ % ^ & * ~ ` / \
0 1 2 3 4 5 6 7 8 9
```

--------

### Preview the following from https://fonts.excalidraw.com

- Architects Daughter
- BLOKLETTERS
- Caveat
- Comic Relief
- Fewriter
- GelPen
- Swagger
- Xarrovv

### Not on the live preview
- RocknRoll One
- [Recursive](https://github.com/excalidraw/excalidraw/issues/2945#issuecomment-774285433)
- [Zhi Mang Xing](https://github.com/excalidraw/excalidraw/issues/2945#issuecomment-774413900) - Too bold
- [Verveine](https://github.com/excalidraw/excalidraw/issues/2945#issuecomment-777768078) - Adobe

**Comment by warrenseine** [comment] 2021-02-05 19:33
You meant February I suppose.

**Comment by dwelle** [comment] 2021-02-05 19:36
Let's kick it off with a few.

All should be free for commercial use.

# [BLOKLETTERS](https://www.fontsquirrel.com/fonts/Blokletters-Potlood)

![image](https://user-images.githubusercontent.com/5153846/107080503-aa7c8a80-67f1-11eb-9530-bee45d0f66c4.png)

# [GelPen](https://www.dafont.com/gelpen.font)

![image](https://user-images.githubusercontent.com/5153846/107080518-b23c2f00-67f1-11eb-9e39-a3f9369b4e7a.png)

# [Swagger](http://fontpro.com/swagger-font-14653)

(`Swagger.ttf`, medium)

![image](https://user-images.githubusercontent.com/5153846/107080543-bb2d0080-67f1-11eb-8d22-3255375543c2.png)

# [Just Another Hand Font](https://www.fontspace.com/just-another-hand-font-f12568)

(doesn't look good in small font sizes)

![image](https://user-images.githubusercontent.com/5153846/107080533-b7997980-67f1-11eb-8fab-d000a125ef48.png)

**Comment by wietsevenema** [comment] 2021-02-05 19:42
I recognize the readability issues with FG Virgil (still love it for its quirkiness, don't make it go away!) 
My vote goes to BLOKLETTERS. Like I learned it in school, very clear.

**Comment by dawneraq** [comment] 2021-02-05 19:55
Architects Daughter might be good! It has a similar character to FG Virgil while being a little easier to read.

![excalidraw-font-architects-daughter](https://user-images.githubusercontent.com/9038965/107082125-952f3e00-67a8-11eb-8ea8-91cfaaeb73b8.png)

No support for Greek/Cyrillic though 😕

https://www.fontsquirrel.com/fonts/architects-daughter
https://fonts.google.com/specimen/Architects+Daughter

**Comment by mrchief** [comment] 2021-02-05 20:02
My vote for BLOKLETTERS since it looks good in small sizes.

**Comment by YouriTjang** [comment] 2021-02-05 20:53
I like [XKCD-script:](https://github.com/ipython/xkcd-font)
![image](https://user-images.githubusercontent.com/1197663/107087580-efa5ba00-67fb-11eb-8859-c7f06171744b.png)
Although the punctuations and symbols are more difficult to read.

And for the sake of comparison I'll add FG_Virgil here:
![image](https://user-images.githubusercontent.com/1197663/107087760-37c4dc80-67fc-11eb-8343-958fe611744f.png)

**Comment by xixixao** [comment] 2021-02-05 20:59
# Recursive

https://www.recursive.design/ https://github.com/arrowtype/recursive

License and character set support look good. Quite regular looking though

<img width="1239" alt="Screen Shot 2020-07-23 at 21 09 36" src="https://user-images.githubusercontent.com/1473433/88359873-20734580-cd29-11ea-84e1-73a3e1bc4054.png">
<img width="1015" alt="Screen Shot 2020-07-23 at 21 10 23" src="https://user-images.githubusercontent.com/1473433/88359878-236e3600-cd29-11ea-9398-8ea1da4953bf.png">

**Comment by dwelle** [comment] 2021-02-05 21:06
@YouriTjang the XKCD has pretty strict license (doesn't allow commercial use and doesn't look like it can be purchased for that purpose), so it's likely out. I amended the description to list this requirement.

**Comment by iamdyani** [comment] 2021-02-05 21:48
I found a few. Both free and allow commercial use from what I can tell!

### **[Fewriter](https://localfonts.eu/freefonts/handwritten-cyrillic-free-fonts/fewriter/)**
Really like this one but could be seen as a little messy due to the moving baseline if the current font is already seen as too hard to read.
![fewriter](https://user-images.githubusercontent.com/78622145/107091968-dd0d8f80-67bf-11eb-9ab9-7cfe1f573c73.jpg)

### **[Xarrovv](https://localfonts.eu/shop/latin-script/xarrovv/)**
Easier to read. Tidy yet handwritten! Lowercase Z is not what I am used to but not sure if it's uncommon to all or just me? Or is it no big deal and so could be a good choice?
![xarrovv](https://user-images.githubusercontent.com/78622145/107091969-dda62600-67bf-11eb-9900-0899715da0c1.jpg)

### **[Comic Relief](https://localfonts.eu/freefonts/traditional-cyrillic-free-fonts/comic-relief/)**
VERY easy to read. Too simple? Really nice though!
![comic relief](https://user-images.githubusercontent.com/78622145/107091966-dc74f900-67bf-11eb-826f-a4bd37f478ab.jpg)

**Comment by rkz** [comment] 2021-02-05 21:54
I'm personally in favor of a font that is narrower than FG_Virgil, and has no slant.

=> Among the above: Blokletters, Swagger, XKCD-Script

Also, from a new user perspective, I don't see the point for proposing two handwritten fonts. FG_Virgil could be smoothly transitioned out (e.g. only show it when opening a drawing that already uses it).

**Comment by daoleno** [comment] 2021-02-06 06:55
Chinese hand-drawn fonts under the [Open Font License](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL), but not compatible with Japanese and Korean fonts.
## [Zhi Mang Xing](https://fonts.google.com/specimen/Zhi+Mang+Xing?preview.text=%E6%88%91%E6%9C%89%E4%B8%80%E4%B8%AA%E6%A2%A6%E6%83%B3&preview.text_type=custom&subset=chinese-simplified#license)
<img width="1212" alt="截屏2021-02-06 下午2 52 05" src="https://user-images.githubusercontent.com/7393152/107111418-f7606f80-688a-11eb-8496-417673154ffa.png">
<img width="809" alt="截屏2021-02-06 下午2 51 47" src="https://user-images.githubusercontent.com/7393152/107111419-f9c2c980-688a-11eb-8d91-d5f6b65bec31.png">

**Comment by tell-y** [comment] 2021-02-07 04:56
### [RocknRoll One-Regular](https://github.com/fontworks-fonts/RocknRoll) 
For Japanese, I recommend it. #1615
[The font's license](https://github.com/fontworks-fonts/RocknRoll#licence) is SIL Open Font License. It also only cover Latin and Japanese. [cf.](https://github.com/fontworks-fonts/RocknRoll/blob/master/documentation/RocknRollOne.pdf)
![image](https://user-images.githubusercontent.com/6883692/107136900-b62f9480-694a-11eb-9638-2626992673f8.png)

**Comment by lipis** [comment] 2021-02-07 10:35
We need to have fall back fonts for other languages anyway.. regardless of the font we choose. Lazy loading or something.

**Comment by eddyg** [comment] 2021-02-07 14:08
I wanted to point out the excellent [Calligraphr](https://www.calligraphr.com/en/) tool. It lets you generate your own fonts, and the fonts you create can be distributed/licensed however you want. But the coolest thing is that it supports _character randomization_:

> Character randomization is quintessential to simulate true handwriting. It works by reproducing different variations of the same character that are naturally found in handwritten text. This means that you can specify different variants for each character and they will be used randomly during writing to give your font a more natural look.

To me, this is indeed the “quintessential” feature that Excalidraw needs.

It may be worth finding a style you like for inspiration, and then finding somebody with appropriate design skills to create a custom font with a bunch of random variants.

Barring a custom font, I think you should be looking for a handwriting font that _has_ randomized characters so it looks more “whiteboard” and less “typed”. Perhaps include a sample sentence with a lot of repeated letters, like:

```The bookkeeper saturated sensationally satirical storylines.```

in the comparisons to show how rendering the same character shape breaks the illusion of “hand drawn”.

**Comment by lipis** [comment] 2021-02-07 15:21
I like @eddyg's idea: but let's not spam this issue, so I created a discussion: https://github.com/excalidraw/excalidraw/discussions/2987

**Comment by shinkim0914** [comment] 2021-02-11 20:27
Here's a couple more. 

# [Caveat](https://fonts.google.com/specimen/Caveat?preview.text_type=custom)
* Open Font License
* Supports Cyrillic

![image](https://user-images.githubusercontent.com/29636145/107694183-f1d8a000-6c63-11eb-8e2f-b1b94b6e755c.png)

# [Verveine](https://fonts.adobe.com/fonts/verveine)
* Commercial license available (per app, per website pricing)
* Supports multiple languages

![image](https://user-images.githubusercontent.com/29636145/107694705-8b07b680-6c64-11eb-8b5a-a116aac53133.png)

**Comment by ReneCode** [comment] 2021-02-12 14:01
I vote for: **GelPen**. like the "sloppiness" in particular of the numbers

**Comment by polyrand** [comment] 2021-02-12 17:52
My favorites ones so far are Blokletters and GelPen (but I think I like GelPen a bit more). They remind me of the wizardzines by Julia Evans, which is great.

**Comment by eddyg** [comment] 2021-02-12 17:58
> They remind me of the wizardzines by Julia Evans, which is great.

Julia [has an article](https://jvns.ca/blog/2020/08/08/handwritten-font/) about how she made her font. (I also mentioned it in the discussion that was forked off.)

**Comment by lipis** [comment] 2021-02-14 10:58
**Fewriter** is nice!

**Comment by lipis** [comment] 2021-02-14 20:37
> They remind me of the wizardzines by Julia Evans, which is great.

https://twitter.com/b0rk/status/981159808832286720

Quite an interesting font.. anyone knows the name?

**Comment by tomayac** [comment] 2021-02-15 10:02
+1 to Fewriter for its coverage of Latin, Cyrillic. And Greek without losing its quirky style.

**Comment by dwelle** [comment] 2021-02-15 11:28
Fewriter isn't bad. It has some kerning issues with spaces around words, esp in all-caps (though most of the above fonts do):

![image](https://user-images.githubusercontent.com/5153846/107940837-2496d700-6f89-11eb-8e65-22fa4242bb88.png)

What worries me most is the license, which is mostly non-existent. There's a note it's free, but it doesn't have an actual license. So we don't even know whether we can modify etc.

**Comment by polyrand** [comment] 2021-02-15 12:17
> What worries me most is the license, which is mostly non-existent. There's a note it's free, but it doesn't have an actual license. So we don't even know whether we can modify, redistribute etc.

His DaFont profile has his email address: https://www.dafont.com/profile.php?user=926808

The "FeWriter" license in DaFont is `100% Free` which I think is the most permissive one.

He had a site at memesbruh03.co, but it's down and the wayback machine is not working for me now.

Regarding the fonts, I like **FeWriter** more, it's not as readable as **GelPen** but the aesthetics match better the Excalidraw shapes.

**Comment by db255** [comment] 2021-02-15 13:13
GelPen & Architects Daughter are equally cool. Digits are very readable, whilst in Virgil, the "2" and "9" can be confusing.

**Comment by lipis** [comment] 2021-02-15 13:52
> He had a site at memesbruh03.co, but it's down and the wayback machine is not working for me now.


It looks like it was designed by **Aaron D. Chand**.. can the Internet get in _touch_ with him?

**Comment by polyrand** [comment] 2021-02-15 15:09
@lipis 

**aaronchand84@gmail.com**

I wouldn't mind writing, but I think it's better done by someone from the Excalidraw org.

**Comment by dwelle** [comment] 2021-02-15 15:12
We'll handle it once we pick or narrow down the selection.

**Comment by apkoponen** [comment] 2021-02-15 19:08
I like Fewriter the most.

**Comment by ntkoopman** [comment] 2021-02-16 05:45
@vjeux could you share the recurring feedback? Without knowing what's causing the readability issues this will just be endless bikeshedding.

**Comment by geraintluff** [comment] 2021-02-17 00:12
I quite like GelPen, but being Latin-only seems like a problem.  Similar with Blokletters (although there are three font-weights for that, and I'd really like to see it one step heavier so that it's not outweighed by the drawn lines.)

Of the ones with wider language coverage, I find Xarrovv the friendliest, although it's a bit rigid and doesn't have the chaotic energy which I think is key to people feeling free (like their diagrams don't have to be "perfect" anymore).

I find Fewriter _almost_ good, but the lower-case "a" kind of unsettles me.

**Comment by maeddes** [comment] 2021-02-17 11:16
How does the voting work? Just drop a comment here? I like Fewriter a lot!

**Comment by ntkoopman** [comment] 2021-02-17 13:50
I think fewriter has some unfortunate kerning and baseline issues (also looks like some mixed cursive/printed cyrillic?)
![image](https://user-images.githubusercontent.com/1769749/108212260-a09b4580-7168-11eb-8820-1092ae9bedfd.png)
`језику су слични ¿Hola? niño era çiego Straße`

But maybe some of the authors would be ok with some changes if asked (I understand FG_Virgil was also patched already)

**Comment by geraintluff** [comment] 2021-02-18 00:38
I can see it might seem weird to be encouraging forks, but (inspired by this conversation) I have just started making a font of my own handwriting, explicitly so that I can use it in Excalidraw diagrams.

So I'd like to request that (whichever one is chosen) the font choice should be deliberately customisable for forks - for example, dropping a WOFF2 file in and changing a JSON config string.

Of course this customisation is already possible somehow, but I'd worry about future changes causing merge conflicts etc., so it would be cool to have some semi-official method which reduces that risk.

**Comment by lipis** [comment] 2021-02-18 12:37
The ideal would be to get some open source font (or get in touch with the creator and open source it).. and have that as official Excalifont :) Would the contributors add more languages (chinese, japanese, georgian, etc..)?

**Comment by 2WeltenChris** [comment] 2021-02-18 13:05
I tried the online demo and Architects Daughter is my favourite so far. Blokletters is way too thin, Caveat too tiny (and doesn't suit the look of Excalidraw), Comic Relief and Xarrovv are ok but don't look very hand written and Xarrovv is also a bit too thin, Fewriter is ok but also a bit thin, Gelpen is ok and Swagger is too thin and too narrow.

So Architects Daughter is it for me. :) Gelpen could be an option and maybe - but only maybe - Comic Relief.

**Comment by wietsevenema** [comment] 2021-02-18 16:03
I've been trying the fonts on one of my diagrams, this is what I think:

- **Architects Daughter**: is very wide for some characters, some are too small (try "library" and "API" to see what I mean). Too wide in general.
- **Blokletters**: I liked this one, but in practice it is too thin to be readable on top of a hachure (the striped fill). It's also a bit too 'neat'. 
- **Caveat**: Readability issues for me, due to the m, n, and the height difference in the line (try "Google Cloud")
- **Comic Relief**: Would probably accept this one if it was forced on me. Good line thickness. Also too tidy and neat, not scrappy enough. 
- **Fewriter**: No. 
- **GelPen**: Harder to read on hachure background. Some letters are too close together
- **Swagger**: Height inconsistencies in the lower case characters bother me (compare 'o' and 'g'). 
- **Xarrovv**: Lines too thin, acceptable otherwise. 

Another idea: can we improve Virgil? There are a few issues we can fix to make it better readable (well documented in the other issues). The most readable font from this list (Comic Relief) feels too tidy and too neat to me.

**Comment by anumithaapollo12** [comment] 2021-02-21 13:57
Hand-written fonts that go with the style of Excalidraw and should be legible. 
The font should be rustic and raw as are wireframes.

![image](https://user-images.githubusercontent.com/38392250/108627268-a18aea80-747a-11eb-9365-a4828716a548.png)

**Comment by inwardmovement** [comment] 2021-02-21 21:34
Like @wietsevenema said, can't we just collaborate with the author to improve the readability of Virgil? It's so cool...

**Comment by claracavalcante** [comment] 2021-02-25 07:06
I liked Fewriter the most.

**Comment by lipis** [comment] 2021-02-26 09:46
Many of you have expressed you'd like us to not abandon Virgil, but improve it. We are happy to announce we will aim to do just that. As of today, Virgil has a new home: https://github.com/excalidraw/virgil, licensed under Open Font License (OFL).

We're not closing the door to offering other fonts in the future, but for now we're sticking with Virgil ❤️. We have moved all the related issues to the new repository. If you have any other requests, ideas, or want to help improve the font yourself, please head over there!

This would be possible without the help of Ellinor Rapp (the creator of the font) and we thank her for that! 🙇‍♂️

**Closed by lipis** 2021-02-26 09:46 UTC
Labels: help wanted

**Comment by lipis** [comment] 2021-02-26 15:00
https://virgil.excalidraw.com

**Comment by ChestnutQiang** [comment] 2021-12-21 17:48
When can Chinese handwritten fonts be supported ?

**Comment by niksumeiko** [comment] 2023-12-27 10:03
This [Excalidraw custom font](https://chromewebstore.google.com/detail/afbeaojffbjckicjpkecknoocdpmgoah) Chrome extension does the job. Here's how to give it a try:

1. Open your drawing in excalidraw
2. Click on the extension icon
3. Paste `https://db.onlinewebfonts.com/t/0002fff34280c16a2cbc07d41f10d8af.woff`  
(this is a BLOCKLETTERS font from https://github.com/excalidraw/excalidraw/issues/2945#issuecomment-774244843)
4. Hit "Change font"
5. Toggle between the Light/Dark mode (applies the font)

![ScreenFlow](https://github.com/excalidraw/excalidraw/assets/175385/d80b8842-0e59-459b-a3ce-c914ef24b5da)
