### ISSUE TITLE
Ability to connect blocks together

### ISSUE THREAD

**Issue by Alex-Mann** [excalidraw/excalidraw#1655] opened 2020-05-26 14:22 UTC
This is a feature request, but it would be extremely awesome if you had a shortcut on the outside of each block where you could click and drag to connect it to another block.

After connecting to another block, it would then create an arrow or some sort of connector line. I know this is a lot of work, but it would seriously make excalidraw an even more awesome tool for things like brainstorming and mindmapping.

**Comment by lipis** [comment] 2020-05-26 14:27
Possibly duplicate of #157

**Comment by j-f1** [comment] 2020-06-14 20:52
Duplicate of #157

**Closed by j-f1** 2020-06-14 20:52 UTC
