### ISSUE TITLE
I hope to support Chinese handwritten fonts

### ISSUE THREAD

**Issue by wongchenv** [excalidraw/excalidraw#3510] opened 2021-04-27 03:48 UTC
At this stage, because Chinese does not adapt to handwritten fonts, I feel very uncomfortable

**Comment by zsviczian** [comment] 2021-04-30 04:40
I would recommend allowing the user to provide a link to a custom font and add that font as the 4th font, or as an override of one of the 3 fonts. That way not only Chinese fonts would be supported, but any font the user desires.

I have a bit of a conversation on the subject here in the Obsidian-Excalidraw plugin issue log: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/14

As a first step allowing an override of a font via the API would serve my use case well.

**Comment by BobDu** [comment] 2021-07-13 03:13
> I would recommend allowing the user to provide a link to a custom font and add that font as the 4th font, or as an override of one of the 3 fonts. That way not only Chinese fonts would be supported, but any font the user desires.
> 
> I have a bit of a conversation on the subject here in the Obsidian-Excalidraw plugin issue log: [zsviczian/obsidian-excalidraw-plugin#14](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/14)
> 
> As a first step allowing an override of a font via the API would serve my use case well.

It's a good idea. Can give user more choose.
But, now chinese handwritten fonts not a realy handwritten fonts.
So, can you change a default font when chinese handwritten?

**Comment by lancelotly** [comment] 2021-07-26 00:44
How about try to embed this one as the default Chinese font? https://github.com/jasonhandwriting/JasonHandwriting
JasonHandwriting is under the [SIL Open Font License](https://en.wikipedia.org/wiki/SIL_Open_Font_License)
@excalidraw

**Comment by zsviczian** [comment] 2021-07-26 05:10
@dwelle  This is a returning request I get… based on [this](https://blog.magicdu.cn/744.html) a solution seems pretty straight forward. It would be super nice if as part of props I could supply a link to a custom font (or base64 encoded data). This would provide a universal solution far beyond just Chinese font support. Saving and loading drawings between Excalidraw instances… if font 4 is not supplied, Excalidraw could default back to normal font family.

**Comment by ChestnutQiang** [comment] 2021-12-21 17:48
When can Chinese handwritten fonts be supported ?

**Comment by zsviczian** [comment] 2021-12-21 17:57
@ChestnutQiang, in Obsidian, with the Markdown Embeds you can use Chinese handwritten fonts in Excalidraw. I recognize this is not perfect, but at least it is a way...

https://youtu.be/tsecSfnTMow

**Comment by hulkbig** [comment] 2024-03-19 16:12
@wongchenv hi, you can try my fork version: [https://excalidraw-zh.com/](https://excalidraw-zh.com/)

**Comment by DawidWraga** [comment] 2024-06-06 18:47
Incase anyone is wondering, I spent a while figuring this out but I've found a solution.

I've written an article on how to use custom fonts on excalidraw [here](https://dev.to/dawidcodes/how-to-use-a-custom-font-on-excalidrawcom-4jl4)

**Comment by Mrazator** [comment] 2024-10-16 20:00
We will be releasing support for the whole CJK soonish! (https://github.com/excalidraw/excalidraw/pull/8530)

Feel free to give us early feedback, preview is available here:
https://excalidraw-git-mrazator-first-class-support-chinese-excalidraw.vercel.app/

Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/8408

**Closed by Mrazator** 2024-10-16 20:00 UTC
Labels: font
