### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by EswaraSatya** [excalidraw/excalidraw#7076] opened 2023-10-03 13:03 UTC
When trying to download when frame is available on excalidraw canvas frame is not displayed on the downloaded png/svg/image

![image](https://github.com/excalidraw/excalidraw/assets/101344518/dc3e9aa4-5028-463c-b0e0-dd1d19b4f544)

![image](https://github.com/excalidraw/excalidraw/assets/101344518/c6baa78b-b955-406d-b608-380ac3158bd0)

**Comment by Satya2234** [comment] 2023-10-06 19:42
I would like to work on it

**Comment by dwelle** [comment] 2023-10-06 20:10
By design, but we are indeed considering rendering frames on export (when not exporting a single frame).

Adding discussion label to make a final decision.

**Comment by dwelle** [comment] 2023-11-10 14:48
fixed via https://github.com/excalidraw/excalidraw/pull/7210

**Closed by dwelle** 2023-11-10 14:48 UTC
Labels: discussion
