### ISSUE TITLE
Undeletable content/session

### ISSUE THREAD

**Issue by dasblitz** [excalidraw/excalidraw#1073] opened 2020-03-24 15:39 UTC
Background:

So last week we used excalidraw to draw a board with goodbye messages for a collegue who had her last day, since we're all forced to work from home because of corona :( We kind of pushed it to the limits with over 20 participants, it was very unresponsive but in the end it was a nice goodbye gift :)
This week we have another collegue leaving and we wanted to do the same again. 

The problem:

I opened excalidraw.com. The content from last week was still there somehow. I went and clicked the clear canvas button. The canvas was now empty. I created a share link and shared it with a collegue. As soon as my collegue joined the session all of the content of last week shows up again, on both our screens.

I've tried deleting my bowser history/sessions etc. But the content keeps coming back when I close and open excalidraw.com.

Expected behaviour:
Always see an empty canvas when I open excalidraw.com without a room hash

**Comment by lipis** [comment] 2020-03-24 15:40
Duplicate of #1072

**Closed by lipis** 2020-03-24 15:40 UTC
