### ISSUE TITLE
Add option to change number of heads to arrow

### ISSUE THREAD

**Issue by xbcratos** [excalidraw/excalidraw#2366] opened 2020-11-09 12:10 UTC
First of all, this is an amazing product, congratulations!

Now here the enhancement I would do. I've found that using the arrow option I just have one type of arrow with one head but I think it would be very useful to add an option to change from one head to two heads the arrow. See image below:

![image](https://user-images.githubusercontent.com/39724033/98539351-75ad7580-228c-11eb-8110-736e289baa1c.png)

**Comment by dwelle** [comment] 2020-11-09 12:37
Thanks. This is a duplicate of https://github.com/excalidraw/excalidraw/issues/616

**Closed by dwelle** 2020-11-09 12:37 UTC
Labels: duplicate
