### ISSUE TITLE
Circle top incorrect

### ISSUE THREAD

**Issue by lidedongsn** [excalidraw/excalidraw#1407] opened 2020-04-13 02:48 UTC
![image](https://user-images.githubusercontent.com/6139634/79088137-47a69800-7d74-11ea-97de-bfa1f7e5685f.png)

**Comment by vjeux** [comment] 2020-04-13 03:15
This is intentional. This mimics how when you draw a circle by hand you don’t quite meet the end exactly right.

cc @pshihn who can tell you more about the effect

**Comment by pshihn** [comment] 2020-04-13 03:52
@lidedongsn Take a piece of paper and try drawing a many circles as quickly as you can in one continuous motion. Here's what it looks like when I did that:
![IMG_3364](https://user-images.githubusercontent.com/833927/79090453-a3363e80-7cfe-11ea-872d-7b867a139a44.jpg)

Notice that that the start and end point of the loop don't actually meet unless you are very careful. Trying to replicate the effects in roughjs. See these 4 circles:

![Screen Shot 2020-04-12 at 8 42 53 PM](https://user-images.githubusercontent.com/833927/79090507-c7921b00-7cfe-11ea-8c20-8bf767d41466.png)
 
This discontinuity of ends not meeting is represented in the shapes. Because of randomness, it seems more pronounced in your shape.

The circle is essentially drawn like this - by estimating points around the circle and not intentionally meeting them accurately:

![Screen Shot 2020-04-12 at 8 50 45 PM](https://user-images.githubusercontent.com/833927/79090711-6e76b700-7cff-11ea-874f-94a6946e9ced.png)

**Comment by pshihn** [comment] 2020-04-13 03:58
I think the corner case for excalidraw is 'architect' mode. Perhaps I should remove this behavior completely if `roughness === 0`.

**Comment by jwoLondon** [comment] 2020-04-13 08:12
For anyone interested, here is the [original paper](https://openaccess.city.ac.uk/id/eprint/1274/) that described the technique:

**Comment by lipis** [comment] 2020-04-13 13:12
Closing this is, as it's by design!

**Closed by lipis** 2020-04-13 13:12 UTC
