### ISSUE TITLE
fonts broken?

### ISSUE THREAD

**Issue by crashedpixel** [excalidraw/excalidraw#4313] opened 2021-11-24 14:46 UTC
anyone else having issues with fonts not loading. not seeing any console errors. something change in the latest release?

**Comment by crashedpixel** [comment] 2021-11-24 14:57
specifically virgil font not seeing it load

**Comment by dwelle** [comment] 2021-11-24 15:35
I cannot reproduce. Are we talking about https://excalidraw.com? What's your browser and OS?

> a lot of breaking changes recently

Can you point out specific cases so we can fix them?

**Comment by crashedpixel** [comment] 2021-11-24 15:42
nothing out of the norm. i work on mac os, chrome, and i don't run this locally with nodejs. i'm using the npm package. so far i'm looking into the webpack config change to do with fonts.

**Comment by dwelle** [comment] 2021-11-24 15:55
Yes, the font file needs to be in `excalidraw-assets/` — in other words, upon install you need to copy the `excalidraw-assets/` folder from the `node_modules/@excalidraw/excalidraw` over to your static folder. It's not an ideal workflow, I admit.

> the font file points to the asset folder in the woff2. not sure if this is normal? i replaced this with the actual font and it worked.

Does that mean the `Virgil.woff2` was already present or not?

**Comment by crashedpixel** [comment] 2021-11-24 17:35
i already copied the folder over. here is the structure:
```
public-folder
                      excalidraw-assets-dev
```

**Comment by crashedpixel** [comment] 2021-11-24 17:39
I had that before with no problem. I noticed the structure changed slightly. The fonts had this weird reference files outside the excalidraw-assets folder.

```
public_folder
                      excalidraw-assets-dev
                      excalidraw-assets
                      hash.woff2 <-- (contains virgil ref)
                      hash.woff2 <-- (contains cascadia ref)
```

Example of what I saw in he reference file `hash.woff2` for virgil.
```export default __webpack_public_path__ + "excalidraw-assets-dev/Virgil.woff2";```

This is why I think it might be the webpack change. How I worked around this issue was replace the reference file contents with the actual font. That was in `public_folder/excalidraw-assets/Virgil.woff2`. Did that make sense?

**Comment by sanketkheni01** [comment] 2021-12-07 07:30
I am facing the same issue.. 
check this out `https://codesandbox.io/s/excalidraw-forked-hu5xh`

**Comment by ad1992** [comment] 2021-12-07 08:01
> I am facing the same issue. try to add some text... check this out [Code sandbox](https://codesandbox.io/s/excalidraw-forked-hu5xh)

Looks like you might not have updated the `excalidraw-assets` folder, it works fine in the [demo](https://ehlz3.csb.app/), Also if you don't want to use `excalidraw-assets` you can simply remove setting `   window.EXCALIDRAW_ASSET_PATH = "/";
` from `public/index.html`

**Comment by sanketkheni01** [comment] 2021-12-07 08:08
please check this link:- [demo](https://hu5xh.csb.app/) and use the latest version of @excalidraw/excalidraw-next (0.10.0-9b8ee3c) in [codeSandbox](https://codesandbox.io/s/excalidraw-forked-hu5xh).
![image](https://user-images.githubusercontent.com/68942390/144990368-6c1e0e68-05f5-46a9-97eb-e16802a18e72.png)

**Comment by ad1992** [comment] 2021-12-08 05:30
There seems to be an issue with bundling, looking into it

**Comment by ad1992** [comment] 2021-12-08 10:27
This is fixed now, please use the latest version of [`@excalidraw/excalidraw-next`](https://npmjs.com/@excalidraw/excalidraw-next)

**Closed** 2021-12-08 10:26 UTC
Labels: bug
