### ISSUE TITLE
[Feature] Cut ability

### ISSUE THREAD

**Issue by AdamLinCodes** [excalidraw/excalidraw#7975] opened 2024-05-02 04:43 UTC
Similar to onenote's cut commands, adding the ability to cut dynamic sections of sketches and move them rather than strict rectangular sections would be very useful.

**Comment by Mrazator** [comment] 2024-05-07 17:51
Duplicate of #7900

**Closed by Mrazator** 2024-05-07 17:51 UTC

**Comment by AdamLinCodes** [comment] 2024-05-07 18:21
Apologies for the duplicate issues @Mrazator

**Comment by Mrazator** [comment] 2024-05-07 18:45
No worries!
