### ISSUE TITLE
request: pan/drag tool

### ISSUE THREAD

**Issue by korilin** [excalidraw/excalidraw#4153] opened 2021-10-31 10:06 UTC
不知道是否能增加一个用鼠标拖动试图的功能呢，目前我移动视图采用缩放的方式去让我想看的元素处于视图中间，这样感觉挺麻烦

----

translation: I don’t know if I can add a function of dragging with the mouse. At present, I move the view by zooming to make the element I want to see in the middle of the view, which feels very troublesome.

**Comment by dwelle** [comment] 2021-11-01 09:50
On the roadmap (duplicate of https://github.com/excalidraw/excalidraw/issues/794). In the meantime, you can use mouse middle button, or drag while holding space.

Refer to the help:

![image](https://user-images.githubusercontent.com/5153846/139653672-a9437595-7cfd-413a-a174-3b83bc3d0b9b.png)

**Closed by dwelle** 2021-11-01 09:50 UTC
