### ISSUE TITLE
Text & Shape binded -> text is not displayed correctly

### ISSUE THREAD

**Issue by Gomilu** [excalidraw/excalidraw#6010] opened 2022-12-18 11:37 UTC
Text is not displayed correctly when bond to a shape (this is after an update ~ roughly 1-5 months ago)

When scaling to a smaller sizer it is displayed correctly

Steps:

1. create text
2. Put shape on top (e.g., square)
3. group together
4. Bind text & shape together
6. scale big 

Small Scale & correct

![Screenshot from 2022-12-18 12-33-43](https://user-images.githubusercontent.com/111446934/208296093-9b6f08cc-c07c-4a56-aa47-bd5e7fa650db.png)

Big Scale & incorrect

![Screenshot from 2022-12-18 12-34-54](https://user-images.githubusercontent.com/111446934/208296124-8efa7ed9-dfa1-4eaa-9162-805d38498752.png)

![Screenshot from 2022-12-18 12-31-25](https://user-images.githubusercontent.com/111446934/208296143-07428d8c-9efb-46a4-8445-c2f0e685ecea.png)

**Comment by dwelle** [comment] 2022-12-18 11:40
Hi. Can you write steps to reproduce, or create a shareable link for it?

**Comment by Gomilu** [comment] 2022-12-18 19:39
updated first comment for steps

**Comment by dwelle** [comment] 2022-12-18 22:11
Unclear what steps (1) and (2) mean. Do you create a text, a group them together (cmd/ctrl-G) and then in step 2, right-click and bind text to the container?

Also:

> Text is not displayed correctly when bond to a shape (this is after an update ~ roughly 1-5 months ago)

Does that mean existing diagrams are being broken when loaded in the new version?

**Comment by Gomilu** [comment] 2022-12-19 07:52
Steps:
Updated initial comment for steps: but, yes thats how I do it

> Does that mean existing diagrams are being broken when loaded in the new 

Yes, the existing one's are all broken

**Comment by Gomilu** [comment] 2022-12-19 10:40
Hi :)
a) doing it on excalidraw.com - there is a different way to get to the same issue
https://excalidraw.com/#room=688587d4cb9b352d2d53,FATI0w_084DIKHsdw1DkZA
steps
1) text
2) shape
3) group
4) bind
5) scale big
6) double click to adjust shape -> narrow it (width-wise)
-> issue should occur

b) doing it within obsidian (linux) 
-> I do not know how to share it from obsidian/linux environment

Side note: 
for a) if you scale it bigger it creates a lot of space at the bottom
https://excalidraw.com/#room=688587d4cb9b352d2d53,FATI0w_084DIKHsdw1DkZA

**Comment by ad1992** [comment] 2022-12-19 11:16
Thanks for the link @Gomilu!
I can see the issue in your link, however, I am still not able to reproduce it in my drawings. I am using MAC, you are using Linux right ?

Also, can you confirm if you are still able to reproduce the issue in https://excalidraw-77vel9y2u-excalidraw.vercel.app/ ?
For me If I copy your drawing in the above link and double click to select text it gets fixed, however in prod it doesn't.

**Comment by Gomilu** [comment] 2022-12-19 11:34
Yes, using Linux.



> can you confirm if you are still able to reproduce the issue in https://excalidraw-77vel9y2u-excalidraw.vercel.app/

I am unable to copy/cut,

**Comment by ad1992** [comment] 2022-12-19 11:39
> Yes, using Linux.
> 
> > can you confirm if you are still able to reproduce the issue in https://excalidraw-77vel9y2u-excalidraw.vercel.app/
> 
> I am unable to reproduce it there. Maybe due to sticky scaling and me unable to copy/cut I can't do the steps mentioned above

@Gomilu do you mean the issue is fixed in the above link ? Could you try the same steps you mentioned in the issue description(if you haven't tried yet)  and confirm if the issue occurs in the above link ?

**Comment by Gomilu** [comment] 2022-12-19 12:40
Thank you for your time & effort!

I am unable to reproduce it according to the original steps (initial comment)

However, I would like to try doing it according to the 'second' version of the steps,but I cannot due to sticky-scaling (i can't do step 6)

> 
    1. text
    2 shape
   3 group
  4   bind
  5   scale big
   6 double click to adjust shape -> narrow it (width-wise)

**Comment by ad1992** [comment] 2022-12-19 12:55
> Thank you for your time & effort!
> 
> I am unable to reproduce it according to the original steps (initial comment)

Awesome, that's great to hear!

> 
> However, I would like to try doing it according to the 'second' version of the steps,but I cannot due to sticky-scaling (i can't do step 6)
> 
> > 
> 
> ```
> 1. text
> 2 shape
> ```
> 
> 3 group 4 bind 5 scale big 6 double click to adjust shape -> narrow it (width-wise)

Do you mean you are not able to double click since it so much zoomed in ? This would have not been possible in production as well unless you zoom out right ?

**Comment by Gomilu** [comment] 2022-12-19 13:51
> Do you mean you are not able to double click since it so much zoomed in ? This would have not been possible in production as well unless you zoom out right ?

I am unable to double click due to 'sticky scaling' i.e., when scaling a grouped text+shape, then binding it, the scaling cannot be released (that is i think another bug)

**Comment by dwelle** [comment] 2022-12-19 14:36
> I am unable to double click due to 'sticky scaling' i.e., when scaling a grouped text+shape, then binding it, the scaling cannot be released (that is i think another bug)

That bug was solved yesterday https://github.com/excalidraw/excalidraw/issues/6009. Can you check if you're on latest version on excalidraw.com by opening the "stats for nerds" (righ-click on canvas)? It should show "2022-12-18T22:06:01Z-539505" (or newer) for the version.

![image](https://user-images.githubusercontent.com/5153846/208449878-52e31e11-845e-4343-a635-ec01128365a3.png)

**Closed** 2022-12-21 07:02 UTC
Labels: Binding text / Sticky note

**Comment by Gomilu** [comment] 2023-01-29 10:55
Thank you very much! 

Good-Intent



Dec 19, 2022, 14:36 by ***@***.***:

**Comment by Gomilu** [comment] 2023-01-29 12:17
Thank you!

Good-Intent



Dec 21, 2022, 07:03 by ***@***.***:
