### ISSUE TITLE
Firefox mobile doesn't support `context.getTransform`

### ISSUE THREAD

**Issue by EmrysMyrddin** [excalidraw/excalidraw#798] opened 2020-02-21 23:11 UTC
The issue is reproductible on firefox mobile v68.3

### Stack trace

```
be@https://excalidraw.com/static/js/main.a1fcd27b.chunk.js:1:48184
value@https://excalidraw.com/static/js/main.a1fcd27b.chunk.js:1:138117
bu@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:160321
t.unstable_runWithPriority@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:179832
$a@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:104594
gu@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:156574
iu@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:146901
Ka/<@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:104885
t.unstable_runWithPriority@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:179832
$a@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:104594
Ka@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:104830
Qa@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:104765
eu@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:143488
enqueueSetState@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:109589
k.prototype.setState@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:54130
t/n.syncActionResult@https://excalidraw.com/static/js/main.a1fcd27b.chunk.js:1:116851
e/<@https://excalidraw.com/static/js/main.a1fcd27b.chunk.js:1:123287
u@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:47414
l/i._invoke</<@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:47167
y/</e[t]@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:47771
r@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:2207
l@https://excalidraw.com/static/js/2.75b44755.chunk.js:2:2410
```

### localStorage

```
{"i18nextLng":"en"}
```

**Comment by j-f1** [comment] 2020-02-22 22:17
Can you reproduce this again and send an updated stack trace? We’ve recently added some tools that should make it easier for us to fix the issue.

**Comment by EmrysMyrddin** [comment] 2020-02-22 22:29
Here is the new stack trace:
```
m.getTransform is not a function:

getTransform (renderer/renderScene.ts:47:42)
componentDidUpdate (index.tsx:2296:37)
p.focus&&p.focus();for (../node_modules/react-dom/cjs/react-dom.production.min.js:251:462)
unstable_runWithPriority (../node_modules/scheduler/cjs/scheduler.production.min.js:18:436)
dg (../node_modules/react-dom/cjs/react-dom.production.min.js:120:324)
Xj (../node_modules/react-dom/cjs/react-dom.production.min.js:244:436)
Lj (../node_modules/react-dom/cjs/react-dom.production.min.js:223:419)
ig (../node_modules/react-dom/cjs/react-dom.production.min.js:121:114)
unstable_runWithPriority (../node_modules/scheduler/cjs/scheduler.production.min.js:18:436)
dg (../node_modules/react-dom/cjs/react-dom.production.min.js:120:324)
ig (../node_modules/react-dom/cjs/react-dom.production.min.js:121:60)
dg (../node_modules/react-dom/cjs/react-dom.production.min.js:120:495)
Rg (../node_modules/react-dom/cjs/react-dom.production.min.js:214:155)
isMounted (../node_modules/react-dom/cjs/react-dom.production.min.js:133:236)
setState (../node_modules/react/cjs/react.production.min.js:13:230)
syncActionResult (index.tsx:704:11)
json=([0-9]+), (index.tsx:774:13)
tryCatch (../node_modules/regenerator-runtime/runtime.js:45:39)
context.dispatchException (../node_modules/regenerator-runtime/runtime.js:271:21)
function (../node_modules/regenerator-runtime/runtime.js:97:20)
asyncGeneratorStep (../node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:24)
_next (../node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:8)```

**Comment by dwelle** [comment] 2020-02-22 22:36
Huh... https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getTransform

![image](https://user-images.githubusercontent.com/5153846/75100301-18717700-55cc-11ea-8d4f-9abbc6e6d06c.png)

/cc @enzoferey

**Comment by enzoferey** [comment] 2020-02-23 07:39
Whoops, sorry ! 😅 I didn't know we plan to support exotic navigators (0.35% usage on [mobile stats](https://gs.statcounter.com/browser-market-share/mobile/worldwide). Btw, `setTransform` has same browser support and it's also an issue.

I unfortunately don't have time to spend on Excalidraw in the next few weeks, but I believe it should be fixable by moving to `context.scale()` + `context.translate` if we are careful about one not affecting the other. Another option, is to use `context.transform(myTransform)`, which is supported by all browsers, but it's context dependant (doesn't reset but instead multiplies matrices).

To give you more context (🥁), the reason why I used `getTransform` and `setTransform` is because is the only way to pick up and set current transform in an associate context-less way. I'm not aware of any other of managing current transform that way.

**Comment by dwelle** [comment] 2020-02-23 11:08
Or maybe let's just disable zooming on browsers that don't support the API for now? Although, looking at the code, this would still need hacks in several places.

Btw, this also applies to non-chromium Edge (which seems to be the majority version out there, still).

**Comment by vjeux** [comment] 2020-03-15 19:25
Duplicate of #861

**Closed by vjeux** 2020-03-15 19:25 UTC
Labels: bug, firefox, mobile
