### ISSUE TITLE
Duplicate selection 

### ISSUE THREAD

**Issue by benadam11** [excalidraw/excalidraw#196] opened 2020-01-06 05:01 UTC
It would be a great feature to duplicate shape (Figma or Sketch have a keybinding - option + drag to duplicate a selection).

**Comment by vjeux** [comment] 2020-01-06 05:13
Great idea! It's a duplicate of https://github.com/excalidraw/excalidraw/issues/165

**Closed by vjeux** 2020-01-06 05:13 UTC
