### ISSUE TITLE
Copy & Paste not working on Chrome 75 for OSX

### ISSUE THREAD

**Issue by andrewmclagan** [excalidraw/excalidraw#382] opened 2020-01-16 02:48 UTC
Copy paste is not working for me on OSX Chrome.

Chrome Version 79.0.3945.117 (Official Build) (64-bit)

OSX 10.14.6 Mojave

Works fine on same system with FireFox

**Comment by kentaromiura** [comment] 2020-01-16 06:30
Fiy: I've reproduced and fixed this locally by feature testing `clipboardData.writeText` I might send a pr later if it's not already fixed.

**Comment by giovannigiordano** [comment] 2020-01-16 08:15
@kentaromiura PRs are accepted for this!

**Comment by dwelle** [comment] 2020-01-16 10:22
> @kentaromiura  Fiy: I've reproduced and fixed this locally by feature testing clipboardData.writeText I might send a pr later if it's not already fixed.

What will feature testing solve in this instance?

**Comment by kentaromiura** [comment] 2020-01-16 12:28
Also since the version of TypeScript used doesn't currently support `writeText`, you need to forceCast like this:

```ts
type ClipboardWithPermission = {
  writeText: (text: string) => Promise<any>;
};
function forceCast<T>(x: unknown) {
  return x as T;
}

// ...
const maybeDataWithPermission = forceCast<ClipboardWithPermission>(
   e.clipboardData
);
const value = JSON.stringify(
   elements
      .filter(element => element.isSelected)
      .map(({ shape, ...el }) => el)
);
if (maybeDataWithPermission.writeText) {
   maybeDataWithPermission.writeText(value);
} else {
   e.clipboardData.setData("text/plain", value);
}
```
which is super ugly :)

**Comment by lipis** [comment] 2020-02-29 14:02
Is that still an issue?

**Comment by dwelle** [comment] 2020-02-29 15:10
Let's close this. If you still experience any issues, comment here or open a new issue please.

**Closed by dwelle** 2020-02-29 15:10 UTC
Labels: bug
