### ISSUE TITLE
Feature Request: Group objects together

### ISSUE THREAD

**Issue by rajeshpillai** [excalidraw/excalidraw#1534] opened 2020-05-03 03:24 UTC
First of all thank you for this wonderful product.

Everything is great and simple.  

As the drawing gets bigger, with lots of rectangles or circles with associated text object , moving elements, that are logically connected, for eg  rectangle with text becomes difficult and alignment may get changed because the objects are independent.

I think a group objects feature could be quite useful here.

For e.g. I can select a rectangle and the associated text and select group to make them one object.  This will make the tool experience even better.

Similarly there could be an ungroup feature.

Please feel to ignore if this request is way out of scope for excalidraw.

Thank You.
Rajesh Pillai

**Comment by dwelle** [comment] 2020-05-03 08:25
Hello. Thanks for the issue, it's definitely not out of scope, we just never got to implement this properly. I'm gonna close this as a duplicate of https://github.com/excalidraw/excalidraw/issues/173

**Closed by dwelle** 2020-05-03 08:25 UTC
