### ISSUE TITLE
[BUG]Can't save to file to local by Chrome

### ISSUE THREAD

**Issue by beagle4ce** [excalidraw/excalidraw#5811] opened 2022-11-01 14:36 UTC
## Environment:

    Chrome Version 107.0.5304.87 (Official Build) (x86_64)

    Macbook pro 2019 Intel, MacOS 12.6.1

    Adblock plus was disabled

## DevTools Console:

```
DOMException: The request is not allowed by the user agent or the platform in the current context.
```

<img width="821" alt="image" src="https://user-images.githubusercontent.com/4271372/199259085-a986ed8a-b803-4e93-a151-25368f656595.png">

<img width="923" alt="image" src="https://user-images.githubusercontent.com/4271372/199259200-865c5e8c-9244-4e29-9329-050c48bb49f0.png">

**Comment by dwelle** [comment] 2022-11-02 09:38
Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/5773

(this particular case was caused by disabled `file editing` permissions on a browser level)

**Closed by dwelle** 2022-11-02 09:38 UTC
