### ISSUE TITLE
Feature Request: Insert Images

### ISSUE THREAD

**Issue by garyelephant** [excalidraw/excalidraw#1535] opened 2020-05-03 08:44 UTC
It would be good , if excalidraw can insert images, so we can make hand-draw on existing images.
For now I have abandoned other drawing tools except for excalidraw.

**Comment by dwelle** [comment] 2020-05-03 09:02
duplicate of https://github.com/excalidraw/excalidraw/issues/19

**Closed by dwelle** 2020-05-03 09:02 UTC
