### ISSUE TITLE
SaveAs or Save results in empty file when using Opera Browser

### ISSUE THREAD

**Issue by bstavenuiter** [excalidraw/excalidraw#2419] opened 2020-11-26 14:26 UTC
**How to reproduce**
- Open new draw using the opera browser.
- Draw some retangles
- Press "save" and store .excalidraw to desktop
- File on desktop now as 0 bytes

**What happens**
- I get an empty .excalidraw file

**What I expected to happen**
- File on desktop with the  contents, containing information about the drawing.

**Also, but don't know if has anything todo with it**
- Getting JS errors
`DOMException: The request is not allowed by the user agent or the platform in the current context.`

![image](https://user-images.githubusercontent.com/2330333/100362421-b0890a80-2ffb-11eb-8cbb-419ed752a9ef.png)

**Comment by dwelle** [comment] 2020-11-26 14:37
Duplicate of https://github.com/excalidraw/excalidraw/issues/2312 — it's caused by Opera itself and how she handles security around the FS API.

We're spread pretty thin right now and can't debug every browser on the market. I suggest you open an issue on their [forum](https://forums.opera.com/category/5/opera-for-computers), linking to this issue.

**Comment by bstavenuiter** [comment] 2020-11-27 12:28
Ah right, couldn't find that issue. Well, maybe others can find it now, using Chrome for now.

Guess this one can be closed as well then

**Closed** 2020-11-27 13:06 UTC
Labels: duplicate
