### ISSUE TITLE
Unable to change the text on an object from the library

### ISSUE THREAD

**Issue by alexeyzimarev** [excalidraw/excalidraw#4840] opened 2022-02-23 13:51 UTC
Steps to reproduce:
- Add the "Sticky notes" library
- Place one stickie on the canvas
- Select the text tool, write some text over the stickie
- Try to change the text afterwards, but it doesn't seem to be possible

It's a nice feature that the text gets "locked" on an object, so they move together (I had to group them manually before), but without being able to change the text afterwards it's close to being unusable.

**Comment by alexeyzimarev** [comment] 2022-04-13 14:22
As a Plus customer, may I get some attention to this issue? It's quite an annoying one.

**Comment by dwelle** [comment] 2022-04-13 16:17
hey @alexeyzimarev. Sorry about that, we're getting a lot of issues on this repository, so some issues may get lost. For general help, you can always use one of our discord servers or our support email: 

![image](https://user-images.githubusercontent.com/5153846/163224906-47a2e9be-87aa-45c8-b171-f98c4ddabb83.png)

Onto your question: I couldn't reproduce the problem.

In fact, I'm not even sure what you're describing is technically possible right now. If you're referring to this library: https://libraries.excalidraw.com/#ferminrp-post-it then those items are composed of line elements, which don't allow for binding text to them. So adding text using the text tool should just place the text over them, and it won't wrap nor be locked to the sticky note.

Could you maybe record a video, or explain in more detail what's happening?

If you're ok with not having the exact look of a sticky note, then I'd suggest to simply create a rectangle with a background color and adding text to it directly. It will be both bound to it, and the text will autowrap:

![excal-sticky](https://user-images.githubusercontent.com/5153846/163224369-58b823ba-40dc-4c6f-bde7-46c49a8af338.gif)

**Comment by alexeyzimarev** [comment] 2022-04-14 10:35
The issue title is about shapes added from the shape library, not the basic shapes. I have it working for the new shapes (sticky notes), but for some older diagrams it doesn't work.

Here is the recording, I continuously try clicking on the text, and it never lets me edit the text.
![Screen Recording 2022-04-14 at 11 24 51](https://user-images.githubusercontent.com/2821205/163371259-4147a199-de32-42e0-ae9e-f77d94300e53.gif)

**Comment by dwelle** [comment] 2022-04-14 15:46
Interesting. Can you export the file into `.excalidraw` so I can take a look? Alternatively, just select the sticky note (including the text) and copy/paste it here (it'll give you a JSON text).

**Comment by alexeyzimarev** [comment] 2022-04-15 14:52
Here's the sticky note:

```json
{"type":"excalidraw/clipboard","elements":[{"type":"line","version":2626,"versionNonce":164051439,"isDeleted":false,"id":"p81KSxAlcCmi_9j_XmDWk","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":1624.12679031863,"y":6826.792189418495,"strokeColor":"#000000","backgroundColor":"#fd7e14","width":211.3916830346147,"height":208.62509381925972,"seed":1789669135,"groupIds":["3eiLCCkwkDs5UDwaMENxN","_Dq4-szz0HtOg43igEcGS"],"strokeSharpness":"sharp","boundElements":[{"id":"2P7XyWGe1GegX-pavAwcI","type":"text"},{"type":"text","id":"2P7XyWGe1GegX-pavAwcI"}],"updated":1649859670257,"link":null,"locked":false,"startBinding":null,"endBinding":null,"lastCommittedPoint":null,"startArrowhead":null,"endArrowhead":null,"points":[[0,0],[207.61683155185338,0.7294583699974784],[211.3916830346147,174.34055042938112],[176.6630493932135,207.1661770792649],[2.264910889656603,208.62509381925972],[0,0]]},{"type":"line","version":837,"versionNonce":1154801793,"isDeleted":false,"id":"JMRHr03Hk-5jl1FEV3fJb","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":1835.1882689059635,"y":7001.853252408127,"strokeColor":"#343a40","backgroundColor":"white","width":36.11111111111131,"height":38.333333333333485,"seed":146623841,"groupIds":["_Dq4-szz0HtOg43igEcGS"],"strokeSharpness":"sharp","boundElements":[],"updated":1649859670257,"link":null,"locked":false,"startBinding":null,"endBinding":null,"lastCommittedPoint":null,"startArrowhead":null,"endArrowhead":null,"points":[[0,0],[-33.88888888888869,-5.000000000000455],[-36.11111111111131,33.33333333333303],[0,0]]},{"type":"text","version":83,"versionNonce":1204298767,"isDeleted":false,"id":"2P7XyWGe1GegX-pavAwcI","fillStyle":"solid","strokeWidth":2,"strokeStyle":"solid","roughness":2,"opacity":100,"angle":0,"x":1629.12679031863,"y":6908.604736328125,"strokeColor":"#000000","backgroundColor":"#12b886","width":201,"height":45,"seed":1720808751,"groupIds":["3eiLCCkwkDs5UDwaMENxN","_Dq4-szz0HtOg43igEcGS"],"strokeSharpness":"sharp","boundElements":[],"updated":1649859670257,"link":null,"locked":false,"fontSize":36,"fontFamily":1,"text":"103","baseline":32,"textAlign":"center","verticalAlign":"middle","containerId":"p81KSxAlcCmi_9j_XmDWk","originalText":"103"}],"files":{}}
```

**Comment by alexeyzimarev** [comment] 2022-04-15 14:53
Here's the board, it's not private https://app.excalidraw.com/l/9IsNQZkLEQM/BBP9fWRWWS

**Comment by dwelle** [comment] 2022-04-15 15:10
Thanks. Ok, it seems the text is indeed bound to the sticky note, even though that's not officially supported. There was a bug where under special circumstances it could have happened, and it was fixed only _after_ you've reported the issue (https://github.com/excalidraw/excalidraw/pull/4655), so that's most likely how you ended up with it.

It should still be possible to edit the text by clicking on it with the text tool — at least it works for me. You can then either delete all the text and confirm to remove the text element, or you can take advantage of this bug which will at least autowrap the text to the sticky note :).

Alternative is to use workflow I suggested in https://github.com/excalidraw/excalidraw/issues/4840#issuecomment-1098243101, which is to create regular rectangles.

We might support binding to line(ar) shapes in the future, after we figure out how it should behave around double-clicking/enter, which as you've noticed right now it edits the sticky note line shape instead of editing the text.

Closing as there's nothing actionable — except maybe trying to recover from this bug on reload by fixing the bindings. But this seems enough of an edge case that it's probably better to leave it (and maybe now that you know you can edit it using the text tool, you may prefer the buggy behavior!).

**Closed by dwelle** 2022-04-15 15:10 UTC
