### ISSUE TITLE
Frame clipping is not honored in export

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#6807] opened 2023-07-25 21:01 UTC
It would be good to align frame clipping in export with frame clipping in appState.
It would also be good to add frame clipping and the other appState.frameRendering states (enabled, clipping, name, outline) to export functions like exportToSVG, exportToCanvas, exportToBlob

<img width="697" alt="image" src="https://github.com/excalidraw/excalidraw/assets/14358394/4c1ea3df-b710-425b-8bab-0f0804564ed2">

<img width="997" alt="image" src="https://github.com/excalidraw/excalidraw/assets/14358394/214541d6-ab0b-4c93-a7af-dc077a68595e">

**Comment by dwelle** [comment] 2023-08-18 07:46
We're not clipping on export by design, and only clip  when you export a single frame. The reasoning is we don't currently consider frames themselves (name, outline...) as exportable elements and exporting content without frames but clipping enabled felt weird.

@zsviczian  Are there any use cases you have in mind?

**Comment by zsviczian** [comment] 2023-08-18 08:45
This is the basic use-case (https://youtu.be/yZQoJg2RCKI). I extended image referencing to work with frames and would love to further extend to allow the user to set clipping or not in the reference link. Imagine a more complex architectural drawing that you want to explain part-by-part in a document. You would add frames to mark each of the parts and embed in the document using frame references. 

That said, this is not top of mind for me.

**Comment by tobalr** [comment] 2023-09-19 11:45
I just used frames for creating a small comic strip. However, as you write - it is not honored by the export. I had expected the frames feature to be just as WYSIWYG as the rest of Excalidraw.

**Comment by dwelle** [comment] 2023-11-03 22:01
this will be fixed in https://github.com/excalidraw/excalidraw/pull/7210, you can test wip preview (has some bugs) https://excalidraw-git-dwelle-render-frames-on-export-excalidraw.vercel.app/

**Closed** 2023-11-09 16:00 UTC
Labels: enhancement, discussion, frames
