### ISSUE TITLE
Clicking on the link redirects to about:blank

### ISSUE THREAD

**Issue by sdzialowski-godaddy** [excalidraw/excalidraw#7866] opened 2024-04-08 13:31 UTC
Steps to reproduce:

- Open https://excalidraw.com/
- create rectangle
- select it
- use the <img width="300" alt="image" src="https://github.com/excalidraw/excalidraw/assets/98088306/ddcb5288-f3de-44e2-a0fe-e8ac9e5752a3"> feature
- then deselect
- click on the link to go to the page 
<img width="323" alt="image" src="https://github.com/excalidraw/excalidraw/assets/98088306/c40b2bc2-033a-4d11-a9c5-e008c7118bed">

then this will open new tab with about:blank in the url

**Comment by ad1992** [comment] 2024-04-08 13:37
closing as duplicate of #7858

**Closed by ad1992** 2024-04-08 13:37 UTC
