### ISSUE TITLE
[npm package] Generates div with content from text field when I click out

### ISSUE THREAD

**Issue by devpanda0** [excalidraw/excalidraw#6828] opened 2023-07-30 01:19 UTC
When I create a text field and enter my text, and then I finish and click out into the background it creates a div where the content of the text field is in it

![image](https://github.com/excalidraw/excalidraw/assets/49129501/acec300a-9925-4489-b61d-02b55494cdbd)
![image](https://github.com/excalidraw/excalidraw/assets/49129501/3db3f6a5-4713-44ca-87e9-73927be10ede)
![image](https://github.com/excalidraw/excalidraw/assets/49129501/89dbb097-ca75-4890-9e54-1eacea585ec9)

**Comment by ad1992** [comment] 2023-07-31 03:37
@devpanda0 looks related to 3rd party, is this happening on https://excalidraw.com/ ?

**Comment by devpanda0** [comment] 2023-07-31 08:25
@ad1992  I have updated my project from NextJS 12 to 13 and since then I have the problem with the NPM package. When I do directly through the page I do not have the problem

**Comment by ad1992** [comment] 2023-07-31 09:45
@devpanda0 can you create a reproducible Code Sandbox example ? That would be helpful so we can look into it

**Comment by devpanda0** [comment] 2023-07-31 09:56
> @devpanda0 can you create a reproducible Code Sandbox example ? That would be helpful so we can look into it

i try it, give me some moment

**Comment by devpanda0** [comment] 2023-07-31 11:12
@ad1992 Here is an example https://8j38gg-3000.csb.app/test

**Comment by ad1992** [comment] 2023-08-01 05:22
@devpanda0 what are the steps to reproduce  in the code sandbox for the issue you are referring to ?

**Comment by devpanda0** [comment] 2023-08-01 07:31
1. go to the link above
2. create a text field for example with a double click
3. fill the text field randomly with values
4. then click outside the text field
5. then the div should appear on the top left

**Comment by ad1992** [comment] 2023-08-02 03:37
> 1. go to the link above
> 2. create a text field for example with a double click
> 3. fill the text field randomly with values
> 4. then click outside the text field
> 5. then the div should appear on the top left

Thats what I have been trying and it works well for me 👇🏻 

https://github.com/excalidraw/excalidraw/assets/11256141/ff89a5f3-a0ef-4c2b-99e5-40b40e5eed4c

**Comment by devpanda0** [comment] 2023-08-02 07:10
> > 1. go to the link above
> > 2. create a text field for example with a double click
> > 3. fill the text field randomly with values
> > 4. then click outside the text field
> > 5. then the div should appear on the top left
> 
> Thats what I have been trying and it works well for me 👇🏻

here is my view

https://github.com/excalidraw/excalidraw/assets/49129501/13ae1531-617e-4ca2-96e0-6c46c7f1b250

**Comment by devpanda0** [comment] 2023-08-02 07:30
I have found the problem. It was deepl the browser plugin. But error is only since I use NextJS 13. With NextJS 12 the problem was not

**Comment by ad1992** [comment] 2023-08-03 02:59
I doubt if its related to next js since I am not seeing it. which browser / OS you are using ?
I am checking on Chrome in Mac

**Comment by devpanda0** [comment] 2023-08-03 05:02
> I doubt if its related to next js since I am not seeing it. which browser / OS you are using ?
> 
> I am checking on Chrome in Mac

I use Brave

**Comment by ad1992** [comment] 2023-08-03 11:05
@devpanda0 I checked on brave as well. it works well. Whats your OS ?

**Comment by devpanda0** [comment] 2023-08-03 11:14
Windows 10/11. Try to install in the browser the deepl plugin and then try again.

**Comment by ad1992** [comment] 2023-08-03 11:27
Ok you meantioned above that its the browser deepl plugin which causes the error (probably you meant https://www.deepl.com/en/chrome-extension ? but I don't see a brave extension for this) , so it must be related to the browser plugin and not excalidraw as it works well without it (as I am not able to reproduce it) hence its not related to Excalidraw and works well in excalidraw app as well. 
I would close this issue since its related to 3rd party plugin.

Feel free to reopen if its related to Excalidraw

**Closed by ad1992** 2023-08-03 11:27 UTC
