### ISSUE TITLE
Can't identify saved file as an excalidraw file

### ISSUE THREAD

**Issue by carmine** [excalidraw/excalidraw#2151] opened 2020-09-10 23:04 UTC
When I save the diagram, I get multiple suffixes (ie ..excalidraw..excalidraw..excalidraw). But that is another problem.

The problem here is, when I try to load that file, my mac doesn't recognize the file. I have to select "all files".

**Comment by dwelle** [comment] 2020-09-11 17:19
Can't repro the duplicate `.excalidraw` on save issue (I'm on Windows), but can repro the filepicker issue on open. It seems to be related to latest change from #2149 /cc @tomayac any ideas?

**Comment by tomayac** [comment] 2020-09-11 17:36
What browser is this happening on? I assume it’s Chrome/Edge <86. The change (the API now requiring leading dots in the to-be-accepted file extensions [`.excalidraw` instead of `excalidraw`]) is one of these unfortunate breaking changes during the Origin Trial phase (which is why we have them in the first place). If you use Chrome/Edge >=86 it should work as expected.

**Comment by carmine** [comment] 2020-09-11 18:15
Yep, chrome < 86 (85.0.4183.102), on macos 10.15.6

**Comment by dwelle** [comment] 2020-09-11 18:33
I see. The problem is that the latest spec expects `.excalidraw` but the API shipped in Chrome 85 doesn't. One weird thing it works with `.json` currently (i.e. it lists `.json` files in the file picker in Chrome 85).

That solves the file picker bug.

The duplicate extension seems to be caused by the same problem. I still can't repro it, but it must be because it first saves the file (on Chrome 85) with double `..` (`filename..excalidraw`), and on second save it must not be recognized as an extension so it appends another `..excalidraw`. On Windows it's not happening, but I suppose on Mac it is.

@tomayac should we (can we) detect whether the browser uses the latest spec of the API and not prefix with `.` on our end? I reckon it'll take ~3 months before this is fixed in next stable release.

**Comment by joshuaiz** [comment] 2020-09-11 20:12
Having this same issue: Chrome Version 86.0.4240.30 (Official Build) beta (x86_64) on macOS.

Also cannot save files (will file another issue).

**Comment by tomayac** [comment] 2020-09-11 20:28
I fear the only way to detect this is via UA string parsing.  

This would have to happen [here](https://github.com/GoogleChromeLabs/browser-nativefs/blob/a9462d03fab6df41be6504c3190bd7a80fd1d11b/src/nativefs/file-save.mjs#L31) and [here](https://github.com/GoogleChromeLabs/browser-nativefs/blob/a9462d03fab6df41be6504c3190bd7a80fd1d11b/src/nativefs/file-open.mjs#L32). The logic would be: “if Chrome < 86 then remove potential leading dots”. It’s weird that this didn’t occur in my testing and apparently it doesn’t repro for all of you either. 

I can patch this after the weekend. Happy to merge a PR from anyone else earlier.

**Comment by tomayac** [comment] 2020-09-11 20:31
As an “emergency” patch, let’s remove the OT token for now. Doing this now. Note that this is part of the deal with Origin Trials that things break.

**Comment by tomayac** [comment] 2020-09-11 20:33
Someone please merge https://github.com/excalidraw/excalidraw/pull/2155 once tests have run.

**Comment by tomayac** [comment] 2020-09-14 08:52
There is someone else with the double-dot problem: https://bugs.chromium.org/p/chromium/issues/detail?id=853326#c232.

**Comment by mkruisselbrink** [comment] 2020-09-14 18:41
You could detect the double-dot issue also by trying without a dot in the extensions, and if that rejects with a TypeError you know you have a version that does require the dot in the extension. But the user agent check should work if all you care about is stable and beta.

**Comment by lipis** [comment] 2020-11-05 20:11
https://github.com/excalidraw/excalidraw/issues/2200#issuecomment-703522536

> Fixed in Chrome Beta, and will be fixed in Chrome 86 stable (Oct 8).

So it should be good now! If there is still an issue.. please report back.

**Closed by lipis** 2020-11-05 20:11 UTC
Labels: bug

**Comment by asoltys** [comment] 2021-03-08 22:16
I'm using Chrome 88 on Ubuntu 18 and just ran into this issue:

![image](https://user-images.githubusercontent.com/7641/110389086-dc635580-8018-11eb-98ac-d0e05a72637c.png)

It shows "Excalidraw file" in the dropdown in the bottom right, but doesn't add any extension at all.

**Comment by dwelle** [comment] 2021-03-08 22:24
@asoltys tracked here https://github.com/excalidraw/excalidraw/issues/3157
