### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ChristianKuenzel** [excalidraw/excalidraw#3519] opened 2021-04-30 12:21 UTC
### Scene content

```
{"excalidraw":[{"id":"P5jxiBIuBJP3Y0S68b5qp","type":"rectangle","x":455,"y":170,"width":1149,"height":724,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":1019024472,"version":182,"versionNonce":2015690024,"isDeleted":false,"boundElementIds":null},{"id":"wfVTbP9xr7Ei19_CaHcJd","type":"line","x":531,"y":170,"width":3,"height":724,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"round","seed":2122446376,"version":125,"versionNonce":1267245096,"isDeleted":false,"boundElementIds":null,"points":[[0,0],[-3,724]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"OT1iPcr0e4IW3Fp6z4eGu","type":"rectangle","x":464,"y":178,"width":60,"height":59,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":1154636584,"version":32,"versionNonce":793454168,"isDeleted":false,"boundElementIds":null},{"id":"wqOFGo47oFjwApk4RpL5T","type":"draw","x":482,"y":192,"width":3,"height":12,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"round","seed":1690606424,"version":14,"versionNonce":1329506344,"isDeleted":false,"boundElementIds":null,"points":[[0,0],[-3,12]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"_Dru_P78UJLebQvG-fUNP","type":"draw","x":483,"y":196,"width":24,"height":2,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"round","seed":1199394392,"version":29,"versionNonce":1828770904,"isDeleted":false,"boundElementIds":null,"points":[[0,0],[24,1],[24,-1]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"rrgigb4KiwhgGSydRdJ2u","type":"draw","x":509,"y":195,"width":17,"height":33,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"round","seed":2137472296,"version":39,"versionNonce":2062949928,"isDeleted":false,"boundElementIds":null,"points":[[0,0],[-7,5],[-16,33],[-17,33]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"2QVrIR-DQ3O2pgSEUaD-c","type":"draw","x":488,"y":218,"width":19,"height":8,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"round","seed":1839216728,"version":28,"versionNonce":1709357096,"isDeleted":false,"boundElementIds":null,"points":[[0,0],[1,-3],[17,-4],[19,-8]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"yPKM0qC0h6c5WvurCfUwO","type":"line","x":457,"y":256,"width":78,"height":1,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"round","seed":1759657560,"version":39,"versionNonce":497290584,"isDeleted":false,"boundElementIds":null,"points":[[0,0],[78,-1]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"n2J8ofxXdQi_9NXtwBNgd","type":"rectangle","x":463,"y":263,"width":59.999999999999964,"height":60,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":90743384,"version":67,"versionNonce":435707736,"isDeleted":false,"boundElementIds":null},{"id":"Ntmtso6VLXcuWinCjK_MG","type":"rectangle","x":475,"y":274,"width":39,"height":39,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":1466086488,"version":36,"versionNonce":1031022632,"isDeleted":false,"boundElementIds":null},{"id":"HlzUFJOuGVMuNCTfGMvhg","type":"rectangle","x":477,"y":277,"width":34,"height":9,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":559926872,"version":22,"versionNonce":1251119400,"isDeleted":false,"boundElementIds":null},{"id":"8jVhhywm7LcgFFF56K7fW","type":"rectangle","x":478,"y":290,"width":6,"height":7,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":1249408344,"version":21,"versionNonce":1869381976,"isDeleted":false,"boundElementIds":null},{"id":"1PHbVISY5JFVKjEkZTXCD","type":"rectangle","x":487,"y":290.5,"width":6,"height":7,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":551739480,"version":68,"versionNonce":65377320,"isDeleted":false,"boundElementIds":null},{"id":"t3uRrDYHKu977P_yZzOdH","type":"rectangle","x":496,"y":290.5,"width":6,"height":7,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":1299238696,"version":73,"versionNonce":308037672,"isDeleted":false,"boundElementIds":null},{"id":"AVudRn4Vgh81Ck0F8F5Q2","type":"rectangle","x":506,"y":290.5,"width":6,"height":7,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":1123091240,"version":73,"versionNonce":1425865768,"isDeleted":false,"boundElementIds":null},{"id":"85MuzpwZ08VH87cd6tDyw","type":"rectangle","x":478,"y":299.5,"width":6,"height":7,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":1465595688,"version":61,"versionNonce":1462560856,"isDeleted":false,"boundElementIds":null},{"id":"hVhNYA4ujt4Zj9CkGHxVA","type":"rectangle","x":486.57142857142856,"y":299.7857142857143,"width":6,"height":7,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":1864244568,"version":78,"versionNonce":185861416,"isDeleted":false,"boundElementIds":null},{"id":"qH0iPjTR_-3rx6jrkRxGI","type":"rectangle","x":495.7142857142857,"y":299.5,"width":6,"height":7,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":1887598120,"version":109,"versionNonce":1879102808,"isDeleted":false,"boundElementIds":null},{"id":"wXqFu9zUV5sqOdQ-jC7aZ","type":"rectangle","x":505.1428571428573,"y":299.78571428571445,"width":6,"height":7,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":15493720,"version":74,"versionNonce":508690264,"isDeleted":false,"boundElementIds":null},{"id":"rsm9H8cIEPyrpcZbhbqz-","type":"text","x":489,"y":268.5,"width":10,"height":26,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"sharp","seed":101885480,"version":1,"versionNonce":0,"isDeleted":false,"boundElementIds":null,"text":"","fontSize":20,"fontFamily":1,"textAlign":"center","verticalAlign":"middle","baseline":18}],"excalidraw-state":{"theme":"light","currentChartType":"bar","currentItemBackgroundColor":"transparent","currentItemEndArrowhead":"arrow","currentItemFillStyle":"hachure","currentItemFontFamily":1,"currentItemFontSize":20,"currentItemLinearStrokeSharpness":"round","currentItemOpacity":100,"currentItemRoughness":1,"currentItemStartArrowhead":null,"currentItemStrokeColor":"#000000","currentItemStrokeSharpness":"sharp","currentItemStrokeStyle":"solid","currentItemStrokeWidth":1,"currentItemTextAlign":"left","cursorButton":"up","editingGroupId":null,"elementLocked":false,"elementType":"selection","exportBackground":true,"exportEmbedScene":false,"exportWithDarkMode":false,"gridSize":null,"lastPointerDownWith":"mouse","name":"Untitled-2021-04-30-1412","openMenu":null,"previousSelectedElementIds":{},"scrolledOutside":false,"scrollX":51.14285714285715,"scrollY":74.00000000000001,"selectedElementIds":{"HlzUFJOuGVMuNCTfGMvhg":true},"selectedGroupIds":{},"shouldAddWatermark":false,"shouldCacheIgnoreZoom":true,"showStats":false,"viewBackgroundColor":"#ffffff","zenModeEnabled":false,"zoom":{"value":10,"translation":{"x":-4949.1428571428605,"y":-3270.714285714286}}},"i18nextLng":"de"}
```

Error after zooming into small rectangle and trying to write in it with doubleclickon rectangle.

### Sentry Error ID

c0afc2011de84ba89f2bda46874d532d

**Comment by dwelle** [comment] 2021-07-22 19:43
Sorry for ignoring this, it somehow got lost. That said, I cannot reproduce manually and the sentry id (again) doesn't lead anywhere.

I'll close this for now. Let me know if you can still reproduce this error and I'll reopen.

**Closed by dwelle** 2021-07-22 19:43 UTC
