### ISSUE TITLE
vertical distribution action behaves weird

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2411] opened 2020-11-24 22:47 UTC
Without digging deep it seems that distributing vertically isn't quite correct.

1. First off, AFAIK it should distributing within common bounding box, but it tends to distribute some elements outside.
2. Related to previous point, executing the action several times in a row keeps changing the distribution. The action should be idempotent.

Repro: https://excalidraw.com/#json=6328897570340864,8r03Rmf9N3139NloxmHpBA (execute vertical distribution action several times)

/cc @steveruizok

**Comment by lipis** [comment] 2020-11-25 10:36
Here as well.. click multiple times on distribute horizontal or vertical..

https://excalidraw.com/#json=5754487973085184,ELjQNaO5MgigYK1ON4WlmA

**Comment by steveruizok** [comment] 2020-11-25 11:16
Hey, looking into this now. It's actually a tricky question: how to handle distributing space when the gaps are negative. Just to show that we're in good company, here's the same bug in Figma.

![2020-11-25 at 9 57 28 - Aqua Wolverine](https://user-images.githubusercontent.com/23072548/100212048-c9fb5b00-2f04-11eb-8b64-97145eff9bf6.gif)

I think I have a solution, adapted from draw.io's distribute pattern. But it also has a bug that shows up when the box that defines the bottom bounds is not also the last box in the sort order. (For a vertical group, that would be when the box with the greatest `maxY` is not also the box with the greatest `y`.)


![2020-11-25 at 11 12 35 - Blue Leopard](https://user-images.githubusercontent.com/23072548/100220739-abe72800-2f0f-11eb-8846-474cfd87d0d5.gif)

**Comment by steveruizok** [comment] 2020-11-25 11:20
Inkscape also has this bug, but it's less clear in that case that it is a bug: they have different options for distributing space between items—which will change the overall bounding box—as well as distributing space between centers, which I think is what we're actually after, and seems to be the approach that draw.io uses.

![image](https://user-images.githubusercontent.com/23072548/100221189-3f205d80-2f10-11eb-97b8-6408a50a5b4f.png)

**Comment by dwelle** [comment] 2020-11-25 11:45
Yea, I agree it's hard to even figure out conceptually what we want it to do. Maybe nothing when the gaps are negative.

**Comment by lipis** [comment] 2020-11-25 13:05
> Maybe nothing when the gaps are negative.

Or putting them centrally.. so at least we are doing something with them... equally from the center. (Center horizontally / Center vertically)

**Comment by steveruizok** [comment] 2020-11-25 13:14
I was thinking the same @lipis: distribute centers as a fallback. 

But the problem isn't actually when gaps are negative: it's when the item at the end of the sort isn't defining the bottom of the bounding box. The example below has a positive step but will still produce the bug.

![image](https://user-images.githubusercontent.com/23072548/100232302-1a33e680-2f20-11eb-9bb3-b16f1f8defb8.png)

**Comment by steveruizok** [comment] 2020-11-25 13:15
This can be fixed by sorting by middle points (`midX` or `midY`) rather than min points (`x` or `y`).

**Comment by dwelle** [comment] 2020-11-25 13:20
> This can be fixed by sorting by middle points (`midX` or `midY`) rather than min points (`x` or `y`).

Sounds good. What are the cases where it'll end up in a suboptimal distribution?

**Comment by steveruizok** [comment] 2020-11-25 13:22
Sometimes a negative gap is stable, sometimes it isn't. 🤯 Here I've just moved the red box a bit lower down.

![2020-11-25 at 13 20 29 - Orange Rat](https://user-images.githubusercontent.com/23072548/100233113-2cfaeb00-2f21-11eb-8213-f1abc64eb0a0.gif)

**Comment by steveruizok** [comment] 2020-11-25 16:00
Ok, I think I've got it. https://github.com/excalidraw/excalidraw/pull/2415

**Closed** 2020-11-26 00:52 UTC
Labels: bug
