### ISSUE TITLE
excalidraw script is not loading 

### ISSUE THREAD

**Issue by Sohailamjad1** [excalidraw/excalidraw#5434] opened 2022-07-11 15:46 UTC
https://unpkg.com/@excalidraw/excalidraw/dist/excalidraw.production.min.js
https://unpkg.com/react@16.14.0/umd/react.development.js
https://unpkg.com/react-dom@16.13.1/umd/react-dom.development.js
these scripts are not loading please check and give solutions for that ...Thankyou

**Comment by Sohailamjad1** [comment] 2022-07-12 05:17
@ad1992  did you guys update any package or anything else..because excalidraw is not loading for any of the enviroments please check

**Comment by ad1992** [comment] 2022-07-12 05:33
Yes there was a [breaking change](https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/CHANGELOG.md#breaking-change-4) pushed in the last release, `Excalidraw` is no more a default export, please go through the changelog when upgrading.

**Comment by Sohailamjad1** [comment] 2022-07-12 05:35
> Yes there was a [breaking change](https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/CHANGELOG.md#breaking-change-4) pushed in the last release, `Excalidraw` is no more a default export, please go through the changelog when upgrading.

okay..so what i have to do to fix this ??

**Comment by Sohailamjad1** [comment] 2022-07-12 05:49
Hi @ad1992 i need that fix immediately .. can you please guide me how to fix this?

**Comment by ad1992** [comment] 2022-07-12 06:03
> Hi @ad1992 i need that fix immediately .. can you please guide me how to fix this?
Its already mentioned in the changelog I linked above!

**Comment by Sohailamjad1** [comment] 2022-07-12 06:05
> 

There is so much changes i can see here ..so which things i have take and change in my code

**Comment by Sohailamjad1** [comment] 2022-07-12 06:32
we are already using in browser things..and for me not even those scripts are not loading
https://unpkg.com/@excalidraw/excalidraw/dist/excalidraw.production.min.js
https://unpkg.com/react@16.14.0/umd/react.development.js
https://unpkg.com/react-dom@16.13.1/umd/react-dom.development.js

**Comment by ad1992** [comment] 2022-07-12 06:37
The scripts are loading (You can verify that by opening those links in browser) and its loading as well in [example](https://tlqom.csb.app/), in case its not working for you please share the codesandbox example

**Comment by Sohailamjad1** [comment] 2022-07-12 06:38
The above error occurred in the <App> component:
    in App
    in div

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

these are the errors iam getting

**Comment by Sohailamjad1** [comment] 2022-07-12 06:50
> The scripts are loading (You can verify that by opening those links in browser) and its loading as well in [example](https://tlqom.csb.app/), in case its not working for you please share the codesandbox example

can we have a call???for debugging this issue 
till friday it was working in every enviroments but from yesterday its breaking to every enviroments ..so can we please take a quick call and fix this ..

**Comment by Sohailamjad1** [comment] 2022-07-12 08:19
![excalidraw-screenshot](https://user-images.githubusercontent.com/86312321/178443896-914036c6-64d6-46d8-96c9-960027bf7466.png)
please check code how iam writing ..i have attached screen shot

**Comment by Sohailamjad1** [comment] 2022-07-12 08:21
> ![excalidraw-screenshot](https://user-images.githubusercontent.com/86312321/178443896-914036c6-64d6-46d8-96c9-960027bf7466.png) please check code how iam writing ..i have attached screen shot

![excalidraw-screen 2](https://user-images.githubusercontent.com/86312321/178444409-2ecc740d-0a2d-4344-a759-c27350047cb0.png)

**Comment by ad1992** [comment] 2022-07-12 09:29
How are you loading Excalidraw ? Did you update the code for loading Excalidraw as mentioned in breaking changes ?

**Comment by Sohailamjad1** [comment] 2022-07-12 09:37
> How are you loading Excalidraw ? Did you update the code for loading Excalidraw as mentioned in breaking changes ?

which code i need to update for loading the excalidraw..and where i have to change
![image](https://user-images.githubusercontent.com/86312321/178460000-adf720bc-26c2-4269-9e17-5e9b663a0fca.png)
iam already using browser one

**Comment by ad1992** [comment] 2022-07-12 09:50
> > How are you loading Excalidraw ? Did you update the code for loading Excalidraw as mentioned in breaking changes ?
> 
> which code i need to update for loading the excalidraw..and where i have to change ![image](https://user-images.githubusercontent.com/86312321/178460000-adf720bc-26c2-4269-9e17-5e9b663a0fca.png) iam already using browser one and i have shared my code already how i have written..please let me know

I don't see the code for loading Excalidraw in your screenshots!  Make sure you are loading it as mentioned in above screenshot then it will work. The same we are doing in example as well so you can refer to the example for the same.

**Comment by Sohailamjad1** [comment] 2022-07-12 10:02
> > > How are you loading Excalidraw ? Did you update the code for loading Excalidraw as mentioned in breaking changes ?
> > 
> > 
> > which code i need to update for loading the excalidraw..and where i have to change ![image](https://user-images.githubusercontent.com/86312321/178460000-adf720bc-26c2-4269-9e17-5e9b663a0fca.png) iam already using browser one and i have shared my code already how i have written..please let me know
> 
> I don't see the code for loading Excalidraw in your screenshots! Make sure you are loading it as mentioned in above screenshot then it will work. The same we are doing in example as well so you can refer to the example for the same.

iam doing in a different way than yours..so i can't update code like yours..pls check i have shared my screen shot
![export excalidraw](https://user-images.githubusercontent.com/86312321/178465312-aa52954d-f5d6-432c-9c29-e814eeb32904.png)

**Comment by Sohailamjad1** [comment] 2022-07-12 12:04
> > > > > How are you loading Excalidraw ? Did you update the code for loading Excalidraw as mentioned in breaking changes ?
> > > > 
> > > > 
> > > > which code i need to update for loading the excalidraw..and where i have to change ![image](https://user-images.githubusercontent.com/86312321/178460000-adf720bc-26c2-4269-9e17-5e9b663a0fca.png) iam already using browser one and i have shared my code already how i have written..please let me know
> > > 
> > > 
> > > I don't see the code for loading Excalidraw in your screenshots! Make sure you are loading it as mentioned in above screenshot then it will work. The same we are doing in example as well so you can refer to the example for the same.
> > 
> > 
> > iam doing in a different way than yours..so i can't update code like yours..pls check i have shared my screen shot ![export excalidraw](https://user-images.githubusercontent.com/86312321/178465312-aa52954d-f5d6-432c-9c29-e814eeb32904.png)
> 
> This is what I have been mentioning so many times :(, please update the below code as Excalidraw is no more the default component. So it should be `ExcalidrawLib.Excalidraw` instead. ![image](https://user-images.githubusercontent.com/11256141/178479320-2c99a20c-7f12-4605-933d-ee97ee6d6499.png)
> 
> Please read the replies and update the code correctly.

after Adding Excalidraw its showing cannot find name ..need to import anything
![image](https://user-images.githubusercontent.com/86312321/178485794-8bfc492c-e844-4858-b6b3-c4043ef3799e.png)

**Comment by ad1992** [comment] 2022-07-12 12:20
Its hard to debug from screenshots! please share a reproducible codesandbox example, you can refer to the [example](https://tlqom.csb.app/) to understand how its used.

**Comment by Sohailamjad1** [comment] 2022-07-13 06:27
> Its hard to debug from screenshots! please share a reproducible codesandbox example, you can refer to the [example](https://tlqom.csb.app/) 
Hi @ad1992 i have checked your example code ..but that is different than my code  and i have modified in my way..so iam not getting like how to resolved the issue...its major breaking change and free diagram got broked for all the enviroments even production..its difficult find the exact issue..can we take a call and fix asap..i think for it will take less than 5 min

**Comment by ad1992** [comment] 2022-07-13 11:24
@Sohailamjad1 as per your comment above looks like the issue is fixed, hence closing this. Feel free to reopen if it persists.

**Closed by ad1992** 2022-07-13 11:24 UTC
