### ISSUE TITLE
Please adding hand-write CJK fonts.

### ISSUE THREAD

**Issue by cszwdy** [excalidraw/excalidraw#1755] opened 2020-06-15 01:21 UTC
Excalidraw is awesome and may be can add default hand-write CJK fonts?  such as HanZiPen: https://hk.maisfontes.com/hanzipen-sc-regular and Chihaya Jun: https://www.freejapanesefont.com/chihaya-jun-download/

**Comment by dwelle** [comment] 2020-06-15 19:59
https://hk.maisfontes.com/hanzipen-sc-regular is only for personal use. https://www.freejapanesefont.com/chihaya-jun-download/ is a Japanese font. If you can find a suitable font for Chinese characters and post it in https://github.com/excalidraw/excalidraw/issues/1290, that would be great.

Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/1290

**Closed by dwelle** 2020-06-15 19:59 UTC
