### ISSUE TITLE
Option to change position of Arrow Points

### ISSUE THREAD

**Issue by GasimGasimzada** [excalidraw/excalidraw#657] opened 2020-02-01 15:30 UTC
This is something that I was thinking when implementing multi point arrows. I suggest to add a UI to the panel for arrows that can set the position of each arrow. There are going to be four modes: At Start, At End, In Both Sides, and Nothing. If we implement this, we won't even need the line shape anymore because lines will be arrows with "Nothing" selected as arrow points. 

Since I have set up migration from old arrow spec to a new one in the app, I can extend that logic for line shapes to convert them to arrows.

Naming shouldn't matter -- we can call the shape arrow or line; plus we can also use the last value stored for the arrows to change the tool's icon.

**Comment by lipis** [comment] 2020-02-01 15:58
We should definitely keep the line and arrow as separate icons without extra configuration, regardless of how they implemented underneath.

**Comment by dwelle** [comment] 2020-02-01 16:42
I've discussed this with @vjeux previously a we decided to keep the line and arrow separate tools, as @lipis mentions.

**Comment by GasimGasimzada** [comment] 2020-02-01 17:19
I am already working on making lines and arrows the same (#660). If the first part of this issue is desirable (e.g we can enable arrow position tool only for arrows and keep lines as is), I will work on it after line PR is finished.

**Comment by dwelle** [comment] 2020-02-01 17:25
Yes, the part about changing arrow ends is fine. In time we'll also want to support other types of ends such as https://github.com/excalidraw/excalidraw/issues/616, I reckon.

The ability to switch arrow ends may seem not that important, but one use case could be that someone draw some complicated arrow diagram and decides the relationships should be swapped, in which case it would be cool to simply switch the arrow end instead of trying to rotate the arrow.

**Comment by lipis** [comment] 2020-07-01 17:56
Duplicate of #616

**Closed by lipis** 2020-07-01 17:56 UTC
