### ISSUE TITLE
production build broken in Vite

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#5035] opened 2022-04-13 19:42 UTC
Unclear what Vite does on production build, but it breaks Excalidraw:

```
index.22c8f9a6.js:32 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at $0 (index.22c8f9a6.js:32:49942)
    at G (index.22c8f9a6.js:30:17215)
    at Ur (index.22c8f9a6.js:32:10779)
    at i3 (index.22c8f9a6.js:32:46238)
    at n3 (index.22c8f9a6.js:32:40175)
    at L8 (index.22c8f9a6.js:32:40103)
    at ym (index.22c8f9a6.js:32:39956)
    at gv (index.22c8f9a6.js:32:36292)
    at J4 (index.22c8f9a6.js:32:35256)
    at fe (index.22c8f9a6.js:17:1678)
```

Repro:

https://stackblitz.com/edit/vitejs-vite-qa5tsy?file=package.json&terminal=serve

**Comment by ad1992** [comment] 2022-04-15 09:56
Was looking into this and this looks like an issue with vite js using roll-up plugin and hasn't been fixed yet, the recommended solution to fix is to use the default export until it gets fixed in rollup plugin / vite itself. 
```js
const ExcalidrawComp = Excalidraw.default ? Excalidraw.default : Excalidraw;
```

and use <ExcalidrawComp/> in rendering.
https://github.com/vitejs/vite/issues/2139
https://github.com/rollup/plugins/issues/481

Sadly this affects a lot of popular libs as well like react-select, react-switch , react-notification and a lot more

Also here it like the issue is only with just default export,  as rollup is not able to identify the default export hence all libs using default export tend to fail so not using default export should fix this as well

**Closed** 2022-04-15 12:42 UTC
Labels: bug, package:excalidraw

**Comment by kulame** [comment] 2023-01-27 09:43
it also wrong.

```bash
src/nodes/ExcalidrawNode/ExcalidrawModal.tsx:183:34 - error TS2339: Property 'default' does not exist on type 'typeof import("F:/code/skill/know/node_modules/.pnpm/@excalidraw+excalidraw@0.14.1_biqbaboplfbrettd7655fr4n2y/node_modules/@excalidraw/excalidraw/types/packages/excalidraw/index")'.

183   const _Excalidraw = Excalidraw.default ? Excalidraw.default : Excalidraw;
```
