### ISSUE TITLE
Possibility of hexagon shape

### ISSUE THREAD

**Issue by ThingsTom** [excalidraw/excalidraw#2180] opened 2020-09-22 09:27 UTC
Loving the tool! Can we have support for a hexagonal shape and my life will be complete ;-)

**Comment by dwelle** [comment] 2020-09-22 10:30
Just draw some hexagons, add the to the library, and reuse: https://excalidraw.com/#json=5698362649083904,VEObfBmrJ9kKTyi3W8kUug

Anyway, this is a duplicate of https://github.com/excalidraw/excalidraw/issues/366

**Closed by dwelle** 2020-09-22 10:30 UTC
