### ISSUE TITLE
Reconciliation algorithm breaks z-order

### ISSUE THREAD

**Issue by petehunt** [excalidraw/excalidraw#2165] opened 2020-09-16 00:12 UTC
The reconciliation algorithm does not sync z-order correctly. Repro by overlaying two shapes with solid fill colors and moving one to the front. You'll see that in collaborative mode both peers may not converge to the same state.

**Comment by dwelle** [comment] 2020-09-16 08:01
duplicate of https://github.com/excalidraw/excalidraw/issues/1376

**Closed by dwelle** 2020-09-16 08:01 UTC
Labels: bug, collaboration
