### ISSUE TITLE
Japanese handwritten font-family

### ISSUE THREAD

**Issue by t6adev** [excalidraw/excalidraw#1615] opened 2020-05-18 15:38 UTC
Hi there!
Currently, Virgil has been only adopted as handwritten font. 

My mother language is Japanese. So I'd like to apply any handwritten Japanese font-family that is distinguished from Chinese traditional/simplified fonts. (Related to #1290 )

Is there any recommended way for applying other font-family?
If there is nothing in particular, I can send a PR to start discussion how to do it.
Now I just modified code to apply the free font which is [あんずもじ](http://www8.plala.or.jp/p_dolce/site3-1.html).
Thank you.

![2020-05-19 0 35 13](https://user-images.githubusercontent.com/6883692/82231796-a6a98f00-9968-11ea-91fb-20a6245f887c.png)

**Comment by vjeux** [comment] 2021-02-05 19:24
We're looking for another handwritten font. If you could add suggestions for the fonts listed in this issue that'd be useful. Thanks! #2945

**Comment by tell-y** [comment] 2021-02-07 01:51
Thank you and sorry for my bad work.
I'll post new suggestion in the issue.

**Comment by tell-y** [comment] 2021-02-07 02:08
I got good news that https://github.com/fontworks-fonts provides some free fonts on github.
I recommend https://github.com/fontworks-fonts/RocknRoll if it's acceptable. #2945
![RocknRoll](https://github.com/fontworks-fonts/RocknRoll/blob/master/image_RocknRoll.png?raw=true)

**Comment by thorn0** [comment] 2021-02-28 18:21
Hi @tell-y 

>  apply any handwritten Japanese font-family that is distinguished from Chinese

Am I correct to understand that it's impossible to use one handwritten font for both Japanese and Chinese?
That would be very unfortunate.

Now that Virgil, the font Excalidraw uses, became open source (see https://github.com/excalidraw/virgil), the community can contribute support for more different scripts to it so that it could support not only Latin, Greek, and Cyrillic like now.

**Comment by tell-y** [comment] 2021-03-07 06:12
Hi @thorn0, Yes, you are right.
It's what dai-shi said [here](https://github.com/excalidraw/excalidraw/pull/2429#issuecomment-735798007).
So I agree [this](https://github.com/excalidraw/excalidraw/pull/2429#issuecomment-736947492).

I fond good sample to show what happen by incomplete font-family settings.
https://help.wrike.com/hc/ja/community/posts/360019266754-Chinese-characters-displayed-in-mixed-fonts
![mixed-font-family-sample](https://user-images.githubusercontent.com/6883692/110230840-15d38c80-7f57-11eb-8a23-ec84bfe54451.png)

Anyway, good to hear about excalidraw/virgil, thank you for considering about it!!

**Comment by Mrazator** [comment] 2024-10-16 19:53
We will be releasing support for the whole CJK soonish! (https://github.com/excalidraw/excalidraw/pull/8530)

Feel free to give us early feedback, preview is available here:
https://excalidraw-git-mrazator-first-class-support-chinese-excalidraw.vercel.app/

Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/8408

---

The lacking-double-codepoint issue between Japenese and Chinese will be resolved in the future, likely with a separate Japanese font.

**Closed by Mrazator** 2024-10-16 19:53 UTC
Labels: font
