### ISSUE TITLE
Offsets not updating correctly when embedded in scrollable website

### ISSUE THREAD

**Issue by junyongxlee** [excalidraw/excalidraw#3175] opened 2021-03-05 08:56 UTC
https://youtu.be/QyXFw99aPnI

Offsets seem to not be updated immediately when the parent screen is scrolled. It will be updated when actions are done on the canvas.

**Comment by ad1992** [comment] 2021-03-05 09:03
As per the video looks like it just has excalidraw in the host app so is it possible to share a codesandbox example with the same?

**Comment by junyongxlee** [comment] 2021-03-05 10:07
> As per the video looks like it just has excalidraw in the host app so is it possible to share a codesandbox example with the same?

Here you go, it's a very simple test-app to test out the package.

https://codesandbox.io/s/dank-water-gmqbx?file=/src/App.js

**Comment by ad1992** [comment] 2021-03-05 12:30
@junyongxlee I am not able to reproduce it in the code sandbox example. It's working fine for me and offsets are also getting updated. Could you confirm if it's reproducible for you and share the steps?

Also, you need to add a `position: relative` in the `excalidraw-wrapper` class and give `width/height` to the `excalidraw-wrapper` so that UI renders correctly (right now the zoom, GitHub, and help icons are rendered outside, they will be positioned absolute to the the `excalidraw-wrapper` once you give position relative)
This will not be needed once https://github.com/excalidraw/excalidraw/pull/3174 is merged.

**Comment by junyongxlee** [comment] 2021-03-05 14:46
I have edited the code to fix the positioning. It's actually working intermittently for me and the problem doesn't show up all of the time. It happens often enough to be easily reproducible, more than half the time.

Here are the steps to reproduce the bug:
1. With the page not scrolled yet, select draw and draw a straight line on the canvas (to test it is working fine).
2. Without clicking anything, move the pointer outside of the excalidraw-wrapper
4. Scroll the page down, leave some parts of the canvas still showing on top.
5. Move the pointer back and draw a straight line again on the canvas without first clicking on the canvas. (At this point the page is still scrolled down).

**Comment by ad1992** [comment] 2021-03-05 15:56
Interesting, sadly it works for me everytime :/ 
![sc](https://user-images.githubusercontent.com/11256141/110139161-be1f0f00-7df8-11eb-9ca3-752c01a92923.gif)

Do you face the same issue in the [codesandbox example] (https://ehlz3.csb.app/)  as well?

**Comment by dwelle** [comment] 2021-03-05 16:05
I can repro but it falls down to being too fast (there's a 500ms debounce for the scroll event). Can't repro outside those cases.

@ad1992 we should maybe decrease the debounce.

Also, this `scroll` event only catches full-page scrolling, and won't work in case it's inside a different scrollable container. It touches on the same issue I raised in the PR: we need to figure out how to detect position changes — but outside of polling (which I'd hate to do) I'm not sure there's a solution.

**Comment by ad1992** [comment] 2021-03-05 16:31
>I can repro but it boils down to being too fast (there's a 500ms debounce for the scroll event). Can't repro outside those cases.

Should we decrease to 100ms then?

> Also, this scroll event only catches full-page scrolling, and won't work in case it's inside a different scrollable container. It touches on the same issue I raised in the PR: we need to figure out how to detect position changes — but outside of polling (which I'd hate to do) I'm not sure there's a solution.

Yeah, there is one more corner case, if any of the parent divs have overflow then also it won't work so I was thinking if we can identify the nearest scrollable container and add the listener to that container (keeping in mind that it doesn't impact perf).

**Comment by dwelle** [comment] 2021-03-05 17:51
> Should we decrease to 100ms then?

Yes.

The API itself is actually fast, so polling may not be out of the question (if we make sure we don't actually update the state if nothing changed).

**Comment by junyongxlee** [comment] 2021-03-05 20:27
I have tried changing the scroll polling rate and the draw tool is working smoothly now. The text element however still has a bug. When scrolled away from the original position, clicking on the canvas with the text tool results in the editable text box being created on the previous scroll location. After typing the text and continuing the created text will however jump to the right location.

**Comment by ad1992** [comment] 2021-03-06 08:51
@junyongxlee can you confirm if the text element bug you are talking about is similar to #3180  ?

**Closed** 2021-03-06 13:36 UTC
Labels: bug, package:excalidraw

**Comment by junyongxlee** [comment] 2021-03-06 14:13
> @junyongxlee can you confirm if the text element bug you are talking about is similar to #3180?
> 
> Also if you can test it out [here](https://3scmb.csb.app/), the experience should be smooth now.

It is similar to #3180. However, I can't seem to reproduce the same bug on the test sandbox you have attached as well as the sandbox I have posted above. It seems to only happen on the website I am building. Both are using the latest 0.4.1 version of excalidraw.

Here's a screen record below showing the problem.

![SCREENRECORD](https://user-images.githubusercontent.com/66911725/110209687-b3cc4600-7ec8-11eb-8423-0231a83b7711.gif)



This is the code used to embed excalidraw in my project. "excalidraw-wrapper" class is set to relative positioning. The line drawn with the draw tool is not important in this case, it is drawn to use as a reference point. Only the text element is buggy.
```
<div className="excalidraw-wrapper">
    <Excalidraw
        width={width * 0.719}
        height={height}
    />
</div>
```
