### ISSUE TITLE
Arrowbinding seems to be broken when moving object with arrow keys

### ISSUE THREAD

**Issue by tmelz** [excalidraw/excalidraw#2088] opened 2020-08-26 22:11 UTC
Setup: draw an arrow between box A & B

If I click & drag box B, the arrow is still bound to it. But if i select B and move it with arrow keys, the arrow is no longer bound (unexpected)

**Comment by dwelle** [comment] 2020-08-27 08:43
duplicate of https://github.com/excalidraw/excalidraw/issues/2074

**Closed by dwelle** 2020-08-27 08:43 UTC
Labels: bug
