### ISSUE TITLE
Remove Monkey and Pig references from random names

### ISSUE THREAD

**Issue by SecondThread** [excalidraw/excalidraw#7262] opened 2023-11-09 21:36 UTC
Meta uses Excalidraw for some of our interviews. We had a candidate referred to as a "determined baboon" by the autogenerated usernames today, which ruffled some feathers.

Removing Ape, Baboon, Monkey, and Pig from the list of randomly generated usernames https://socket.dev/npm/package/@excalidraw/random-username/files/1.0.0/src/index.ts would smooth things over.

**Comment by dwelle** [comment] 2023-11-11 18:23
Removed plus some more (note that pig was never in the list): https://github.com/excalidraw/random-username/compare/434d2a5c875d6cc370af5e29c5e2756aa4fadcb0..7f15b01b7f96f932def9638156e3496791824683

Fixed via https://github.com/excalidraw/excalidraw/issues/7262

**Closed by dwelle** 2023-11-11 18:23 UTC

**Comment by ccw-morris** [comment] 2026-05-27 14:41
I was using excalidraw.com last week, and it generated the name "Fancy Baboon" for someone else on the call. Earlier this week, I tried a few times with incognito sessions and it generated "Spectacular Dog" - after a few tries; Dog should have also been removed by the above PR.

It might be caused by this line, which is still pulling in the old version of the random names repo.
https://github.com/excalidraw/excalidraw/blob/c08be69618dcac9386817bced03d2d79883e50b6/excalidraw-app/package.json#L29
