### ISSUE TITLE
Not able to click on Browe library section

### ISSUE THREAD

**Issue by shivam1410** [excalidraw/excalidraw#5637] opened 2022-08-29 13:04 UTC
![image](https://user-images.githubusercontent.com/33784139/187207612-afda9320-e590-447e-b575-e9d0e3b2a8ea.png)

**Comment by ThisIsMyGithubRepo** [comment] 2022-08-29 13:11
For me, clicking in the library panel just dismisses it - which means I can't even add an item to the canvas once it's in the library.

Reproduction Steps:
1. Go to Excalidraw library: https://libraries.excalidraw.com/?theme=light&sort=default
2. Pick several libraries and click add to Excalidraw for each of them. You want a lot of icons so that the library panel needs to scroll.
3. Go back to excalidraw and open the library panel.
4. Attempt to scroll in the library just causes the panel to dismiss.
5. Attempt to click on a library item just causes the panel to dismiss.

I'm commenting here b/c I assume this is the same issue.

**Comment by d1onys1us** [comment] 2022-08-29 13:22
yes i am having the exact same issue. +1

**Comment by YuiiraX** [comment] 2022-08-29 13:33
https://github.com/excalidraw/excalidraw/pull/5636
seems to have been caused by this PR

**Comment by ad1992** [comment] 2022-08-29 13:56
This should be fixed now. Thanks for reporting this.

**Closed** 2022-08-29 13:56 UTC

**Comment by ThisIsMyGithubRepo** [comment] 2022-08-29 16:31
Confirmed working for me.
Thanks!

**Comment by shivam1410** [comment] 2022-08-29 19:35
Working for me, thanks
