### ISSUE TITLE
Can't turn off pressure sensitivity

### ISSUE THREAD

**Issue by salesp07** [excalidraw/excalidraw#7763] opened 2024-03-09 08:15 UTC
When using a drawing tablet on excalidraw, the line appears too thick due to pressure sensitivity. I'd love to be able to turn that off.

**Comment by ShonenAsh** [comment] 2024-03-10 06:48
Yep, it's preventing me from using this gold of an application on my iPad.

**Comment by Sciddie** [comment] 2024-04-30 08:48
That function would be nice

**Comment by Mrazator** [comment] 2024-05-07 18:04
Closing as duplicate of #3693.

**Closed by Mrazator** 2024-05-07 18:04 UTC
