### ISSUE TITLE
 I can't select any elements on the canvas

### ISSUE THREAD

**Issue by adominguez** [excalidraw/excalidraw#7879] opened 2024-04-11 11:22 UTC
Hi!! I have several elements on my canvas, texts, images... I am trying to select some of them with the mouse and it won't let me select any.

It is as if none of the mouse buttons work on the canvas. However, I can select from the top command palette and the options button.

If I inspect the chrome console it gives me the following error every time I move or click the mouse on the canvas.

![image](https://github.com/excalidraw/excalidraw/assets/30770867/48ddf083-132e-4a8f-bdbd-97291b551170)

This error does not occur when I move or click with the mouse in the top command palette.

This code is where the error occurs. I don't know if it has anything to do with it, but I'm posting it in case it helps.

![image](https://github.com/excalidraw/excalidraw/assets/30770867/04a4ba45-c25f-4fcf-bc09-1535edef05d0)

Thank you

**Comment by Nicbib** [comment] 2024-04-11 11:27
Hello j'ai le même problème que toi, je ne peux rien sélectionner. Je peux faire des formes sans problème mais je ne peux pas les bouger supprimer / écrire / sélectionner des éléments. Je ne sais pas comment faire pour retrouver la mobilité. Hier tout fonctionnait très bien. Tu as une astuce ?

**Comment by adominguez** [comment] 2024-04-11 11:38
I just checked that if I clean the canvas and start from the beginning I don't have any problems, and also, the errors in the chrome inspector disappear

**Comment by Nicbib** [comment] 2024-04-11 11:39
Yes j'ai pareil que toi si je pars de zéro c'est ok mais pour tous fiches excalidraw uploader ça ne fonctionne pas c'est chiant parce que j'avais tout paramétré

**Comment by adominguez** [comment] 2024-04-11 11:40
> Hello j'ai le même problème que toi, je ne peux rien sélectionner. Je peux faire des formes sans problème mais je ne peux pas les bouger supprimer / écrire / sélectionner des éléments. Je ne sais pas comment faire pour retrouver la mobilité. Hier tout fonctionnait très bien. Tu as une astuce ?


What I'm going to try is to download the canvas in svg and inspect it to see if I see anything strange, but beyond that... no idea.

I imagine it has to be related to the console error that appeared above.

**Comment by Nicbib** [comment] 2024-04-11 11:41
Oui je pense que c'est lié à l'erreur que tu as mentionné ci-dessus. Y a surement du avoir une mise à jour ou un truc comme ça. J'ai essayé de changer de navigateur mais rien n'y fait c'est la même chose.

**Comment by adominguez** [comment] 2024-04-11 11:45
Then I'm going to debug the svg, maybe there may be a poorly closed tag or something...

**Comment by Nicbib** [comment] 2024-04-11 11:50
Je pense que niveau code tu es 100 fois meilleur que moi si tu trouves la solution je suis chaud

**Comment by Nicbib** [comment] 2024-04-11 12:01
J'ai envoyé un mail au support pour voir

**Comment by PabloLigeroIsla** [comment] 2024-04-11 12:08
Same here!

Thanks @Nicbib and @adominguez

**Comment by PabloLigeroIsla** [comment] 2024-04-11 12:53
No @Nicbib . Sorry. I also try to select just groups of elements. But was not possible. 

Another interesting addition,

- This is NOT happening in all of my boards in Excalidraw. Just in some of them.
- If a copy paste all the elements from an old Excalidraw which has the bug to a new one (clean new), the bug is reproduced again. 

I didn't identify the combination of elements that cause the bug.

**Comment by erik-vo** [comment] 2024-04-11 13:25
Same here!

**Comment by Nicbib** [comment] 2024-04-11 13:27
Toujours pas de nouvelles du support quelqu'un à réussi à avancer ?

**Comment by adominguez** [comment] 2024-04-11 13:28
As I see, new commits have been added 3 hours ago, I don't know if there could be a problem in any of those files, perhaps the problem can be narrowed down https://github.com/excalidraw/excalidraw/pull/7876

**Comment by martin-blaus** [comment] 2024-04-11 13:52
Im having the same issue, a null pointer on the p4 since its undefined, can't find the elements in the exported json (.excalidraw) to fix it.

Any solution?  I dont want to lose my work

**Comment by adominguez** [comment] 2024-04-11 14:03
I just started a new canvas, and I've encountered the same problem again when trying to add an object from a library. That might be where the issue lies.

![image](https://github.com/excalidraw/excalidraw/assets/30770867/6a9f310d-88e3-4476-8594-29c485b6cd71)

Perhaps now it's asking for some new property or something specific that these objects don't have, and that might be where the error is coming from.

If I undo (Ctrl + Z) and remove the added element, everything works correctly. So, it must be an issue with the objects being added to the canvas.

**Comment by gitdenison** [comment] 2024-04-11 14:28
Hey guys! I have the same problem. I need to continue work on my screen and it doesn't allow editing. I am desperate! I eagerly await the correction.

**Comment by Fobhep** [comment] 2024-04-11 14:32
I can confirm the observation regarding adding library objects. I think this is triggering the error

**Comment by emanuelelongo** [comment] 2024-04-11 14:34
Same problem

**Comment by PabloLigeroIsla** [comment] 2024-04-11 14:55
Workaround: 

Is posible to open and edit the .excalidraw files with the bug using the Excalidraw Plugin of VSCode. 

https://marketplace.visualstudio.com/items?itemName=pomdtr.excalidraw-editor

I test it and I can select individual elements.

**Comment by Nicbib** [comment] 2024-04-11 14:59
Tu peux m'expliquer le process pour le mettre en place sur Mac ?

**Comment by zaboco** [comment] 2024-04-11 15:00
I have the same issue. I noticed that it happens when I add a closed polygon which doesn't have 3n lines. So 3, 6, 9 is fine; others (4, 5, 8) trigger the error. Don't know if that helps, but it might be a starting point when debugging.

**Comment by Fobhep** [comment] 2024-04-11 15:18
> Tu peux m'expliquer le process pour le mettre en place sur Mac ?

Et pourquoi pas l'anglais ;) C'est Github, les discussions sont généralement en anglais pour que tout le monde comprenne.

**Comment by Fobhep** [comment] 2024-04-11 15:32
Intellij plugin works fine as well - in case somebody is using not vscode:
https://plugins.jetbrains.com/plugin/17096-excalidraw-integration

**Comment by ryan-di** [comment] 2024-04-11 15:59
Thank you all for reporting and following up on the issue ❤️ We're terribly sorry about the inconvenience this has caused. As @adominguez has correctly pointed out, this bug is caused by the recently merged #7636 refactor on geometry. 

Looking into it now! Hope to get back to you soon with a fix!

**Comment by dwelle** [comment] 2024-04-11 16:11
Hi, we've reverted the deployment for now.

**Comment by sanghel-orbyta** [comment] 2024-04-11 16:15
> Hi, we've reverted the deployment for now.

Can confirm, seems to be working now.

I only saw the issue with items from [a specific library](https://libraries.excalidraw.com/?target=_excalidraw&referrer=https%3A%2F%2Fexcalidraw.com%2F&useHash=true&token=K65Xez6LA3P5xEUBXN8vt&theme=light&version=2&sort=default#7demonsrising-azure-network) .
I don't know your architecture, but perhaps the sentry key issue is caused by some libraries only (perhaps those employing analytics in some war...)

**Comment by Nicbib** [comment] 2024-04-11 16:18
Ca remarche chez vous ? Car moi pas du tout

**Comment by Nicbib** [comment] 2024-04-11 16:19
C'est bon ça remarche

**Comment by gitdenison** [comment] 2024-04-11 16:54
Thank you!!!

**Comment by gitdenison** [comment] 2024-04-11 16:55
Thank you, now it's ok!

**Comment by gitdenison** [comment] 2024-04-11 16:56
> Olá, revertemos a implantação por enquanto.

Thank you, now it's ok!!!

**Comment by gitdenison** [comment] 2024-04-11 16:57
> Hi, we've reverted the deployment for now.

Thank you, now it's ok!

**Comment by ryan-di** [comment] 2024-04-11 17:08
For those who are interested/affected, with lines, if the first point and the last point meet, it would form a closed shape.  
![image](https://github.com/excalidraw/excalidraw/assets/47294779/29bb3a02-4021-4c8d-9a0b-612b9bbf9612)

For hit testing, that is to check if the pointer hits a given element, we approximate closed lines with polygons. When the lines are curved/round, we use the package `points-on-curve` to sample points along the curve to form a closed polygon. The functions inside the package therefore assume the given points to meet certain criteria. 

But when the lines are sharp, there's no need to refer to `points-on-curve` and we should just form the polygon directly. And since incorrect points were given to `points-on-curve`, it threw.

There's a fix already but we want to test it more thoroughly before we reintroduce the refactor into the codebase. Again, our apologies!

**Comment by adominguez** [comment] 2024-04-12 07:16
Thank you very much, I just checked and indeed it's working now. 👏🏼👏🏼👏🏼

**Closed** 2024-04-12 10:58 UTC

**Comment by mellamofranco** [comment] 2025-02-13 00:15
I solved it importing al old versión from local file and then ctr z to current state. 
shitty bug tough, feels risky to keep working in complex diagram after facing that.
object block seem to start when ctr + a and the hit lock, never unlocked elements.

**Comment by dwelle** [comment] 2025-02-18 19:30
@mellamofranco if you can still reproduce thus (make sure you're on the latest version or later than 2025-02-13T13:07:44Z, by checking the canvas properties you can open by right-clicking on canvas), then please open a new issue with the error. Thanks!
