### ISSUE TITLE
Should we add info button on bottom left to toggle shortcuts ?

### ISSUE THREAD

**Issue by mbj36** [excalidraw/excalidraw#1251] opened 2020-04-05 22:49 UTC
![Screenshot 2020-04-06 at 4 17 49 AM](https://user-images.githubusercontent.com/9936881/78511870-accf1c00-77bd-11ea-9cd1-f27d0d25314d.png)

Something like this can be added which opens the shortcut modal. 

Currently there is no way on Excalidraw which says Press `?`

**Comment by lipis** [comment] 2020-04-05 23:02
Yeap.. that's the duplicate of #1233.

Simple questionmark would do.

**Closed by lipis** 2020-04-05 23:02 UTC
