### ISSUE TITLE
Ability to toggle the fixed container while editing

### ISSUE THREAD

**Issue by harshsinghatz** [excalidraw/excalidraw#6281] opened 2023-02-25 15:49 UTC
- Sometimes it is annoying that i cannot get rid of the fixed container on the left while adding objects on the canvas
![image](https://user-images.githubusercontent.com/51085015/221366310-f5722998-73c1-4bba-8b2b-16a97b28251d.png)

Solution:
1. Add a toggle button above the container for visibility

**Comment by dwelle** [comment] 2023-02-26 15:26
Hi. Doesn't the zen mode (opts/alt-z) solve this?

**Comment by dwelle** [comment] 2023-02-26 15:29
Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/6257

**Closed by dwelle** 2023-02-26 15:29 UTC

**Comment by harshsinghatz** [comment] 2023-02-26 15:34
@dwelle Thanks, Didn't knew that should've waited before creating a PR. my bad!
