### ISSUE TITLE
Change the copy for collaboration options on mobile when in session

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2933] opened 2021-02-04 21:14 UTC
I was already in a session and wanted to change my name.

![Screenshot_20210204-231241](https://user-images.githubusercontent.com/125676/106955942-9c216680-673e-11eb-9182-d1682aa6ffc4.png)

**Comment by JosiasAurel** [comment] 2021-02-13 04:33
Hey. I want to solve this issue but I don't clearly understand what is meant by the title. Please can it be explained what the issue is ?

**Comment by dwelle** [comment] 2021-02-13 09:12
Actually, this was recently fixed via https://github.com/excalidraw/excalidraw/pull/2994, and we forgot to close this.

**Closed by dwelle** 2021-02-13 09:12 UTC
Labels: good first issue
