### ISSUE TITLE
The current "code" fonts are "ruined"

### ISSUE THREAD

**Issue by AayushSameerShah** [excalidraw/excalidraw#8551] opened 2024-09-26 07:04 UTC
Just have a look at this:
![image](https://github.com/user-attachments/assets/fb66c78f-c9df-4639-9370-d6b3029de7dd)

They are not common-width fonts anymore! It is all misaligned and looks "un-soothing" to the eyes.

Please revert to some consolas or some other `actual code font` for this purpose! 

Thanks

**Comment by DevMhrn** [comment] 2024-09-27 09:50
I would like to work on this issue , please assign it to me

**Comment by AayushSameerShah** [comment] 2024-09-28 08:57
@DevMhrn have it!

**Comment by rudeyak** [comment] 2024-10-06 10:44
Related: https://github.com/excalidraw/excalidraw/issues/8331

**Comment by Mrazator** [comment] 2024-10-06 15:44
Duplicate of #8327

**Closed by Mrazator** 2024-10-06 15:44 UTC
