### ISSUE TITLE
Save file picker is repeatedly not working

### ISSUE THREAD

**Issue by loomsfriendlyghost** [excalidraw/excalidraw#5100] opened 2022-04-26 19:51 UTC
Error message:
`Failed to execute 'showSaveFilePicker' on 'Window': Must be handling a user gesture to show a file picker.`

Browser: Chrome
OS: MacOS Monterrey

**Comment by dwelle** [comment] 2022-04-27 08:35
Exporting image (SVG/PNG) or as excalidraw file (`.excalidraw`)? Does it happen always, or intermittently? What are the exact steps? What's your Chrome version?

Lastly, what's the Excalidraw version? You can check by opening the context menu by clicking on the canvas → show stats for nerds → click on the version to copy to clipboard → paste here.

Thanks!

**Comment by cmheisel** [comment] 2022-04-27 15:59
@dwelle I'm getting the same behavior but different console error on that URL:

`script.mjs:151 DOMException: The request is not allowed by the user agent or the platform in the current context.`

**Comment by dwelle** [comment] 2022-04-27 16:16
Did it start happening only recently (did it work before)? If so, did you make any upgrades (Big Sur → Monterey)?

**Comment by cmheisel** [comment] 2022-04-27 16:28
It did work before, the last time I was using it successfully was in mid-February. When it worked it was working every time, and now that it's stopped it's stopped working every time -- reloading, incognito, different or new files, nothing has made it work.

**Comment by dwelle** [comment] 2022-04-27 17:14
Ok, this is strange. I assume opening a file doesn't work either?

**Comment by cmheisel** [comment] 2022-04-27 23:02
Actually opening an .excalidraw file does work

**Comment by tomayac** [comment] 2022-04-28 08:48
<img width="1258" alt="Screen Shot 2022-04-28 at 10 46 37" src="https://user-images.githubusercontent.com/145676/165714645-78bd1c89-23dd-4e56-97c5-932a4b7e7145.png">

Cannot reproduce either. This is via BrowserStack.

**Comment by tomayac** [comment] 2022-04-28 08:52
Could you open Excalidraw, and then DevTools and paste in the following line:

```js
document.body.addEventListener('click', () => {try { window.showOpenFilePicker() } catch (err) {console.error(err.name, err.message)}})
```

This adds a click listener that upon clicking anywhere in the `body` opens a file open dialog. Does this work?

**Comment by cmheisel** [comment] 2022-04-28 13:21
@tomayac That works, I see an open file picker without any issue.

**Comment by tomayac** [comment] 2022-04-28 14:10
Thanks for running the test. Additional question: is this happening when the scene is very complex? Here is one theory:

1. The user clicks the **Save** button (this is the _user gesture_, which is valid a period of time `Δuser_gesture`).
2. Excalidraw prepares the to-be-saved data, which may take some time `Δprep`.
3. The browser tries to show the file save dialog, but if `Δprep > Δuser_gesture`, the user gesture is no longer good.

In `browser-fs-access`, the library used by Excalidraw under the hood, we now support a new programming model, where the to-be-saved data may be passed as a `Promise<Blob>` as well (apart from a pre-prepared `Blob` and streaming `Response`). 

```js
// `blobOrPromiseBlobOrResponse` is a `Blob`, a `Promise<Blob>`, or a `Response`.
await fileSave(
  blobOrResponseOrPromiseBlob,
  options,
  existingHandle,
  throwIfExistingHandleNotGood
);
```

Before we explore this, it would be helpful to know if this is the problem. Judging from your video (where apparently the data is available immediately), it's not, but I wanted to be sure.

**Comment by dwelle** [comment] 2022-04-28 17:26
@tomayac just in case you missed this, @cmheisel was able to reproduce in the demo as well https://github.com/excalidraw/excalidraw/issues/5100#issuecomment-1111176856. Does the image file you're saving there considered big one?

**Comment by cmheisel** [comment] 2022-04-28 18:16
@tomayac - I'm seeing it happen even with a very simple drawing. See attached example.

![2022-04-28 14 15 49](https://user-images.githubusercontent.com/34786/165820080-7d53bf48-d2e8-4641-bb26-2480c4429fdd.gif)

**Comment by dwelle** [comment] 2022-04-28 19:10
The svg export is "almost" not async (when not embedding it should just be awaiting an empty async function, so it's a microtick away).

And the json export (which doesn't work either) should be completely sync if I'm not mistaken.

@cmheisel to test this, can you run:

```
document.body.addEventListener('click', async () => {
  try {
    await window.showSaveFilePicker()
  } catch (err) {
    console.error(err.name, err.message);
  }
});
```

It should allow you to save an empty file on click. Let us know if that works!

**Comment by cmheisel** [comment] 2022-04-28 21:45
@dwelle 

Nope, when I click I get the following error:

`instrument.ts:129 NotAllowedError The request is not allowed by the user agent or the platform in the current context.`

**Comment by dwelle** [comment] 2022-04-28 22:02
Thank you for confirming!

Though I do wonder, the stack trace is a bit strange (`instrument.ts:129`). Can you actually change the code I posted above to include the error stack trace in full?

```
document.body.addEventListener('click', async () => {
  try {
    await window.showSaveFilePicker()
  } catch (err) {
    console.error(err.stack); // orr console.error(error)
  }
});
```

And then capture a screenshot (or copy the text) of it?

Could it be a browser extension blocking this? Do you have any privacy-related or similar extensions installed?

**Comment by tomayac** [comment] 2022-04-29 07:57
Better yet, can you open [example.com](https://example.com/) in a [guest profile](https://support.google.com/chrome/answer/6130773?hl=en&co=GENIE.Platform%3DDesktop) and paste the snippet. This way we make sure no extensions whatsoever are installed.

**Comment by cmheisel** [comment] 2022-04-30 14:10
@tomayac - 

With **a guest profile on example.com and excalidraw.com I got the save file dialog without issue**. Without a guest profile I tried it on excalidraw.com and example.com I got the same error (screenshot attached)

<img width="540" alt="Screen Shot 2022-04-30 at 10 05 54 AM" src="https://user-images.githubusercontent.com/34786/166108862-aae6d019-fe58-48fe-a0aa-ecbcd288dca3.png">

That made me do some digging and I found the culprit for my setup, I think my company (Chrome is managed) has a policy banning File editing! From the site settings screen for Excalidraw:

<img width="653" alt="Screen Shot 2022-04-30 at 10 07 54 AM" src="https://user-images.githubusercontent.com/34786/166108991-c1ab58ee-03e0-4cf7-b412-aac5c98ef4ee.png">

**Comment by tomayac** [comment] 2022-04-30 14:32
Mystery solved then. 😅 Closing.

**Closed** 2022-04-30 14:32 UTC

**Comment by dwelle** [comment] 2022-04-30 15:39
Should we detect and fall back to legacy? As I understand, the "File Editing" permission only covers the new FS API?

Also the OP from @loomsfriendlyghost seems to be a different issue.

@loomsfriendlyghost if you're still facing the issue, can you go through the same steps? Mainly:

1) go to https://example.com and paste this into the console: (Cmd-opt-I or Ctrl-shift-I on Windows), and click to open file save dialog

```
document.body.addEventListener('click', async () => {
  try {
    await window.showSaveFilePicker()
  } catch (err) {
    console.error(err.stack); // orr console.error(error)
  }
});
```

2) if that works, can you https://googlechromelabs.github.io/browser-fs-access/demo/ and check if saving the image file works?

Thanks

**Comment by tomayac** [comment] 2022-05-02 07:08
> @tomayac should we detect and fall back to legacy? As I understand, the "File Editing" permission only covers the new FS API?

I think it's designed in a way to be non-detectable to avoid it (the managed setting) to become a fingerprinting vector. It will fail at runtime with the error message from above.

I have just released `browser-fs-access` version `0.28.5`, which supports a pattern like in this [demo](https://astonishing-elfin-stranger.glitch.me/):

```js
import { fileOpen } from 'https://unpkg.com/browser-fs-access';

const FAILURE_NOTE = 'Looks like your browser\'s enterprise configuration prohibits access to the File System Access API. Falling back to the legacy approach to opening files.';

const button = document.querySelector('button');
const pre = document.querySelector('pre');

let defensiveFileOpen = fileOpen;

const onButtonClick = async () => {
  try {
    const file = await defensiveFileOpen();
    pre.textContent += `${file.name}\n`;
    console.log(file);
  } catch (err) {
    if (err.name === 'NotAllowedError') {
      pre.textContent += FAILURE_NOTE;
      const { fileOpenLegacy } = await import('https://unpkg.com/browser-fs-access');
      defensiveFileOpen = fileOpenLegacy;
      return onButtonClick();
    }
  } 
};

button.addEventListener('click', onButtonClick); 
```

The confusing part is maybe that it shows the dialog twice.

**Comment by zadam** [comment] 2022-07-29 21:29
Save to PNG/SVG doesn't work on MacOS 12.5 / Electron 19:

> The request is not allowed by the user agent or the platform in the current context.

Interestingly, "Save to disk" works fine. Is there a major difference between the two? 

Excalidraw 0.12.0

**Comment by dwelle** [comment] 2022-07-30 20:47
@zadam I assume it works on excalidraw.com? Probably something to do with Electron, but hard to say what. Can you post the error stack trace?

**Comment by zadam** [comment] 2022-07-30 21:13
It works on excalidraw.com in browser, but not in electron (i.e. I load the excalidraw.com within electron). So yes, it is probably specific to electron. Here's the stacktrace (exlicadraw.com from within electron):

<img width="550" alt="image" src="https://user-images.githubusercontent.com/617641/181996371-f10d4d2c-e518-4bc5-ba2d-0a034f5092ad.png">

**Comment by DennisFaucher** [comment] 2022-10-07 13:40
Interesting, Export file picker works in Safari but not Edge (Chrome) on MacOS. Also, that Chrome download image test also fails in Edge, so it is a Chrome/Edge issue.

**Comment by tomayac** [comment] 2022-10-07 13:44
Any messages in the console? Do you have the exact version numbers of Chrome and the OS at hand? Is it an enterprise policy, as in https://github.com/excalidraw/excalidraw/issues/5100#issuecomment-1113995395?

**Comment by DennisFaucher** [comment] 2022-10-07 14:05
Thanks @tomayac 
Chrome (Edge): Version 105.0.1343.53 (Official build) (arm64) (Mac M1 Mini) 
OS: 12.6 (M1)
No Enterprise Policy blocking file editing
![Screen Shot 2022-10-07 at 10 04 54 AM](https://user-images.githubusercontent.com/9034190/194572504-93a24505-ec6d-4c65-818b-9e511c580703.png)

**Comment by tomayac** [comment] 2022-10-07 14:07
Alright. Console messages?

**Comment by DennisFaucher** [comment] 2022-10-07 14:10
I'm using excalidraw.com but I will try running locally to see console messages

**Comment by DennisFaucher** [comment] 2022-10-07 15:02
I think you meant Chrome Console not OS console. I installed locally anyway, started, clicked "Save to File" and the Chrome (Edge) console gave this error about FilePicker
![Screen Shot 2022-10-07 at 11 00 59 AM](https://user-images.githubusercontent.com/9034190/194585140-661ee1c8-fee3-4010-ba7b-4418587a0e87.png)

**Comment by tomayac** [comment] 2022-10-07 15:12
Yes, I was talking about the DevTools console indeed. Could you try the steps outlined in https://github.com/excalidraw/excalidraw/issues/5100#issuecomment-1114008081 and report here, please?

**Comment by tomayac** [comment] 2022-10-07 15:15
FWIW, doesn't reproduce locally, nor on BrowserStack: `https://live.browserstack.com/dashboard#os=OS+X&os_version=Monterey&browser=Chrome&browser_version=105.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fexcalidraw.com%2F&speed=1`

**Comment by DennisFaucher** [comment] 2022-10-07 15:22
example.com with the console code does not present a File Save dialog. Maybe I am doing something wrong.
![Screen Shot 2022-10-07 at 11 21 34 AM](https://user-images.githubusercontent.com/9034190/194590199-84bb3e98-a141-482b-ab02-e84f30ae8f65.png)

**Comment by tomayac** [comment] 2022-10-07 15:23
(At the risk of pointing out the obvious: did you click somewhere in the page?)

**Comment by DennisFaucher** [comment] 2022-10-07 15:24
Yes, the only hot item is the "More information..."

**Comment by DennisFaucher** [comment] 2022-10-07 15:24
If this works for everyone else, I can just not use Chrome/Edge for Excelidraw

**Comment by tomayac** [comment] 2022-10-07 15:26
Can you open a guest profile in Chrome and try again? A guest profile has no extensions whatsoever installed.

**Comment by DennisFaucher** [comment] 2022-10-07 15:42
Edge InPrivate window did not respond to clicks after adding console code
![Screen Shot 2022-10-07 at 11 41 50 AM](https://user-images.githubusercontent.com/9034190/194593917-2d3483bd-8292-476f-9af0-d3f42f636efd.png)

**Comment by tomayac** [comment] 2022-10-07 15:48
Extensions can still be configured to run in private/incognito mode. Maybe actually try running in a guest profile. And again, just to make sure: you're clicking the page, not the DevTools area. right!?

**Comment by DennisFaucher** [comment] 2022-10-07 15:50
Oh, it is Brave. Chrome works out of the box. Version 106.0.5249.103 (Official Build) (arm64)
![Screen Shot 2022-10-07 at 11 50 24 AM](https://user-images.githubusercontent.com/9034190/194595599-86549424-aa60-4b1b-84c0-303d7935c917.png)

**Comment by DennisFaucher** [comment] 2022-10-07 15:55
Guest mode is also not working but the console is telling me this which I will look into:

Tracking Prevention blocked access to storage for https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j98&tid=UA-387204-13&cid=494702610.1665157883&jid=286577239&gjid=959989043&_gid=590909874.1665157883&_u=SACAAUABAAAAACAAI~&z=1142065368.

**Comment by DennisFaucher** [comment] 2022-10-07 15:56
Guest mode is also not working but the console is telling me this which I will look into

Tracking Prevention blocked access to storage for https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j98&tid=UA-387204-13&cid=494702610.1665157883&jid=286577239&gjid=959989043&_gid=590909874.1665157883&_u=SACAAUABAAAAACAAI~&z=1142065368.

**Comment by tomayac** [comment] 2022-10-07 15:57
*Sigh*. Yes, Brave has decided to not expose this API: https://github.com/brave/brave-browser/issues/11407. You could have saved us some time by telling us you were using Brave, not Edge or Chrome.

**Comment by DennisFaucher** [comment] 2022-10-07 16:02
Guest mode is also not working but the console is telling me this which I will look into

Tracking Prevention blocked access to storage for https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j98&tid=UA-387204-13&cid=494702610.1665157883&jid=286577239&gjid=959989043&_gid=590909874.1665157883&_u=SACAAUABAAAAACAAI~&z=1142065368.

**Comment by DennisFaucher** [comment] 2022-10-07 16:03
> _Sigh_. Yes, Brave has decided to not expose this API: [brave/brave-browser#11407](https://github.com/brave/brave-browser/issues/11407). You could have saved us some time by telling us you were using Brave, not Edge or Chrome.

I mistyped and fixed. Edge, not Brave. Sorry about that.

**Comment by tomayac** [comment] 2022-10-07 16:24
In this case, it seems like the Edge team needs to take care of this. You can send them feedback:

![Screenshot 2022-10-07 at 18 24 03](https://user-images.githubusercontent.com/145676/194601694-af8827fd-fbcf-40d3-9406-e2db3eaeeca8.png)

**Comment by DennisFaucher** [comment] 2022-10-07 16:55
Fair enough

**Comment by kdivringi** [comment] 2023-01-31 21:55
Installing it as a chrome app first makes it work for me.

**Comment by TrumanDu** [comment] 2023-11-15 07:54
if u have this issue,u can try:
`app.commandLine.appendSwitch('enable-experimental-web-platform-features');`

**Comment by AdnanCukur** [comment] 2023-12-18 10:16
I'm getting the same issue with error

`Failed to execute 'showSaveFilePicker' on 'Window': Must be handling a user gesture to show a file picker.`

Scale 1x, it works, Scale 3x it seems to be "processing" for a couple seconds and then the error window pops up, my guess is that it takes too long to process because of big drawing so chrome doesnt associate the click with the download file event. 

A solution might be to basically just show a "Processing bar" or spinning wheel while its processing and when its done display a download button, similar to how other sites that process images do it.

Windows 11, Chrome Version 120.0.6099.72, tried in incognito, guest mode, company profile, private profile, same issue.

**Comment by TBG-FR** [comment] 2024-01-02 18:25
Happens to me everytime on https://excalidraw.com/ when trying to export a large schema to PNG
- x1 scale => no issue
- x2 scale => no issue
- x3 scale => `Failed to execute 'showSaveFilePicker' on 'Window': Must be handling a user gesture to show a file picker.`

```
DOMException: Failed to execute 'showSaveFilePicker' on 'Window': Must be handling a user gesture to show a file picker.
    at Module.y (https://excalidraw.com/assets/file-save-745eba88-h9NxcJsg.js:1:525)
    at pU (https://excalidraw.com/assets/index-pzqFbuE1.js:119:11238)
    at async rm (https://excalidraw.com/assets/index-pzqFbuE1.js:145:101481)
    at async https://excalidraw.com/assets/index-pzqFbuE1.js:191:7327
```

**Comment by AdnanCukur** [comment] 2024-01-05 09:03
> Happens to me everytime on https://excalidraw.com/ when trying to export a large schema to PNG (using Google Chrome, or the app installed through Google Chrome)
> 
> * x1 scale => no issue
> * x2 scale => no issue
> * x3 scale => `Failed to execute 'showSaveFilePicker' on 'Window': Must be handling a user gesture to show a file picker.`
> 
> ```
> DOMException: Failed to execute 'showSaveFilePicker' on 'Window': Must be handling a user gesture to show a file picker.
>     at Module.y (https://excalidraw.com/assets/file-save-745eba88-h9NxcJsg.js:1:525)
>     at pU (https://excalidraw.com/assets/index-pzqFbuE1.js:119:11238)
>     at async rm (https://excalidraw.com/assets/index-pzqFbuE1.js:145:101481)
>     at async https://excalidraw.com/assets/index-pzqFbuE1.js:191:7327
> ```

I created a new issue for this a few weeks ago since the bug seems to be different

https://github.com/excalidraw/excalidraw/issues/7456

**Comment by tomayac** [comment] 2024-01-08 09:29
I just commented on a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1516572#c1) where someone was running into a seemingly similar problem.
