### ISSUE TITLE
Canvas was just deleted randomly, open option fails

### ISSUE THREAD

**Issue by aHagouel** [excalidraw/excalidraw#2148] opened 2020-09-09 19:05 UTC
Hi! I was on my canvas and my work seems to have been deleted after I hit ctrl+z. It just went to a completely blank screen. Afterwards I tried to open an older, local version I had saved and got the following error:

![image](https://user-images.githubusercontent.com/9829937/92642186-affe9480-f294-11ea-85af-ff5c623f2e98.png)

**Comment by dwelle** [comment] 2020-09-09 19:07
That Ctrl-Z thing should be solved via this PR https://github.com/excalidraw/excalidraw/pull/2115 which I should have merged already. Sorry for the trouble it caused :(.

**Comment by dwelle** [comment] 2020-09-09 19:12
Can't repro the `showSaveFilePicker` error. @tomayac any ideas?

**Comment by aHagouel** [comment] 2020-09-09 19:14
@dwelle great to hear that the ctrl+z thing may be fixed. I'm at the stage where I'm really scared I lost all of my work now... how might I recover it?

**Comment by tomayac** [comment] 2020-09-09 19:32
The API surface has changed. Now we need to pass file extensions with a leading dot (`.excalidraw` instead of `excalidraw`). I’ll have a look tomorrow, it’s late here.

**Comment by dwelle** [comment] 2020-09-09 19:36
> @dwelle great to hear that the ctrl+z thing may be fixed. I'm at the stage where I'm really scared I lost all of my work now... how might I recover it?

If you have it saved in a file (at least some version of it) as you mentioned, but just can't import it at the moment due to the bug, then it'll be fixed and you will be able to restore it. But you won't be able to restore the unsaved work I'm afraid :(.

> The API surface has changed. Now we need to pass file extensions with a leading dot (`.excalidraw` instead of `excalidraw`). I’ll have a look tomorrow, it’s late here.

Yup, np.

**Comment by aHagouel** [comment] 2020-09-09 20:37
kasdfb;asd;flknasdf;lk.... I should have saved wayyyyy earlier. Thx for looking in to this. Btw confirmed the open / save is ok in chrome, I was just using a beta version of edge.

**Comment by dwelle** [comment] 2020-09-10 08:20
@tomayac I can confirm on Edge 87.0.635.0 (canary) --- simply clicking on the open-file button throws.

@aHagouel sorry again :(

**Closed** 2020-09-10 10:00 UTC
Labels: bug
