### ISSUE TITLE
Bug: Sticky notes reset font size while resizing

### ISSUE THREAD

**Issue by 7flash** [excalidraw/excalidraw#5916] opened 2022-11-22 11:14 UTC
It appears them to respect the chosen "medium/small" font option rather than actual font size

**Comment by dwelle** [comment] 2022-11-22 11:18
Can you post steps to repro?

I can reproduce a regression when resizing using `shift` — is that what you meant?

**Comment by 7flash** [comment] 2022-11-23 09:10
![eleven23-first](https://user-images.githubusercontent.com/4569866/203508171-95d075d5-396c-411e-9f93-fe70a28c4a8a.gif)

to reproduce, create sticky note with font size of (3000px) then hold shift and left click on corner point; expected nothing to happen and allow me to downsize it; instead it multiplies font size until overflow

**Comment by 7flash** [comment] 2022-11-23 09:17
happens with smaller font size (23px) too when have padding
![eleven23-third](https://user-images.githubusercontent.com/4569866/203509718-f311961e-94b6-4e61-adb4-05dbcdd1d01e.gif)

**Comment by dwelle** [comment] 2022-11-23 11:15
Got it. All of that seems to be related to this regression: https://github.com/excalidraw/excalidraw/pull/5710 /cc @ad1992 

Can you check if it works properly for you here? https://excalidraw-oia7z37wn-excalidraw.vercel.app/

**Comment by dwelle** [comment] 2022-11-23 11:19
Closing in favor of https://github.com/excalidraw/excalidraw/issues/5842

**Closed by dwelle** 2022-11-23 11:19 UTC
Labels: bug, Binding text / Sticky note
