### ISSUE TITLE
Cannot save or save as from Chrome v86 macOS

### ISSUE THREAD

**Issue by joshuaiz** [excalidraw/excalidraw#2154] opened 2020-09-11 20:16 UTC
Just tried saving a file in Chrome Version 86.0.4240.30 (Official Build) beta (x86_64) on macOS using both 'Save' and 'Save As' and the operation times out with this error:

![CleanShot 2020-09-11 at 15 10 34@2x](https://user-images.githubusercontent.com/1096738/92968780-5a1b1f80-f441-11ea-8d69-e65681156ecc.jpg)

Also tried with new file in Incognito window and same error:

![CleanShot 2020-09-11 at 15 15 19@2x](https://user-images.githubusercontent.com/1096738/92968996-aebe9a80-f441-11ea-9fc4-c30332ab99b5.jpg)

Tried in latest Chrome Canary and was able to save using that but not in regular Chrome.

**Comment by tomayac** [comment] 2020-09-11 20:33
Temporarily fixed via https://github.com/excalidraw/excalidraw/pull/2155.

**Comment by dwelle** [comment] 2020-09-11 20:34
What's this one caused by? I'm on stable 85, and canary on 87 so can't test. Will try to test on beta channel.

**Comment by tomayac** [comment] 2020-09-11 20:37
I have not seen this error before. Let’s disable the OT for now just to be on the safe side via #2155.

**Comment by dwelle** [comment] 2020-09-11 20:38
Done. I've tested on 86 (Beta channel) and still can't repro the OP. Maybe it's Mac-only.

**Comment by joshuaiz** [comment] 2020-09-11 22:34
@dwelle here's the value (after refresh):

6ea9f2dde46453a6c1cbf073dc8e42bfbbc05d8e

**Comment by joshuaiz** [comment] 2020-09-11 22:38
Can save now...thanks for the quick fix.

**Comment by tomayac** [comment] 2020-09-14 07:07
I'm closing this issue in favor of the newly created Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1127773. Please star it to be notified of changes.

**Closed by tomayac** 2020-09-14 07:07 UTC
Labels: bug

**Comment by tomayac** [comment] 2020-09-15 06:50
To the initial poster @joshuaiz: Could you chime in on the [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1127773#c2), please? Not sure if you have seen it. Thank you!

**Comment by joshuaiz** [comment] 2020-09-15 19:21
@tomayac Yep I've seen it - go ahead and close this out. Thanks!
