### ISSUE TITLE
Wrapped text is not correctly centered in boxes

### ISSUE THREAD

**Issue by olance** [excalidraw/excalidraw#4997] opened 2022-03-30 22:17 UTC
When a text goes multiline automatically because of its length, the centering algorithm keeps the trailing whitespaces in its calculation of each line width.  
As a result, lines that end with a space because the next word was wrapped are shifted to the left.

You can see in the example below the same boxes with almost identical texts:
- Left one is the uninterrupted sentence "Some text that will wrap automatically"
- Right one is "Some text that`\r`will wrap`\r`automatically"

You can see that the text is correctly centered only in the second instance:
![image](https://user-images.githubusercontent.com/314079/160939905-c9bc0c55-1627-439c-800a-0deddf81118c.png)

<small>(pixel measurements are indicative, just used the screenshot tool on macOS at 100% zoom on Excalidraw)</small>

Depending on the text, it can have more "dramatic" effect; here the left box text looks achored to the right:
![image](https://user-images.githubusercontent.com/314079/160940271-ebf8aa2b-cfab-4899-a762-869826be01a7.png)

**Comment by ad1992** [comment] 2022-12-20 09:08
@olance apologies for the delayed reply. 
Do you mean that when you edit the sentence, the "whitespace" is removed and once you stop editing it's added back?

**Comment by dwelle** [comment] 2022-12-20 09:36
I think it's about the trailing whitespace acting as a visible character when centering/wrapping the text:

![excal-whitespace-wrapping-centering-issue](https://user-images.githubusercontent.com/5153846/208633807-124cb87e-2dd1-448f-a59e-9f3efa31668c.gif)

**Comment by ad1992** [comment] 2022-12-20 09:47
Yeah but thats coz the css needs that whitespace (If you edit you will see the whitespace as well so there will be no mismatch) , if I remove it then there will be slight displacement eg trying the the same in Miro has this displacement




https://user-images.githubusercontent.com/11256141/208636123-0638f598-988d-45a2-b36d-0aefa50ed1e8.mp4

**Comment by dwelle** [comment] 2022-12-20 12:37
Yeah, I have no idea. But tldraw and eraser don't seem to have that issue, so it must be doable. But, let's leave this as a bonus once the wrapping algo is super solid, as trying to fix this now would ndoubtedly break some other thing elsewhere.

**Comment by ad1992** [comment] 2022-12-21 07:49
In eraser, I can still see the same issue of not being correctly centered

<img width="180" alt="Screenshot 2022-12-21 at 1 10 32 PM" src="https://user-images.githubusercontent.com/11256141/208849013-c1c3f937-2ca7-449e-b406-518aa02e22a0.png">

I will check on we can improve this.

**Comment by dwelle** [comment] 2022-12-21 08:42
You're right that both tldraw and eraser have the centering issue (including whitespace). What caught my attention was the absence of the jump once the whitespace wraps on new line in our implem (as [shown above](https://github.com/excalidraw/excalidraw/issues/4997#issuecomment-1359077361)).

![eraser-text-wrapping-whitespace](https://user-images.githubusercontent.com/5153846/208859573-1625c454-c92a-4493-9fd7-f6ed9b23d82c.gif)

**Comment by ignacio-cuadra** [comment] 2023-01-24 02:06
I'm working on a refactor so I think it's a good idea to ask.

the technical limitation is the behavior of the textarea (because it's used when editing), right?

the textarea uses something like "overflow: hidden" with last spaces of a line. 

![Merchant Account](https://user-images.githubusercontent.com/67276174/214198220-ac8353b2-fa73-488b-a65d-1b06b41602c2.gif)


Maybe that is expected behavior, no?

**Comment by olance** [comment] 2023-01-24 09:04
Hi all, sorry for replying only now.

@dwelle is right in the interpretation of my issue/concern: IMHO, a box that is configured to have centered text should show the _visible_ text perfectly centered.

In my example of "merchant account" it looks really off as if I had mistakenly set it to right aligned.

To me the final appearance will be more important than a potential jump when switching to edit mode. But that's of course one single opinion on the matter.

**Comment by dwelle** [comment] 2023-01-24 21:51
@olance I understand where you're coming from, and neither solution (jumping text when entering the editor vs not centering outside of the editor) is good, but let's first implement the standard behavior and decide later whether we want break off from it (by stripping trailing whitespaces before aligning).

In other words what @ignacio-cuadra is saying.

**Comment by Mrazator** [comment] 2024-10-22 12:09
We recently rewrote text wrapping to preserve all whitespace (https://github.com/excalidraw/excalidraw/issues/8408), hence this issue should be fixed as of now.

**Closed by Mrazator** 2024-10-22 12:09 UTC
Labels: bug, Text containers

**Comment by olance** [comment] 2024-10-28 15:58
Indeed @Mrazator!
It behaves perfectly well now, both in aligning and when editing without a jump.

Thanks for the follow-up :)
