### ISSUE TITLE
saving to image file-handle overwrites with JSON

### ISSUE THREAD

**Issue by tonyxiao** [excalidraw/excalidraw#3402] opened 2021-04-05 14:19 UTC
PNG with scene embeds is an ideal way to store excalidraw file because it can be both previewed (in the finder, or anywhere else) or opened with excalidraw to view the source. The problem comes from opening a png file, then hitting `cmd+s` to save. This will overwrite the PNG file with a json correspond to the excalidraw, as oppose to saving a PNG with excalidraw file embedded inside. 

The right behavior after opening a png file and saving it back should be to save the png with the embedded scene data, rather than saving a json and overwriting the original PNG with json content (which results in an invalid png file anyways)

**Comment by tonyxiao** [comment] 2021-04-05 14:20
Related issue https://github.com/excalidraw/excalidraw/issues/3382

**Comment by dwelle** [comment] 2021-04-05 14:30
> This will overwrite the PNG file with a json correspond to the excalidraw, as oppose to saving a PNG with excalidraw file embedded inside.

Are you sure the current behavior is it overwrites the PNG file with JSON? This was reported and fixed https://github.com/excalidraw/excalidraw/issues/2250 and I can't repro: it prompts me for a file location.

The feature request itself is a duplicate of https://github.com/excalidraw/excalidraw/issues/2261 though

**Comment by dwelle** [comment] 2021-04-05 14:34
Reading the source the fix was actually reverted. But I don't understand why I can't repro then :thinking:

**Comment by dwelle** [comment] 2021-04-05 14:37
Ok, got it. There's a different code path for drag&drop and file-open.

**Closed** 2021-04-06 19:27 UTC
Labels: bug

**Comment by tonyxiao** [comment] 2021-04-07 15:41
So the fix is to prompt user to "save as"? Or is it to write back to the PNG with embedded json scene?

**Comment by dwelle** [comment] 2021-04-07 15:56
To prompt, so that we don't override the png for now. Re-exporting the PNG is tracked in https://github.com/excalidraw/excalidraw/issues/2261
