### ISSUE TITLE
Links to files and folders don't work

### ISSUE THREAD

**Issue by sojusnik** [excalidraw/excalidraw#7607] opened 2024-01-25 21:14 UTC
When working on a local Excalidraw file in Brave as PWA on Ubuntu 23.10, I sometimes tend to link text to files or folders on my hard drive for reference, but when clicking on those links, the currently opened instance of Excalidraw just gets reloaded.

Is it technically possible to implement that when clicking on links to local files and folders, those are opened with the apps configured by the OS?

**Comment by CobaltMongoose** [comment] 2024-05-16 17:58
I have the same problem.
Control + dragging a folder or file from a local location into Excalidraw does not create a clickable text link.
Given that I can still click the tiny box icon inside the Excalidraw view to get the link to work and that web links and internal note links work as intended I suspect this is a bug.
![LocalLinking](https://github.com/excalidraw/excalidraw/assets/34733276/23167322-3bc2-4be2-a501-44dda036f1d7)

**Comment by dwelle** [comment] 2024-05-16 22:04
@sojusnik I'm not sure if this is something that PWA supports.

@CobaltMongoose is this Obsidian?

**Comment by CobaltMongoose** [comment] 2024-05-16 23:43
@dwelle Yes, for me this is in Obsidian on a local install.
Versions: Obsidian 1.5.12 Desktop and Excalidraw community plugin 2.1.8

**Comment by dwelle** [comment] 2024-05-17 16:36
> Is it technically possible to implement that when clicking on links to local files and folders, those are opened with the apps configured by the OS?

@sojusnik double-checked, and not possible :(

Alright, closing as not actionable for this repo.

**Closed by dwelle** 2024-05-17 16:36 UTC
