### ISSUE TITLE
Can't clear canvas

### ISSUE THREAD

**Issue by stephenturner** [excalidraw/excalidraw#8902] opened 2024-12-09 16:57 UTC
I've been using Excalidraw for a few weeks now. First time I've encountered this. When I try to clear my canvas, I cannot. 

![Image](https://github.com/user-attachments/assets/173959e2-bdec-4680-8b27-568f02748556)

![Image](https://github.com/user-attachments/assets/eeafd9b9-0f8b-48b9-8a72-4620b8a7dd51)

I get this:

![Image](https://github.com/user-attachments/assets/58dd44e1-1c74-48af-b1b8-e31b80db9d66)

Same thing happens when I try to reset my library.

**Comment by jsjoeio** [comment] 2024-12-09 17:14
I have the same issue. One interesting observation is it doesn't happen if the tab is in a new window

![Image](https://github.com/user-attachments/assets/ba745579-1834-481f-8d89-7812e9774a46)

but it does happen if it's a tab in a window where I previously had it open

![Image](https://github.com/user-attachments/assets/d012c6e5-1a8c-4ef3-b8a3-3129e79cd683)

**Comment by Mrazator** [comment] 2024-12-09 20:45
Duplicate of #8840

Will be fixed soonish with https://github.com/excalidraw/excalidraw/pull/8901!

**Closed by Mrazator** 2024-12-09 20:45 UTC
