### ISSUE TITLE
pinch zooming in safari broken

### ISSUE THREAD

**Issue by jhoogeboom** [excalidraw/excalidraw#2389] opened 2020-11-18 12:49 UTC
Hi all, a heads up, since a somewhat recent update it looks like pinch zooming has broken on safari.

Whenever I pinch zoom in safari, the drawing disappears, the scroll back to content button appears, but clicking it does not take me back to the content. Zooming in and out manually with the buttons also does not seems to take me back to the drawing. When I refresh, I see my drawing again.

On another note, beyond a certain window size safari performance drops so drastically a single square on the drawing and trying to pan takes multiple seconds for a frame to draw.

**Comment by lipis** [comment] 2020-11-18 12:50
It seems that's a duplicate of #2347

**Closed** 2020-11-18 16:39 UTC
Labels: duplicate
