### ISSUE TITLE
Please support Chinese handwritten fonts

### ISSUE THREAD

**Issue by mining-id** [excalidraw/excalidraw#5259] opened 2022-06-01 01:34 UTC
Currently it is mechanical Chinese and hand-drawn wireframe, which looks very discordant

Please support Chinese handwritten fonts

[https://github.com/lxgw/kose-font](https://github.com/lxgw/kose-font)

This font is free and fully supported, hope it can be considered

<img width="527" alt="image" src="https://user-images.githubusercontent.com/94845005/171310270-d58b74fd-2fa3-4621-8299-8a7d44f9e810.png">

Thank you very much!

----------
The author has more free fonts:
https://lxgw.github.io/2021/01/15/Lxgw-Opensource-Chinese-Fonts/

Specific ideas come from this blog:
https://www.ixiqin.com/2022/04/03/for-excalidraw-add-chinese-handwriting/

**Comment by hulkbig** [comment] 2024-03-19 16:11
@mining-id hi, you can try my fork version: [https://excalidraw-zh.com/](https://excalidraw-zh.com/)

**Comment by hausen1012** [comment] 2024-05-10 07:57
> 嗨，你可以试试我的分叉版本：https://excalidraw-zh.com/

请问你这个仓库打包docker怎么报错呢

**Comment by hulkbig** [comment] 2024-05-17 15:41
> > 嗨，你可以试试我的分叉版本：https://excalidraw-zh.com/
> 
> 请问你这个仓库打包docker怎么报错呢

哈喽，打包脚本是怎样的？可以贴出来我来看看哈

**Comment by dwelle** [comment] 2024-05-18 12:16
We are looking into extending fonts, part of which would be support for CJK fonts. But there are many things to figure out, so will take some time.

**Comment by Mrazator** [comment] 2024-10-16 19:46
We will be releasing support for the whole CJK soon-ish! (https://github.com/excalidraw/excalidraw/pull/8530)

Feel free to give us early feedback, preview is available here:
https://excalidraw-git-mrazator-first-class-support-chinese-excalidraw.vercel.app/

Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/8408

**Closed by Mrazator** 2024-10-16 19:46 UTC
Labels: font
