### ISSUE TITLE
Content disappears without any way to roll back

### ISSUE THREAD

**Issue by edgarasben** [excalidraw/excalidraw#2347] opened 2020-11-06 12:13 UTC
The content disappeared just after drawing few things on a blank canvas today. The button "Scroll back to content" appeared but not functional. I've tried to find content on the canvas but it was completely gone.

I could replicate this twice on **Safari 14.0**. On other browsers it seems to work fine.

**Comment by dwelle** [comment] 2020-11-06 12:32
Likely due to a missed migration. Could you post the scene if not private?

**Comment by edgarasben** [comment] 2020-11-08 15:49
> Could you post the scene if not private? Not sure if you will be able to save it though.

Sure, here is the link: https://excalidraw.com/#room=eb51f2b2343df04afc08,-B1Esng3z_NFjdAKIApjJA

I could reproduce it again. It seems to happen when I start zooming in/out.

**Comment by edgarasben** [comment] 2020-11-08 15:50
It happens every time I zoom, everything disappears and I cannot draw after that. The initial content shows up again after page reload.

**Comment by lipis** [comment] 2020-11-08 16:02
Works fine for me on Safari 14.0.. can't repro! Added more elements, deleted, zoom in, zoom out.. refresh, scroll to content, everything worked! Very strange

**Comment by dwelle** [comment] 2020-11-08 16:05
@edgarasben can you open the console (`F12`) and paste `__EXCALIDRAW_SHA__` into it and copy/paste the value here please?

**Comment by dwelle** [comment] 2020-11-08 16:53
I manually checked the scene JSON (before `restore()`) and it looks fine.

If it happens during zoom that would suggest it may be related to recent change of `appState.zoom` schema. Not sure what the failure mode would be though even if you were on an older version.

**Comment by edgarasben** [comment] 2020-11-08 21:29
@dwelle sure: `22a6ae77cda277ce5313ca2048fcb19783f5c99d`

Also the console is flooding with "Failed to load resource: the server responded with a status of 400 (Bad Request)" 
`https://excalidraw-socket.herokuapp.com/socket.io/?EIO=4&transport=polling&t=NMfmtji`

**Comment by dwelle** [comment] 2020-11-08 22:23
> Also the console is flooding with "Failed to load resource: the server responded with a status of 400 (Bad Request)"
> `https://excalidraw-socket.herokuapp.com/socket.io/?EIO=4&transport=polling&t=NMfmtji`

That one is unrelated, and now fixed (https://github.com/excalidraw/excalidraw/issues/2362).

I'll follow up on this issue tomorrow.

**Comment by Rulikkk** [comment] 2020-11-12 16:43
+1 have the same issue.

Steps to reproduce:
1. Open excalidraw; draw anything, can even be one line.
**2. Zoom in/out using pinch-to-zoom (two finger gesture on trackpad)**

Result: content disappears, "scroll back to content" does not work, the only way to bring everything back is to reload the page. 

Note: the content is still there (just not visible), so if you save/load it — it's back, too.

Safari version:
<img width="396" alt="image" src="https://user-images.githubusercontent.com/2227358/98968634-f7b4cd00-251e-11eb-8532-1629dd6fb11e.png">

**Comment by dwelle** [comment] 2020-11-12 17:18
Can someone on Mac please repro and help debug this? @lipis @ad1992

**Comment by ad1992** [comment] 2020-11-28 16:05
I am able to reproduce this, will take a look at it.

**Comment by ad1992** [comment] 2020-11-28 21:51
@edgarasben @Rulikkk can you confirm if the zoom in /out works for you in https://excalidraw-git-aakansha-zoom.excalidraw.now.sh/ ?

**Closed** 2020-11-30 00:30 UTC
Labels: bug, safari
