### ISSUE TITLE
Default font for text elements

### ISSUE THREAD

**Issue by antoinegag** [excalidraw/excalidraw#513] opened 2020-01-22 15:41 UTC
It would be interesting to be able to pick a default font that will always be used when creating new text elements.

For example if you want your whole drawing to use the `Code` font, you have to either do it all in "Hand-Drawn" and then change every text element with the select tool or change it for every text element you add, being able to have a selected font by default would make this process much better IMO.

I'm not sure if there's already a mechanism in place to handle global defaults but if so I would be willing to try to add this feature if it's something you feel has a place in excalidraw. 😃

**Comment by vjeux** [comment] 2020-01-22 15:54
We already have a way to remember the stroke and background colors. We need to extend it to all the properties. A PR would be welcome!

**Comment by dwelle** [comment] 2020-01-22 16:33
Related (and potentially duplicate of) https://github.com/excalidraw/excalidraw/issues/481.

**Comment by antoinegag** [comment] 2020-01-22 16:59
Looks like it yes, sorry I missed that one! Was looking through issues with the "enhancement" label 😅

**Comment by dwelle** [comment] 2020-01-22 17:01
@antoinegag  No prob. That issue also isn't named very well.

**Closed** 2020-01-22 17:01 UTC

**Comment by lipis** [comment] 2020-01-22 17:03
@dwelle Let's rename it to something more meaningful.
