### ISSUE TITLE
Saving in Linux (ubuntu) creates a new file instead of overwriting an existing file.

### ISSUE THREAD

**Issue by AayushSameerShah** [excalidraw/excalidraw#6842] opened 2023-08-01 17:41 UTC
I have been working **on windows** where suppose for the first time if I save the drawing, with `file-1.excalidraw` then it saves in the destination folder say **downloads**.

## 🤔 What is desired?
Now, I am constantly making the changes and when I save the changes, **it simply overwrites the existing** file `file-1.excalidraw`. Which is desired.

## 👀 What is happening?
I am trying in **ubuntu** where if I save the changes, it **creates a new file** `file-1(1).excalidraw` and on the second save, it does the same `file-1(2).excalidraw`. *(using firefox - haven't tested on chrome in Linux)*

Now, I am not sure if this is the problem with linux or what.
Please fix, this is annoying.

**Comment by ad1992** [comment] 2023-08-02 03:31
@arnostpleskot @are since you are on linux could one of you confirm this ?

**Comment by arnostpleskot** [comment] 2023-08-02 06:49
Hey, @ad1992 ! I've tried it, and it behaves in the described way when using Firefox. Chromium opens the native file select dialog.

Imho, this happens because Firefox has only partial support of the File System Access API that doesn't include saving files; therefore, it treats saved files the same way as regular downloads. This behavior should be the same on every OS when using a Firefox-based browser, but I can't confirm that atm.

**Comment by ad1992** [comment] 2023-08-03 03:02
@arnostpleskot yes thats expected since in firefox File System Access API isn't supported.
@AayushSameerShah I see you have updated the desc of the issue mentioning its happening on firefox so thats expected behaviour hence closing this issue.

**Closed by ad1992** 2023-08-03 03:02 UTC
Labels: Linux
