### ISSUE TITLE
Text gets misaligned when (and after) editing a sticky note

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#5789] opened 2022-10-25 11:09 UTC
https://user-images.githubusercontent.com/14358394/197757783-01e59b3c-deef-4901-a493-4166a5fd844a.mp4

**Comment by ad1992** [comment] 2022-10-27 06:41
@zsviczian can you share a link with the above reproducible example? 
I am making some fixes to the sticky note in https://github.com/excalidraw/excalidraw/pull/5723 which I might decouple so will fix this along.

**Comment by zsviczian** [comment] 2022-10-27 07:42
https://excalidraw.com/#room=9df57bd225eda40dd006,GWt0m2z0AWLEmK9tubXpzQ

**Comment by DanielJGeiger** [comment] 2022-11-05 16:46
@zsviczian @ad1992 While resolving some MathJax-specific sticky-note quirks, I happened to fix this issue as well.  My fix works for text in general (Wysiwyg or not).  See https://excalidraw-git-fork-danieljgeiger-asciimath-mode-excalidraw.vercel.app/#room=9df57bd225eda40dd006,GWt0m2z0AWLEmK9tubXpzQ for a working example.  What could we do to align the two fixes?

**Comment by zsviczian** [comment] 2022-11-05 17:27
@DanielJGeiger there is another sticky note formatting bug (#5834). I just tested it with your preview. Unfortunately, this new bug is not (yet) resolved by your fix.

To align fixes, it would probably be best if you opened a PR for the main product with your proposed fix.

**Comment by DanielJGeiger** [comment] 2022-11-05 21:42
@zsviczian @ad1992 I opened #5835 with the fix I propose for #5789.  Could one of you check it out?

(My fix touches several files since it additionally relaxes the Wysiwyg assumption.)

**Comment by ad1992** [comment] 2022-11-07 08:46
@DanielJGeiger calling `measureText` on every keystroke could significantly affect the perf.
I am working on some refactorings for sticky notes so that the position/alignment no more depends on text coordinates and can be determined from the container element during rendering instead similar to how it is done in #5723 for arrow/lines, I will push the fixes for bound containers so with that hopefully all position/alignment related issues should get fixed completely.

**Comment by ad1992** [comment] 2022-12-21 07:09
@DanielJGeiger @zsviczian could you please share a shareable link with the reproducible example? 
The above link was a collab link that looks like already been modified.
I have pushed some fixes so want to check if this got fixed or is still reproducible

**Comment by DanielJGeiger** [comment] 2022-12-23 23:59
@ad1992 Your fixes seem to have resolved this issue, both on [excalidraw.com](https://excalidraw.com) and in #2993.  But #5834 remains, likewise both on [excalidraw.com](https://excalidraw.com) and in #2993.

**Comment by ad1992** [comment] 2022-12-24 05:48
Awesome that's what I wanted to hear :D, thanks for checking @DanielJGeiger! 
closing this via https://github.com/excalidraw/excalidraw/pull/5996

As per  #5834, it works fine for me

https://user-images.githubusercontent.com/11256141/209423248-f3ae2784-0559-47b6-9003-0fe209fb83f0.mp4

Could you post a shareable link so I can check in the same issue #5834 ?

**Closed by ad1992** 2022-12-24 05:48 UTC
Labels: bug, Binding text / Sticky note

**Comment by ad1992** [comment] 2023-02-03 09:43
@DanielJGeiger @zsviczian do we have any reproducible example for this? I am working on improving the measurements and want to make sure this doesn't break

**Comment by DanielJGeiger** [comment] 2023-02-04 00:02
@ad1992 I have no reproducible example at the moment.  But I imagine #6187 may interact with #6037 as you push more commits.

**Comment by ad1992** [comment] 2023-02-07 10:20
ok I have a reproducible example for this :)
Try adding a character on first line to below element and alignment shouldn't break. It breaks if you try in https://excalidraw-dq7zpgzuc-excalidraw.vercel.app/ (commit before the fix was pushed) 
```
{"type":"excalidraw/clipboard","elements":[{"type":"rectangle","version":1269,"versionNonce":1323841584,"isDeleted":false,"id":"Kww5Tv2GtKr1rYF0iNeIz","fillStyle":"solid","strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,"x":794.5,"y":194,"strokeColor":"black","backgroundColor":"White","width":159,"height":154,"seed":926385200,"groupIds":[],"roundness":null,"boundElements":[{"type":"text","id":"DAH0dfvnYNpxNAk_ro6_8"}],"updated":1675765108320,"link":null,"locked":false},{"type":"text","version":1723,"versionNonce":1829692976,"isDeleted":false,"id":"DAH0dfvnYNpxNAk_ro6_8","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,"x":818.5,"y":233,"strokeColor":"black","backgroundColor":"transparent","width":111,"height":76,"seed":487986896,"groupIds":[],"roundness":null,"boundElements":null,"updated":1675765111299,"link":null,"locked":false,"fontSize":16,"fontFamily":2,"text":"Text positioning\nin\nsticky notes\n...","baseline":72,"textAlign":"center","verticalAlign":"middle","containerId":"Kww5Tv2GtKr1rYF0iNeIz","originalText":"Text positioning\nin\nsticky notes\n..."}],"files":{}}
```
