### ISSUE TITLE
FEATURE   lock item 

### ISSUE THREAD

**Issue by JJger148** [excalidraw/excalidraw#4142] opened 2021-10-30 08:55 UTC
Some items need to be locked, maybe a locking function would be appreciated

**Comment by ad1992** [comment] 2021-11-08 08:12
Hi @JJger148 👋🏻, what do you mean by locking items ?

**Comment by dwelle** [comment] 2021-11-08 14:43
Duplicate of https://github.com/excalidraw/excalidraw/issues/1976 — will be implemented in some form, soon.

**Closed by dwelle** 2021-11-08 14:43 UTC
