### ISSUE TITLE
Hotkeys are not working on Russian keyboard

### ISSUE THREAD

**Issue by AmadeusTwi** [excalidraw/excalidraw#6421] opened 2023-04-05 12:33 UTC
Using russian keyboard leads to some hotkeys (like Ctrl+Z) not working, forcing user to change keyboard language first.

**Comment by ad1992** [comment] 2023-04-24 12:01
Closiing as a duplicate of https://github.com/excalidraw/excalidraw/issues/6194

**Closed by ad1992** 2023-04-24 12:01 UTC
