### ISSUE TITLE
Embeddable excalidraw doesn't ship with types

### ISSUE THREAD

**Issue by bduffany** [excalidraw/excalidraw#3301] opened 2021-03-21 18:06 UTC
The embeddable version of excalidraw doesn't include a `.d.ts` file in the distribution folder, so when using typescript all the type info is lost.

**Comment by ad1992** [comment] 2021-03-21 18:27
@bduffany we will be adding it soon. Its already tracked in https://github.com/excalidraw/excalidraw/issues/2514.
closing this as its duplicate of https://github.com/excalidraw/excalidraw/issues/2514

**Closed by ad1992** 2021-03-21 18:27 UTC
