### ISSUE TITLE
Pasting content from the clipboard on an empty text element is not working

### ISSUE THREAD

**Issue by dvsshadow** [excalidraw/excalidraw#5848] opened 2022-11-08 17:32 UTC
If I create a text element outside a container, and then try to paste the content on my clipboard, nothing happens.
However, if I create a text element inside of a rectangle, for example, I can succesfuly paste the content.

I tested on Firefox, Edge, and Chrome and the issue can be replicated on all of them.

**Comment by DanielJGeiger** [comment] 2022-11-08 17:47
@dvsshadow I'm pretty sure this was a regression in #5845, which assumed the text was in a container.  I pushed a fix for this to #5835.
cc @ad1992 @dwelle

**Comment by ad1992** [comment] 2022-11-08 19:50
Yep, this is a regression that got introduced in my PR. @DanielJGeiger since you have pushed a fix for this, can you create a separate PR for this fix with a test as well? I would like to push the fix first as its a regression

**Comment by dwelle** [comment] 2022-11-30 20:39
Missed this issue. Reopening as there are numerous issues with this still.

**Closed** 2022-12-07 17:35 UTC
Labels: bug
