### ISSUE TITLE
is there any feature for writing a formula

### ISSUE THREAD

**Issue by codroc** [excalidraw/excalidraw#3569] opened 2021-05-12 06:44 UTC
if i need to write a math formula, what can i do?

**Comment by dwelle** [comment] 2021-05-12 20:26
Not at this moment. There's an open PR for it, but it's yet unsure whether it'll be merged (soon). https://github.com/excalidraw/excalidraw/pull/2993

Anyway, closing as duplicate of https://github.com/excalidraw/excalidraw/issues/1176.

**Closed by dwelle** 2021-05-12 20:26 UTC
