### ISSUE TITLE
Some Emoji looks very strange in dark mode

### ISSUE THREAD

**Issue by ShravanSunder** [excalidraw/excalidraw#5782] opened 2022-10-22 11:21 UTC
Some emoji have their colors inverted in dark mode.  

<img width="1192" alt="2022-10-22 1020 Obsidian p dev dPatron 2022 excal encryption flow for dpatron - shravan-pkm - Obsidian v1 0 2" src="https://user-images.githubusercontent.com/5294949/197336304-f087889b-fac5-47c7-a074-da16a61818e9.png">

this is the copied code for that rectangle
```js
{"type":"excalidraw/clipboard","elements":[{"id":"o39dK_nPnN-CA5nFX5coU","type":"rectangle","x":4156.074319007163,"y":1802.677740204419,"width":637,"height":167,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"round","seed":502249042,"version":31,"versionNonce":1701994126,"isDeleted":false,"boundElements":[{"type":"text","id":"2ItrmETe"}],"updated":1666437627932,"link":null,"locked":false},{"id":"2ItrmETe","type":"text","x":4410.574319007163,"y":1868.177740204419,"width":128,"height":36,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"round","seed":1310233998,"version":6,"versionNonce":1857611218,"isDeleted":false,"boundElements":null,"updated":1666437626105,"link":null,"locked":false,"text":"🙋🏽‍♂️ 🧐☘️❓","rawText":"🙋🏽‍♂️ 🧐☘️❓","fontSize":28,"fontFamily":1,"textAlign":"center","verticalAlign":"middle","baseline":25,"containerId":"o39dK_nPnN-CA5nFX5coU","originalText":"🙋🏽‍♂️ 🧐☘️❓"}],"files":{}}
```

**Comment by dwelle** [comment] 2022-10-22 17:50
Yeah, sadly the limitation of how current dark mode works. Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/4336

**Closed by dwelle** 2022-10-22 17:50 UTC
