### ISSUE TITLE
Creating elements at the same time doesn't work

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#906] opened 2020-03-11 15:51 UTC
I'm not 100% sure, but when I tested live-collab with a colleague for a few minutes, we've seen this happening:

When I was creating an element, if my colleague was creating an element at the same time, one of us was prevented from finishing it (maybe it was even cancelled mid-creation, don't recall). After that, I was unable to create new elements and had to select the tool again for it to work.

**Comment by vjeux** [comment] 2020-03-11 16:01
There's an explicit reconciliation step that was introduced. It does handle updates to an element but may not handle a new element added on both sides
https://github.com/excalidraw/excalidraw/blob/83a2f5de28dfaad67fe6f8c14528cd91dbe74be4/src/components/App.tsx#L266-L294

**Comment by petehunt** [comment] 2020-03-11 16:27
Likely caused by https://github.com/excalidraw/excalidraw/pull/898#discussion_r390151892

**Comment by dwelle** [comment] 2020-03-12 17:35
We should certainly retain local-only elements, but during my investigation, this is not what's causing the problem. At least not for arrow/line elements, which are the only ones I can use to test this using two tabs on single device. It seems it somehow mangles the state, but I haven't yet been able to figure out how (on first look the state before/after looks identical).

**Comment by dwelle** [comment] 2020-03-12 17:42
Ok, I think the problem is we're swapping element-being-edited with remote ones. I think we'll need to make `appState.editingElement` point to currently-editing element of any kind, not just `text`. But I wanted to do this change, anyway.

**Comment by vjeux** [comment] 2020-03-15 18:08
This should be fixed by the various refactoring @dwelle and @petehunt did.

**Closed by vjeux** 2020-03-15 18:08 UTC
Labels: bug, collaboration
