### ISSUE TITLE
Dark mode negetives the emojis 

### ISSUE THREAD

**Issue by lemondiee** [excalidraw/excalidraw#7739] opened 2024-03-01 10:16 UTC
In the dark mode, every colour turns 180° which is popular and nice.
But when I type emojis as text, it also alters colour and that doesn't seem nice. I don't know much programming so I cannot contribute but I would suggest something... That to texts either stop allowing emojis and make separate option to input emojis... Or I think need to change the whole thing.

**Comment by boi-doingthings** [comment] 2024-03-04 09:40
Can you share some pictures? It would be helpful in better understanding the issue.

**Comment by bugaddictbose** [comment] 2024-03-08 12:29
Sure - I'm attaching both light and dark theme preview 
![Screenshot_20240308-175802_Chrome](https://github.com/excalidraw/excalidraw/assets/82674039/6eaf7347-c158-4fe7-843d-3a32dfa1b50b)
![Screenshot_20240308-175808_Chrome](https://github.com/excalidraw/excalidraw/assets/82674039/5f79d1c9-d288-4f3c-adbc-ba9077524023)

**Comment by Laurensdc** [comment] 2024-12-04 15:13
Duplicate of #4336

**Comment by Mrazator** [comment] 2024-12-10 13:13
Closing as duplicate.

**Closed by Mrazator** 2024-12-10 13:13 UTC
