### ISSUE TITLE
Incorrect line spacing in sticky notes

### ISSUE THREAD

**Issue by DanielJGeiger** [excalidraw/excalidraw#5847] opened 2022-11-08 15:30 UTC
Sometimes the line spacing is incorrect:
https://excalidraw.com/#json=hW7V4yRbvJJdwGnlQEeY9,OLdnAsjZvCWgHUXZ2llgwQ

**Comment by DanielJGeiger** [comment] 2022-11-08 15:31
![image](https://user-images.githubusercontent.com/1852529/200607010-ad3ea352-4f6f-4d1a-bd74-989a691ca4b4.png)

**Comment by ad1992** [comment] 2022-11-08 19:53
@DanielJGeiger how did you reproduce this scenario? I mean was it typing or pasting it ?

**Comment by DanielJGeiger** [comment] 2022-11-09 22:34
@ad1992 I believe it was actually by manually resizing the container.

**Comment by ad1992** [comment] 2022-12-19 08:10
@DanielJGeiger this should be fixed in https://excalidraw-77vel9y2u-excalidraw.vercel.app/ can you try ?

**Comment by DanielJGeiger** [comment] 2022-12-19 18:03
@ad1992 I have to start an edit on the text element to fix the spacing, but I initially get: https://excalidraw-77vel9y2u-excalidraw.vercel.app/#json=L0hAwykt0OrKiAhc4xfFv,ox4hUnhwrcqUx_lXl3S6bg.  I have to start a second edit before the vertical alignment behaves as expected.

**Comment by ad1992** [comment] 2022-12-20 06:25
> @ad1992 I have to start an edit on the text element to fix the spacing, but I initially get: https://excalidraw-77vel9y2u-excalidraw.vercel.app/#json=L0hAwykt0OrKiAhc4xfFv,ox4hUnhwrcqUx_lXl3S6bg. I have to start a second edit before the vertical alignment behaves as expected.

@DanielJGeiger are you able to reproduce this for new elements in the above link? Also I can see the element is not vertically centered even though vertical alignment is set as center, is this a fresh element or pasted from somewhere ?

 I am not able to reproduce it for new elements and for the one you pinged, the resize works absolutely fine for me which wasn't earlier, as per the element you pinged, its not vertically centered hence the edit is needed

**Comment by DanielJGeiger** [comment] 2022-12-20 16:16
> @DanielJGeiger are you able to reproduce this for new elements in the above link? Also I can see the element is not vertically centered even though vertical alignment is set as center, is this a fresh element or pasted from somewhere ?
> 
> I am not able to reproduce it for new elements and for the one you pinged, the resize works absolutely fine for me which wasn't earlier, as per the element you pinged, its not vertically centered hence the edit is needed

@ad1992 I cannot reproduce it for new elements, either.  The element was neither fresh nor pasted, but transferred from the previous link.  So, it seems you have fixed the issue.

**Comment by ad1992** [comment] 2022-12-21 07:00
Awesome!

**Closed** 2022-12-21 07:02 UTC
Labels: bug, Binding text / Sticky note
