### ISSUE TITLE
Jumping text in Firefox on OSX

### ISSUE THREAD

**Issue by pbowyer** [excalidraw/excalidraw#4822] opened 2022-02-20 10:52 UTC
When I type text into a shape the alignment varies with every character.

https://user-images.githubusercontent.com/89852/154839017-a8af833a-584e-4676-9107-cdc6bdbe6270.mov

Occurring in Firefox 97.0.1 (64-bit) on macOS 12.2.

This does not happen in Chrome on macOS 12.2.

**Comment by dwelle** [comment] 2022-02-21 18:58
Thanks for the report. Can reproduce on Firefox, macOS Big Sur. 

Related to container text-binding. /cc @ad1992

**Comment by gkaemmer** [comment] 2022-03-01 16:57
FWIW this is also happening to me in Chrome 98.0.4758.102 on Big Sur, so it doesn't look firefox-specific.

**Comment by dwelle** [comment] 2022-04-04 11:30
Not sure what the root cause is, but there's a feedback loop between `height` being incorrectly updated in `updateWysiwygStyle()` which triggers another update changing the height again.

Interestingly enough, I can only repro on MacOS Firefox and _only_ on fresh load. Once the tab is reloaded the bug goes away and I need to load excalidraw in a new tab to reproduce again.

**Comment by ad1992** [comment] 2022-04-14 16:38
Yes, this could be browser-related as well it gets fixed on reload even in the latest version `99.0.1` as well.

**Comment by ad1992** [comment] 2022-05-03 09:53
I have pushed a fix for this, can you test it out in https://excalidraw-git-aakansha-jump-excalidraw.vercel.app/ ?

**Comment by ad1992** [comment] 2022-05-04 06:54
closed via #5139

**Closed by ad1992** 2022-05-04 06:54 UTC
Labels: bug, Binding text / Sticky note
