### ISSUE TITLE
Zoom in/out with scroll wheel has no effect on Linux/Firefox

### ISSUE THREAD

**Issue by ubitux** [excalidraw/excalidraw#3234] opened 2021-03-12 15:53 UTC
With Firefox 86.0.1 (and probably older versions, the issue is here since a while) on Linux (X11), the `Ctrl`+scroll wheel up/down has no effect (unless the focus is on the zoom bar, which then applies the native Firefox zoom).

No idea if that's related, but this can be observed in the errors:

![2021-03-12-164843-miT5nijo](https://user-images.githubusercontent.com/34467/110963954-f8396500-8352-11eb-9f00-611cf7c3a008.png)

**Comment by dwelle** [comment] 2021-03-12 22:43
Probably duplicate of https://github.com/excalidraw/excalidraw/issues/3042. We'll need to normalize the scroll delta since Firefox uses really tiny steps which end up being rounded to 0 in our case it seems.

**Comment by ubitux** [comment] 2021-03-12 22:46
> Probably duplicate of #3042. We'll need to normalize the scroll delta since Firefox uses really tiny steps which end up being rounded to 0 in our case it seems.

I was actually initially going to reply there but AFAICT the reporter observe an unusual behaviour, while I can't make any change at all. (Note: `Ctrl`+`+` and `Ctrl`+`-` work as expected, and the `Ctrl`+`Scrollwheel` works on chromium)

**Comment by dwelle** [comment] 2021-11-19 15:29
The scrolling on Firefox should work normally. I've tested on Firefox 93 on Fedora and Firefox 94 Windows 10. If the issues persist, let us know!

**Closed by dwelle** 2021-11-19 15:29 UTC
