### ISSUE TITLE
Can't export with dark mode color palette

### ISSUE THREAD

**Issue by jniziol** [excalidraw/excalidraw#2735] opened 2021-01-06 16:15 UTC
When I export my diagram, it respects the light mode color palette, but not the dark mode color palette. It would be great if it actually in dark mode as well.

**Comment by dwelle** [comment] 2021-01-06 16:27
Yes, so far the dark mode is only for the UI because it's not clear what the default should be and how best to handle this in the UI.

I imagine most people who work in dark mode (me included) don't want their drawings be exported in a color scheme that's based on what time of the day it is.

Anyway, duplicate of https://github.com/excalidraw/excalidraw/issues/2026

**Closed by dwelle** 2021-01-06 16:27 UTC
