### ISSUE TITLE
Chinese fonts without handwriting style

### ISSUE THREAD

**Issue by danielesk** [excalidraw/excalidraw#5370] opened 2022-06-28 06:41 UTC
![image](https://user-images.githubusercontent.com/10652829/176110780-8c8ebbb8-c11b-4a55-83a9-2e443fcdac18.png)

**Comment by lolimay** [comment] 2022-07-12 03:27
Checkout out this [tutorial](https://blog.magicdu.cn/744.html) to customize your own self-hosted version that supports Chinese handwritten fonts.

**Comment by danielesk** [comment] 2022-07-15 01:07
@lolimay Thank you

**Comment by linguax-gc** [comment] 2023-02-17 10:31
> Checkout out this [tutorial](https://blog.magicdu.cn/744.html) to customize your own self-hosted version that supports Chinese handwritten fonts.
> 
> <img alt="image" width="539" src="https://user-images.githubusercontent.com/32427260/178421302-dabf13dc-aa46-4f77-8902-86dece028d60.png">
> 
> Below is the font file I patched with [FontForge](https://fontforge.org/en-US/), which applies [Virgil](https://virgil.excalidraw.com/) as the default handwritten font and uses [XiaoLai](https://github.com/lxgw/kose-font) as the fallback for presenting Simplified Chinese (SC) handwritten fonts.
> 
> **Download**: [Virgil3_with_Xiaolai_as_fallback.ttf.zip](https://github.com/excalidraw/excalidraw/files/9090039/Virgil3_with_Xiaolai_as_fallback.ttf.zip)

Hi, I'm trying to implement this but I must be doing something wrong because it crashes every time I try to open the writing panel on my build. 

I followed the tutorial you mentioned and used the font you provided, since I prefer it to the one on the tutorial. I have zero programming knowledge and just going through trial and error. Would you mind explaining a bit more how to set up the font you provided?

This is what I modified:

"[user]\excalidraw\public\index.html"
`  <link
    rel="preload"
    href="Virgil3_with_Xiaolai_as_fallback.ttf"
    as="font"
    type="font/ttf"
    crossorigin="anonymous"
  />`

"[user]\excalidraw\public\fonts.css"
`@font-face {
  font-family:"XiaoLai";
  src: url("Virgil3_with_Xiaolai_as_fallback.ttf");
  font-display: swap;} `

"[user]\excalidraw\src\constants.ts"
`export const FONT_FAMILY = {
  1: "Virgil",
  2: "Helvetica",
  3: "Cascadia",
  4: "XiaoLai"
} as const;`

"[user]\excalidraw\src\locales\zh-CN.json"
`    "handChinese":"中文手写", `

"[user]\excalidraw\src\actions\actionProperties.tsx"
`      {
        value: FONT_FAMILY.XiaoLai,
        text: t("labels.handChinese"),
        icon: FreedrawIcon,
      },`

I'm getting several errors like this one:
ERROR in src/actions/actionProperties.tsx:664:28

TS2339: Property 'Virgil' does not exist on type '{ readonly 1: "Virgil"; readonly 2: "Helvetica"; readonly 3: "Cascadia"; readonly 4: "XiaoLai"; }'.
    662 |     }[] = [
    663 |       {
  > 664 |         value: FONT_FAMILY.Virgil,
            |                                     ^^^^^^
    665 |         text: t("labels.handDrawn"),
    666 |         icon: FreedrawIcon,
    667 |       },

Maybe @shiqimei or @alswl can give me a hand?

**Comment by alswl** [comment] 2023-02-18 03:31
@linguax-gc As I have mentioned in https://github.com/excalidraw/excalidraw/pull/5604#issue-1345533714 , I do not support using Chinese handwriting fonts with embedded font files.

The cost of embedding font files is very high. There are too many CJK fonts, it may take 5M-20M to store and transfer. This will slow down the loading speed of the website. So I choose the option of using a system that includes fonts.

**Comment by linguax-gc** [comment] 2023-02-18 08:12
@alswl Yes, I read about that and I understand you're reasoning. I ended up compiling an offline version on Docker and simply replacing the Virgil ttf files with the one provided on this thread and it works just fine. But I understand it might not be the best option for the public website.

**Comment by hulkbig** [comment] 2024-03-19 16:11
@danielesk  hi, you can try my fork version: [https://excalidraw-zh.com/](https://excalidraw-zh.com/)

**Comment by DawidWraga** [comment] 2024-06-06 18:47
Incase anyone is wondering, I spent a while figuring this out but I've found a solution.

I've written an article on how to use custom fonts on excalidraw [here](https://dev.to/dawidcodes/how-to-use-a-custom-font-on-excalidrawcom-4jl4)

**Comment by soliviantar** [comment] 2024-06-09 14:09
> Incase anyone is wondering, I spent a while figuring this out but I've found a solution.
> 
> I've written an article on how to use custom fonts on excalidraw [here](https://dev.to/dawidcodes/how-to-use-a-custom-font-on-excalidrawcom-4jl4)

Thanks, @DawidWraga, this is working (when using the pastbin you provided). But how do I add the font to the `code` or `handdrawn` font, instead of `normal`. I tried changing it at the beginning of the script and it didn't work. I also tried it on the `font-style` section of the font-face definition with the same result. Looks like it only works on `normal`?

Also, is it possible to use a non-Google font? Thanks in any case!

**Comment by DawidWraga** [comment] 2024-06-09 14:43
> > Incase anyone is wondering, I spent a while figuring this out but I've found a solution.
> > 
> > I've written an article on how to use custom fonts on excalidraw [here](https://dev.to/dawidcodes/how-to-use-a-custom-font-on-excalidrawcom-4jl4)
> 
> Thanks, @DawidWraga, this is working (when using the pastbin you provided). But how do I add the font to the `code` or `handdrawn` font, instead of `normal`. I tried changing it at the beginning of the script and it didn't work. I also tried it on the `font-style` section of the font-face definition with the same result. Looks like it only works on `normal`?
> 
> Also, is it possible to use a non-Google font? Thanks in any case!

Hello @soliviantar 

Sorry if I don't do a great job explaining it in the article I wrote it quickly.

I tried to override the css variables or manually set the font face of the text but that didn't work.

So in the script provided, we're importing a new font and setting the name of this font so that it overrides the default one.

Put another on way,

This didn't work:
Import (new font as new font)
Handdrawn Font family = new font

This did work:
Import (new font as old font)
Handdrawn font family = still the old font
(but now the new font is overriding the old font)

So whether you get the import script from Google fonts or a different cdn it doesn't matter it just matters that you're overriding the correct font family name

For me overriding Helvetica and Virgil worked for normal and handdrawn respectively, but I couldn't get the code font to change (I gave up quite quick as I only wanted to change the normal)

If it's not working on your end it could be because you're in a different OS so there might be a more specific font that is taking presidence 

To solve it id use developer tools and look at what font families are being applied in your browser. Experiment with setting the new fonts name to one of those and see whether it works.

In my attempts, trying to set the css to a new font didn't work so I think taking the route of changing the font definitions name inside the style import is more likely to work.

Let me know if you find a solution for your system and I'll update the article :)

Best of luck!

**Comment by soliviantar** [comment] 2024-06-09 15:34
Thanks, @DawidWraga.

No problem about the article. I got it to work. I just had to change `app.excalidraw.com` into `excalidraw.com` and understand you had an override on the pastebin code. So I could use other fonts without problem. However, I could only change "normal". 

In order to change "handdrawn", what should I do? Is it just a matter to change `injectCustomFont("normal");` in the script's first line with `injectCustomFont("handdrawn");`? I tried that but it didn't work for me.

I took a look into Developer tools and found Assistant, Cascadia, Circular and Virgil (I'm on Windows 11). So I'm guessing replacing Virgil using `handdrawn` in the script instead of `normal` should work? But it doesn't.

**Comment by Mrazator** [comment] 2024-10-16 19:47
We will be releasing support for the whole CJK soon-ish! (https://github.com/excalidraw/excalidraw/pull/8530)

Feel free to give us early feedback, preview is available here:
https://excalidraw-git-mrazator-first-class-support-chinese-excalidraw.vercel.app/

Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/8408

**Closed by Mrazator** 2024-10-16 19:47 UTC
Labels: font
