### ISSUE TITLE
Lock/unlock selection: It is not possible to Unlock selection [Ctrl+Shift+L] and/or reselect it after Locking selection

### ISSUE THREAD

**Issue by al-bal** [excalidraw/excalidraw#5136] opened 2022-05-02 22:23 UTC
- select several elements, press Ctrl+Shift+L; selection is locked as expected; it is possible to Unlock selection while it is still selected
- select another element

from that point it is not possible to reselect the selection and unlock it; the only way to restore editing is to undo or to load previously saved drawing

**Comment by ad1992** [comment] 2022-05-03 07:11
Yes it's only possible via right-click and unlocks with the context menu once locked

**Comment by dwelle** [comment] 2022-05-03 13:09
@ad1992 it's not a bug?

@al-bal as Aakansha said, you can unlock by right-click. I assume you found out about element locking from the help dialog? @ad1992 I think we should remove it from the help dialog as this will lead to people not knowing how to unlock.

**Comment by ad1992** [comment] 2022-05-03 14:07
Continuing the private chat discussion here -> 
As per UX, I feel it's not intuitive to disable selection and I am not sure why you want to disable selection, even when you right-click the element that gets selected. 
As per the same flow, I select an element -> right click, -> lock, hence I am expecting then when I click on an element again it will select it, and then I can either use the context menu/shortcut to unlock it.
Miro, and Figma both allow the selection of lock elements and show a visual indicator to unlock as well which makes it more intuitive. 
Hence I would suggest we allow selection and show some indicator (eg lock icon) that makes it clear that the element is locked so the user needs to unlock it.

And this is most helpful during collaboration where users don't know which elements are locked and which aren't
And one more thing, disabling selection+ not showing indicator might look like a bug when someone tries to interact with the elements (eg move, resize) unless the user is aware of the lock functionality in Excalidraw

In case we want to disable selection then I suggest showing some indicator that makes it more clear how to unlock and why the selection is disabled but to align with other tools I think we should allow selection + some indicator to unlock when selected as well.

**Comment by ad1992** [comment] 2022-05-03 16:04
closing this and moving the discussion of enabling selection to https://github.com/excalidraw/excalidraw/issues/5141

**Closed by ad1992** 2022-05-03 16:04 UTC
Labels: discussion

**Comment by al-bal** [comment] 2022-05-04 02:18
@dwelle @ad1992 Thank you for andestanding and advice how to unlock locked selection in current implementation.
> you found out about element locking from the help dialog?
exactly
> disabling selection+ not showing indicator might look like a bug
you are perfectly right - this was my initial impression; my bad - I did not check the local menu by right click
> moving the discussion of enabling selection to #5141
it was pleasure to follow you conversation

good luck with indeed an exceptional project!
