### ISSUE TITLE
Grid support

### ISSUE THREAD

**Issue by ntemposd** [excalidraw/excalidraw#1477] opened 2020-04-23 12:34 UTC
Support for grid, having a grid on the background, and using a snap to grid functionality. Google Drawing does this in an excellent way. My colleague @bbarekas proposed this one, catch him for more details he is a diagram expert.

**Comment by lipis** [comment] 2020-04-23 12:37
Yes, that would be nice! :) Thanks @ntemposd! 

Duplicate of #521

**Closed by lipis** 2020-04-23 12:37 UTC
Labels: duplicate
