### ISSUE TITLE
Feature Request: Flip button for arrows/any shapes/a group of them

### ISSUE THREAD

**Issue by mojtabast** [excalidraw/excalidraw#970] opened 2020-03-15 21:27 UTC
Sometimes we need to flip the arrow when drawing, right now it's just possible by using resizing. That would be great to have a button to do that automatically. As an example, Figma has it on the context menu. 

<img width="476" alt="Screen Shot 1398-12-26 at 00 53 13" src="https://user-images.githubusercontent.com/3523430/76710960-e82b7d00-6720-11ea-8f89-876b941fc4a2.png">

**Comment by dwelle** [comment] 2020-03-15 21:40
Is this a request for flipping *just* arrows? And if so, is this a duplicate of https://github.com/excalidraw/excalidraw/issues/616 (switching just the arrow end points), or do you want a general shape horizontal/vertical flip (not just end points, but also the shape)?

**Comment by mojtabast** [comment] 2020-03-15 22:06
I think it can be useful for just arrows because doesn't make sense on other shapes. It just a productivity enhancement.  

Here is a quick demo. 

Current experience:
![excalidraw](https://user-images.githubusercontent.com/3523430/76711509-fa5bea00-6725-11ea-9f50-b44984b8fce1.gif)

Suggested experience (Figma):
![figma](https://user-images.githubusercontent.com/3523430/76711563-8a019880-6726-11ea-861c-2542eb65c706.gif)

**Comment by j-f1** [comment] 2020-03-15 22:11
All the other shapes are symmetric, so it doesn’t matter at this point.

**Comment by mojtabast** [comment] 2020-03-15 22:53
Actually, because we don't have rotating shapes feature here, as @j-f1 said it doesn't matter at that point but if we had, it could be useful there as well:
![rect](https://user-images.githubusercontent.com/3523430/76712326-dc45b800-672c-11ea-9130-2a53dc9f6c9e.gif)

**Comment by lipis** [comment] 2020-10-28 23:29
I think we can live without this..

**Comment by dwelle** [comment] 2020-10-29 20:09
I've had a need for this many times, and it shouldn't be that hard to implement. It's especially useful for mirroring a group of elements. Let's keep this open a bit if someone wanna implement this under a contextMenu.

**Comment by dai-shi** [comment] 2020-10-29 21:40
> useful for mirroring a group of elements

yeah, I wanted this feature for several times.

**Comment by rileyschnee** [comment] 2020-11-06 15:48
Hi! I'm a college CS student that is relatively new to Github open source contributions. I would like to work on this over the next few weeks as a learning experience. Is anyone working on this? If not, how can I be assigned to this?

**Comment by dwelle** [comment] 2020-11-06 16:12
Cool. It may or may not turn out more involved, especially around rotation. If you need help understanding the code, drop in to our chat https://t.co/jWJMO0IcUu?amp=1, or post here.

**Comment by rileyschnee** [comment] 2020-11-23 20:57
Design question: I have been figuring out how to add just the "flip horizontal"/"flip vertical" options to the context menu and it's currently being placed before the "Send backward"/"Send to back". Should this be above "duplicate" or should I leave it where it is? 
![Screen Shot 2020-11-23 at 3 55 16 PM](https://user-images.githubusercontent.com/22105181/100014382-4a567a80-2da4-11eb-91ef-9c0121914189.png)

**Comment by dwelle** [comment] 2020-11-23 22:24
It's fine. We can tweak it in the PR later, if we decide it should be sorted differently.

**Closed** 2021-03-26 15:45 UTC
Labels: discussion, enhancement, good first issue
