### ISSUE TITLE
File saving with incorrect extension

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#2200] opened 2020-10-04 21:03 UTC
When trying to save file, its appending `..excalidraw` instead of `.excalidraw`, as a result of this the file ultimately gets saved as `filename.excalidraw.excalidraw`. Due to this when trying to upload the file, I am not able to upload unless I change the option to `All files` in the upload dialog.
<img width="844" alt="Screenshot 2020-10-05 at 2 21 16 AM" src="https://user-images.githubusercontent.com/11256141/95027000-d4db0180-06b2-11eb-81f9-f50c881c58c0.png">

It's saving with correct extension in the [browser-nativefs demo page](https://browser-nativefs.glitch.me/)

cc @tomayac

**Comment by dwelle** [comment] 2020-10-05 09:42
Duplicate of https://github.com/excalidraw/excalidraw/issues/2151

Fixed in Chrome Beta, and will be fixed in Chrome 86 stable (Oct 8).

**Closed by dwelle** 2020-10-05 09:42 UTC
