### ISSUE TITLE
PWA of Excalidraw can't open and save a local .excalidraw file

### ISSUE THREAD

**Issue by sojusnik** [excalidraw/excalidraw#4238] opened 2021-11-11 14:13 UTC
Although everything is set up like suggested [here](https://github.com/excalidraw/excalidraw/discussions/2714), when double-clicking on a .excalidraw file in Ubuntu's file manager (Nautilus/Files v40.2), then the PWA of Excalidraw is opened with the latest instance and not the instance from the .excalidraw file. The only way to open the local excalidraw file is by using ctrl+o, although double-clicking on in the file manager worked before.

And there's another glitch, when saving a file locally: after pressing ctrl+s in Excalidraw, a text file appears with the same structure as shown [here](https://github.com/excalidraw/excalidraw/discussions/2714#discussioncomment-261437). This file doesn't overwrite the old local file, but creates a new one. Is this due to a bug? As far as I can remember, saving worked very well before.

Excalidraw recently also showed in the left upper corner a hint, that the current instance is running from a local file, this is missing too ATM.

**Comment by aur3l14no** [comment] 2022-01-17 06:36
MacOS is having this issue too. I could open local files before, but now the browser would crash when I try to open one.

**Comment by sojusnik** [comment] 2022-01-17 08:56
Don't know what's causing this, it worked very well before, but then the devs changed something and now we can't open and save files on the fly any more.

**Comment by aur3l14no** [comment] 2022-01-17 11:37
> Tested on Mac, its working for me, could you share a file which is not crashing your browser ?

In fact all file crashes my browser.

1. I open a file. 2. It prompt `allow app to open https link?` 3. I click yes and the browser crashes.

**Comment by dwelle** [comment] 2022-01-24 13:09
I can reproduce the crashing on MacOS (https://github.com/excalidraw/excalidraw/issues/4613), but nothing else from the OP @sojusnik

**Comment by sojusnik** [comment] 2022-01-24 23:03
@dwelle

There are several things involved here. Let's tackle them step by step:

1. Open a new drawing as a PWA of Excalidraw created by the Brave browser. Draw something and press ctrl+s to save the file. You will see, that the drawing will be saved to the default Downloads directory of the Brave browser, without any confirmation. Additionally, this saved file will instantly be opened in a separate window of this PWA. As a result, you now see two open windows with identical content, whereas I expect to see only one window. If you continue to draw something on the second window (the new one) and press ctrl+s again, then another file is saved, as well as another window pops up. So with each saving, an additional file is created and a new window shown, while the old ones remain, displaying the old content.

2. Directly opening an .excalidraw file from the local drive by clicking on it in the file manager doesn't work either, because the PWA, that is assigned to open this type of file, always shows the last opened drawing and not the drawing from the file. But if you use ctrl+o or drag and drop a local file on the PWA window, then finally the drawing from the file appears, without opening another window.

I think that both issues are connected and guess that those recent changes (some months ago?) in presumably `fs-access` have something to do with it, because before everything worked fine.

> And there's another glitch, when saving a file locally: after pressing ctrl+s in Excalidraw, a text file appears with the same structure as shown here. This file doesn't overwrite the old local file, but creates a new one. Is this due to a bug? As far as I can remember, saving worked very well before.

The thing with the text file popping up after saving a file is resolved now, because I forgot to assign this file type to the PWA. But instead of a text file a new PWA window appears now after each saving. 

> Excalidraw recently also showed in the left upper corner a hint, that the current instance is running from a local file, this is missing too ATM.

When the save/load to/from local file feature was working fine, there was a hint in the left upper corner showing it, which is missing now, either due to removal or because this feature isn't working any more.

Observing this on Ubuntu 21.10 with Gnome 40.4.0 and Nautilus 40.2 (= the file manager), while using Brave 1.34.81 Chromium: 97.0.4692.99

**Comment by dwelle** [comment] 2022-01-27 21:37
> Open a new drawing as a PWA of Excalidraw created by the Brave browser. Draw something and press ctrl+s to save the file. You will see, that the drawing will be saved to the default Downloads directory of the Brave browser, without any confirmation.

Sadly, this is due Brave [not supporting the API](https://github.com/brave/brave-browser/issues/11407) we use to enable this. Nothing we can do.

> Additionally, this saved file will instantly be opened in a separate window of this PWA. 

If you mean when opening the downloaded/local file not loading the contents of the file, I'm seeing that as well. I'm not sure what that's about, but I'd wager it's related to the previous point.

In short, if the local filesystem workflow is something important to you, I'd suggest using either Chrome, or Edge browsers. It's possible that other Chromium derivative, such as Vivaldi might support it as well (haven't checked).

**Comment by dwelle** [comment] 2022-01-27 21:39
I'll close this as Brave issue blocked upstream.

@aur3l14no the crashing is caused by a Chrome bug that's fixed in version 99+. Please refer to https://github.com/excalidraw/excalidraw/issues/4613#issuecomment-1023656845 for workarounds.

**Closed by dwelle** 2022-01-27 21:39 UTC
Labels: Brave, blocked-upstream

**Comment by sojusnik** [comment] 2022-01-30 15:28
Good news!

Actually, it is possible to use the local filesystem workflow on Brave. Just enable (from `default` to `enable`) `File Handling API` and `File System Access API` under `brave://flags/` and everything should work again.

**Comment by dwelle** [comment] 2022-01-30 15:50
@sojusnik nice! There were talks about at least exposing it via a flag, so it seems they've already done it. 👍
