### ISSUE TITLE
My thought about how to implement pencil

### ISSUE THREAD

**Issue by Zaynex** [excalidraw/excalidraw#707] opened 2020-02-05 01:07 UTC
What pencil look like:
See the demo: https://codepen.io/michaelsboost/pen/cnCAL .
I just search whiteboard and it give me this one.

How to implement pencil ?
**Any irregular curve consists of several straight lines.**

The data structure of Pencil

```
type PencilShape {
  x1: number,
  y1: number,
  x2: number,
  y2: number
}

type Pencil {
  box: {
    minX: number,
    minY: number,
    maxX: number,
    maxY: number
  },
  shape: PencilShape[],
}
```

`PencilShape` means the start point and end point.
So Pencil.shape means a series of straight lines (A freely drawn curve)
`Pencil.box` means the outline of box.

when user mousedown, we record the last point (x1, y1),
and when user mousemove, we get the current position (x2, y2)
[x1, y1, x2, y2] is one of Pencil.shape.
if user mousemove continue, we will get the new position: [x2, y2, x3, y3].
we need store it to the shape: [[x1, y1, x2, y2], [x2, y2, x3, y3]].The actual array is going to be very long, like:`[[x1, y1, x2, y2], [x2, y2, x3, y3], [x3, y3, x4, y4]...]`.

When you actually save the shape, you'll find that there's a lot of duplication in the data store because the end of the last two arguments in the first array is the beginning of the second array.

We should consider the frequency of data collection, otherwise the array will be extremely large.

In addition, we need to calculate the size of the whole rectangle area.The best way to do this is to compare a point(x, y) when we save it and save the compare result into `box`.

**Comment by Zaynex** [comment] 2020-02-05 14:05
From https://github.com/szimek/signature_pad. I learn something:

The data structure can be more simplify.
The `Pencil.shape` records every point when user move.
So it would like `[[x1, y1], [x2, y2], [x3, y3], [x4, y4]]`. Reduce size by avoiding recording duplicate values.

eg:
```
{ 
  pencil:  {
    box: {
       minX: 100,
       minY: 100,
       maxX: 102,
       maxY: 102
    },
   style: {
      color: 'black',
      width:  4
   },
    shape: [[100, 100], [100, 101], [100, 102], [101, 102], [102, 102]]
  }
}
```

**Comment by j-f1** [comment] 2020-02-21 20:59
I think there should be two modes here: create a multiline shape, or do the variable-width cubic-bezier thing the signature pad repo does. They both convey a handwritten style but in different ways.

**Comment by j-f1** [comment] 2020-03-12 05:00
Looks like this is actually a duplicate of #25.

**Comment by j-f1** [comment] 2020-03-12 05:01
duplicate of #25

**Closed** 2020-03-12 05:01 UTC
Labels: enhancement
