### ISSUE TITLE
implement multiplayer undo/redo

### ISSUE THREAD

**Issue by lizuncong** [excalidraw/excalidraw#6927] opened 2023-08-24 02:26 UTC
As we can see in https://github.com/excalidraw/excalidraw/pull/6926. In the collaborative mode, users can only undo and redo their own modifications, and the data synchronized by other terminals cannot be undone.

**Comment by theonlypwner** [comment] 2023-11-20 23:33
Duplicate of #5375?

**Comment by dwelle** [comment] 2023-11-29 22:03
Will be fixed soon, actively working on it! 🙏

(for now closing as duplicate as noted above)

**Closed by dwelle** 2023-11-29 22:03 UTC
