### ISSUE TITLE
Undo button on screen

### ISSUE THREAD

**Issue by LouisDeconinck** [excalidraw/excalidraw#3560] opened 2021-05-09 20:49 UTC
I use Excalidraw with a drawing tablet. This makes using shortcuts hard. Would it be possible to have an undo button on the screen?

**Comment by dwelle** [comment] 2021-05-09 22:00
Yep. We'll hopefully get it done soon :).

Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/3560

**Closed by dwelle** 2021-05-09 22:00 UTC
