### ISSUE TITLE
Add rubber function 

### ISSUE THREAD

**Issue by JJger148** [excalidraw/excalidraw#4141] opened 2021-10-30 08:52 UTC
There is a need for a rubber, so that it could be used as a note taking tool for handwritten notes. 
maybe even some more pencil functions.

**Comment by ad1992** [comment] 2021-11-08 08:13
closing as a duplicate of https://github.com/excalidraw/excalidraw/issues/3682

**Closed by ad1992** 2021-11-08 08:13 UTC
