### ISSUE TITLE
Wiggling text in boxes

### ISSUE THREAD

**Issue by jsbaudler** [excalidraw/excalidraw#5134] opened 2022-05-02 07:22 UTC
Since some updates I experience an issue when entering text in boxes.

The text 'wiggles' around while typing it in. If you end up with an uneven amount of keystrokes, you have to resize the box to center the text. It only affects the hand-drawn font.

![wigglewiggle](https://user-images.githubusercontent.com/41510184/166198572-d0996e71-a108-4156-92e8-9b522cd58cb1.gif)

It is an ubuntu 22.04 system with chrome 100.0.4896.127 and no addons. I hope this is not a duplicate issue but 5 min researching did not lead me to a similar reported problem.

**Comment by ad1992** [comment] 2022-05-02 07:38
This could be related to OS + browser combination, looks like a duplicate of https://github.com/excalidraw/excalidraw/issues/4822, can you confirm if this is reproducible on refreshing the browser as well? In firefox, it's not reproducible once the browser refreshed on Mac.

**Comment by dwelle** [comment] 2022-05-02 12:01
Yeah, that's a duplicate. We now have reports from Chrome on Ubuntu + MacOS, Firefox on MacOS, and VSCode (unknown OS). The algo needs fixing for sure.

**Comment by ad1992** [comment] 2022-05-02 13:44
In mac it doesn't happen for me on chrome, which version are you using?

**Comment by dwelle** [comment] 2022-05-02 18:16
I can't repro either sadly, but it was reported in #4822. Meaning that it's not isolated to Firefox, albeit it's hard to repro :(.

**Comment by jsbaudler** [comment] 2022-05-03 02:46
I am sorry that this is a duplicate. After trying some more things it gets even weirder.

On a newly installed Chromium I did not experience that issue as well not in Firefox 99, so I double checked all the differences. I came up with that:

![fliffy2](https://user-images.githubusercontent.com/41510184/166397881-d6d5b0fd-8c42-4d29-a406-8c27131e77fb.gif)

This is again the Chrome 100 just in one tab it is logged out without refreshing and in one tab it is logged in. This is reproducible for me.

**Comment by ad1992** [comment] 2022-05-03 07:05
Yes, you are right it does have different results with different font sizes, 

In firefox - It jumps when the font is small and works fine with all other fonts (whereas for you it works for medium but jumps but works for all other fonts)
In Safari - It jumps for xl and works fine in all other fonts
In Chrome - Its works fine for all fonts (but for you doesn't)

And it only jumps for the first line every time when I start typing, after that it's fine.

I am still not sure if it could be related to OS + browser combination but will be looking into this shortly

**Comment by ad1992** [comment] 2022-05-03 09:52
I have pushed a fix for this, can you test it out in https://excalidraw-git-aakansha-jump-excalidraw.vercel.app/ ?

**Comment by jsbaudler** [comment] 2022-05-04 01:55
LGTM. Seems the rounding fixes it. Tested on Firefox 99 and Chrome 100 @ Ubuntu

**Comment by ad1992** [comment] 2022-05-04 05:50
> LGTM. Seems the rounding fixes it. Tested on Firefox 99 and Chrome 100 @ Ubuntu.
> 
> Thank you!

Awesome, thanks for helping in testing it out :)

**Closed** 2022-05-04 05:51 UTC
Labels: duplicate
