### ISSUE TITLE
Scroll to content not working when elements out of view port

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#1662] opened 2020-05-27 13:46 UTC
![Excalidraw _ Hand-drawn look   feel • Collaborative • Secure (2)](https://user-images.githubusercontent.com/11256141/83027736-19dc9080-a04e-11ea-9e4e-0617d0664dc2.gif)

**Comment by lipis** [comment] 2020-05-27 13:54
Duplicate of #1260

**Closed** 2020-05-27 13:54 UTC
